/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Отзывы 2 звезды
 * @export
 * @interface DistributionTableIndicatorsTwoStar
 */
export interface DistributionTableIndicatorsTwoStar {
    /**
     * Прирост оценок за период
     * @type {number}
     * @memberof DistributionTableIndicatorsTwoStar
     */
    current: number;
    /**
     * Динамика по сравнению с предыдущим периодом, %
     * @type {number}
     * @memberof DistributionTableIndicatorsTwoStar
     */
    dynamics?: number;
}

/**
 * Check if a given object implements the DistributionTableIndicatorsTwoStar interface.
 */
export function instanceOfDistributionTableIndicatorsTwoStar(value: object): value is DistributionTableIndicatorsTwoStar {
    if (!('current' in value) || value['current'] === undefined) return false;
    return true;
}

export function DistributionTableIndicatorsTwoStarFromJSON(json: any): DistributionTableIndicatorsTwoStar {
    return DistributionTableIndicatorsTwoStarFromJSONTyped(json, false);
}

export function DistributionTableIndicatorsTwoStarFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistributionTableIndicatorsTwoStar {
    if (json == null) {
        return json;
    }
    return {
        
        'current': json['current'],
        'dynamics': json['dynamics'] == null ? undefined : json['dynamics'],
    };
}

export function DistributionTableIndicatorsTwoStarToJSON(json: any): DistributionTableIndicatorsTwoStar {
    return DistributionTableIndicatorsTwoStarToJSONTyped(json, false);
}

export function DistributionTableIndicatorsTwoStarToJSONTyped(value?: DistributionTableIndicatorsTwoStar | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current': value['current'],
        'dynamics': value['dynamics'],
    };
}

