/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Тип агрегации. Если не указано, то по умолчанию используется агрегация по дням. <br> Доступные уровни агрегации `day`, `week`
 * 
 * @export
 */
export const Level = {
    Day: 'day',
    Week: 'week'
} as const;
export type Level = typeof Level[keyof typeof Level];


export function instanceOfLevel(value: any): boolean {
    for (const key in Level) {
        if (Object.prototype.hasOwnProperty.call(Level, key)) {
            if (Level[key as keyof typeof Level] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LevelFromJSON(json: any): Level {
    return LevelFromJSONTyped(json, false);
}

export function LevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Level {
    return json as Level;
}

export function LevelToJSON(value?: Level | null): any {
    return value as any;
}

export function LevelToJSONTyped(value: any, ignoreDiscriminator: boolean): Level {
    return value as Level;
}

