/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV) 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderBy } from './OrderBy';
import {
    OrderByFromJSON,
    OrderByFromJSONTyped,
    OrderByToJSON,
    OrderByToJSONTyped,
} from './OrderBy';
import type { PastPeriod } from './PastPeriod';
import {
    PastPeriodFromJSON,
    PastPeriodFromJSONTyped,
    PastPeriodToJSON,
    PastPeriodToJSONTyped,
} from './PastPeriod';
import type { PositionCluster } from './PositionCluster';
import {
    PositionClusterFromJSON,
    PositionClusterFromJSONTyped,
    PositionClusterToJSON,
    PositionClusterToJSONTyped,
} from './PositionCluster';
import type { Period } from './Period';
import {
    PeriodFromJSON,
    PeriodFromJSONTyped,
    PeriodToJSON,
    PeriodToJSONTyped,
} from './Period';

/**
 * Параметры запроса для формирования главной страницы:
 *   - `currentPeriod` — текущий период
 *   - `pastPeriod` — предыдущий период для сравнения
 * 
 * @export
 * @interface MainRequest
 */
export interface MainRequest {
    /**
     * 
     * @type {Period}
     * @memberof MainRequest
     */
    currentPeriod: Period;
    /**
     * 
     * @type {PastPeriod}
     * @memberof MainRequest
     */
    pastPeriod?: PastPeriod;
    /**
     * Список артикулов WB для фильтрации
     * @type {Array<number>}
     * @memberof MainRequest
     */
    nmIds?: Array<number>;
    /**
     * Список ID предметов для фильтрации
     * @type {Array<number>}
     * @memberof MainRequest
     */
    subjectIds?: Array<number>;
    /**
     * Список брендов для фильтрации
     * @type {Array<string>}
     * @memberof MainRequest
     */
    brandNames?: Array<string>;
    /**
     * Список ID ярлыков для фильтрации
     * @type {Array<number>}
     * @memberof MainRequest
     */
    tagIds?: Array<number>;
    /**
     * 
     * @type {PositionCluster}
     * @memberof MainRequest
     */
    positionCluster: PositionCluster;
    /**
     * 
     * @type {OrderBy}
     * @memberof MainRequest
     */
    orderBy: OrderBy;
    /**
     * Показать данные по прямым запросам с [подменным артикулом](https://seller.wildberries.ru/help-center/article/A-524)
     * @type {boolean}
     * @memberof MainRequest
     */
    includeSubstitutedSKUs?: boolean;
    /**
     * Показать данные по поисковым запросам без учёта подменного артикула
     * @type {boolean}
     * @memberof MainRequest
     */
    includeSearchTexts?: boolean;
    /**
     * Количество групп товаров в ответе
     * @type {number}
     * @memberof MainRequest
     */
    limit: number;
    /**
     * После какого элемента выдавать данные
     * @type {number}
     * @memberof MainRequest
     */
    offset: number;
}



/**
 * Check if a given object implements the MainRequest interface.
 */
export function instanceOfMainRequest(value: object): value is MainRequest {
    if (!('currentPeriod' in value) || value['currentPeriod'] === undefined) return false;
    if (!('positionCluster' in value) || value['positionCluster'] === undefined) return false;
    if (!('orderBy' in value) || value['orderBy'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function MainRequestFromJSON(json: any): MainRequest {
    return MainRequestFromJSONTyped(json, false);
}

export function MainRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPeriod': PeriodFromJSON(json['currentPeriod']),
        'pastPeriod': json['pastPeriod'] == null ? undefined : PastPeriodFromJSON(json['pastPeriod']),
        'nmIds': json['nmIds'] == null ? undefined : json['nmIds'],
        'subjectIds': json['subjectIds'] == null ? undefined : json['subjectIds'],
        'brandNames': json['brandNames'] == null ? undefined : json['brandNames'],
        'tagIds': json['tagIds'] == null ? undefined : json['tagIds'],
        'positionCluster': PositionClusterFromJSON(json['positionCluster']),
        'orderBy': OrderByFromJSON(json['orderBy']),
        'includeSubstitutedSKUs': json['includeSubstitutedSKUs'] == null ? undefined : json['includeSubstitutedSKUs'],
        'includeSearchTexts': json['includeSearchTexts'] == null ? undefined : json['includeSearchTexts'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function MainRequestToJSON(json: any): MainRequest {
    return MainRequestToJSONTyped(json, false);
}

export function MainRequestToJSONTyped(value?: MainRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPeriod': PeriodToJSON(value['currentPeriod']),
        'pastPeriod': PastPeriodToJSON(value['pastPeriod']),
        'nmIds': value['nmIds'],
        'subjectIds': value['subjectIds'],
        'brandNames': value['brandNames'],
        'tagIds': value['tagIds'],
        'positionCluster': PositionClusterToJSON(value['positionCluster']),
        'orderBy': OrderByToJSON(value['orderBy']),
        'includeSubstitutedSKUs': value['includeSubstitutedSKUs'],
        'includeSearchTexts': value['includeSearchTexts'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

