/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostSalesFunnelProducts402Response
 */
export interface PostSalesFunnelProducts402Response {
    /**
     * Заголовок ошибки
     * @type {string}
     * @memberof PostSalesFunnelProducts402Response
     */
    title?: string;
    /**
     * Детали ошибки. Ошибка возвращается только сервисам из [Каталога решений для бизнеса](https://dev.wildberries.ru/business-solutions)
     * @type {string}
     * @memberof PostSalesFunnelProducts402Response
     */
    detail?: string;
}

/**
 * Check if a given object implements the PostSalesFunnelProducts402Response interface.
 */
export function instanceOfPostSalesFunnelProducts402Response(value: object): value is PostSalesFunnelProducts402Response {
    return true;
}

export function PostSalesFunnelProducts402ResponseFromJSON(json: any): PostSalesFunnelProducts402Response {
    return PostSalesFunnelProducts402ResponseFromJSONTyped(json, false);
}

export function PostSalesFunnelProducts402ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSalesFunnelProducts402Response {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function PostSalesFunnelProducts402ResponseToJSON(json: any): PostSalesFunnelProducts402Response {
    return PostSalesFunnelProducts402ResponseToJSONTyped(json, false);
}

export function PostSalesFunnelProducts402ResponseToJSONTyped(value?: PostSalesFunnelProducts402Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'detail': value['detail'],
    };
}

