/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV) 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductOrdersMetrics } from './ProductOrdersMetrics';
import {
    ProductOrdersMetricsFromJSON,
    ProductOrdersMetricsFromJSONTyped,
    ProductOrdersMetricsToJSON,
    ProductOrdersMetricsToJSONTyped,
} from './ProductOrdersMetrics';
import type { ProductOrdersTextItem } from './ProductOrdersTextItem';
import {
    ProductOrdersTextItemFromJSON,
    ProductOrdersTextItemFromJSONTyped,
    ProductOrdersTextItemToJSON,
    ProductOrdersTextItemToJSONTyped,
} from './ProductOrdersTextItem';

/**
 * 
 * @export
 * @interface ProductOrdersResponse
 */
export interface ProductOrdersResponse {
    /**
     * Итог по товарам
     * @type {Array<ProductOrdersMetrics>}
     * @memberof ProductOrdersResponse
     */
    total: Array<ProductOrdersMetrics>;
    /**
     * Элементы таблицы
     * @type {Array<ProductOrdersTextItem>}
     * @memberof ProductOrdersResponse
     */
    items: Array<ProductOrdersTextItem>;
}

/**
 * Check if a given object implements the ProductOrdersResponse interface.
 */
export function instanceOfProductOrdersResponse(value: object): value is ProductOrdersResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ProductOrdersResponseFromJSON(json: any): ProductOrdersResponse {
    return ProductOrdersResponseFromJSONTyped(json, false);
}

export function ProductOrdersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductOrdersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'total': ((json['total'] as Array<any>).map(ProductOrdersMetricsFromJSON)),
        'items': ((json['items'] as Array<any>).map(ProductOrdersTextItemFromJSON)),
    };
}

export function ProductOrdersResponseToJSON(json: any): ProductOrdersResponse {
    return ProductOrdersResponseToJSONTyped(json, false);
}

export function ProductOrdersResponseToJSONTyped(value?: ProductOrdersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': ((value['total'] as Array<any>).map(ProductOrdersMetricsToJSON)),
        'items': ((value['items'] as Array<any>).map(ProductOrdersTextItemToJSON)),
    };
}

