/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatisticsPast } from './StatisticsPast';
import {
    StatisticsPastFromJSON,
    StatisticsPastFromJSONTyped,
    StatisticsPastToJSON,
    StatisticsPastToJSONTyped,
} from './StatisticsPast';
import type { StatisticsSelected } from './StatisticsSelected';
import {
    StatisticsSelectedFromJSON,
    StatisticsSelectedFromJSONTyped,
    StatisticsSelectedToJSON,
    StatisticsSelectedToJSONTyped,
} from './StatisticsSelected';
import type { StatisticsComparison } from './StatisticsComparison';
import {
    StatisticsComparisonFromJSON,
    StatisticsComparisonFromJSONTyped,
    StatisticsComparisonToJSON,
    StatisticsComparisonToJSONTyped,
} from './StatisticsComparison';

/**
 * 
 * @export
 * @interface ProductsResponseProductsInnerStatistic
 */
export interface ProductsResponseProductsInnerStatistic {
    /**
     * 
     * @type {StatisticsSelected}
     * @memberof ProductsResponseProductsInnerStatistic
     */
    selected: StatisticsSelected;
    /**
     * 
     * @type {StatisticsPast}
     * @memberof ProductsResponseProductsInnerStatistic
     */
    past?: StatisticsPast;
    /**
     * 
     * @type {StatisticsComparison}
     * @memberof ProductsResponseProductsInnerStatistic
     */
    comparison?: StatisticsComparison;
}

/**
 * Check if a given object implements the ProductsResponseProductsInnerStatistic interface.
 */
export function instanceOfProductsResponseProductsInnerStatistic(value: object): value is ProductsResponseProductsInnerStatistic {
    if (!('selected' in value) || value['selected'] === undefined) return false;
    return true;
}

export function ProductsResponseProductsInnerStatisticFromJSON(json: any): ProductsResponseProductsInnerStatistic {
    return ProductsResponseProductsInnerStatisticFromJSONTyped(json, false);
}

export function ProductsResponseProductsInnerStatisticFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsResponseProductsInnerStatistic {
    if (json == null) {
        return json;
    }
    return {
        
        'selected': StatisticsSelectedFromJSON(json['selected']),
        'past': json['past'] == null ? undefined : StatisticsPastFromJSON(json['past']),
        'comparison': json['comparison'] == null ? undefined : StatisticsComparisonFromJSON(json['comparison']),
    };
}

export function ProductsResponseProductsInnerStatisticToJSON(json: any): ProductsResponseProductsInnerStatistic {
    return ProductsResponseProductsInnerStatisticToJSONTyped(json, false);
}

export function ProductsResponseProductsInnerStatisticToJSONTyped(value?: ProductsResponseProductsInnerStatistic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'selected': StatisticsSelectedToJSON(value['selected']),
        'past': StatisticsPastToJSON(value['past']),
        'comparison': StatisticsComparisonToJSON(value['comparison']),
    };
}

