/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV) 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Тип складов хранения товаров:
 *   - `""` — все
 *   - `wb` — Склады WB
 *   - `mp` — Склады продавца
 * 
 * @export
 */
export const StockType = {
    Empty: '',
    Wb: 'wb',
    Mp: 'mp'
} as const;
export type StockType = typeof StockType[keyof typeof StockType];


export function instanceOfStockType(value: any): boolean {
    for (const key in StockType) {
        if (Object.prototype.hasOwnProperty.call(StockType, key)) {
            if (StockType[key as keyof typeof StockType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StockTypeFromJSON(json: any): StockType {
    return StockTypeFromJSONTyped(json, false);
}

export function StockTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockType {
    return json as StockType;
}

export function StockTypeToJSON(value?: StockType | null): any {
    return value as any;
}

export function StockTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): StockType {
    return value as StockType;
}

