/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV) 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TableShippingOfficeItem } from './TableShippingOfficeItem';
import {
    TableShippingOfficeItemFromJSON,
    TableShippingOfficeItemFromJSONTyped,
    TableShippingOfficeItemToJSON,
    TableShippingOfficeItemToJSONTyped,
} from './TableShippingOfficeItem';

/**
 * 
 * @export
 * @interface TableShippingOfficeResponse
 */
export interface TableShippingOfficeResponse {
    /**
     * Множество данных по регионам отгрузки
     * @type {Array<TableShippingOfficeItem>}
     * @memberof TableShippingOfficeResponse
     */
    regions?: Array<TableShippingOfficeItem>;
}

/**
 * Check if a given object implements the TableShippingOfficeResponse interface.
 */
export function instanceOfTableShippingOfficeResponse(value: object): value is TableShippingOfficeResponse {
    return true;
}

export function TableShippingOfficeResponseFromJSON(json: any): TableShippingOfficeResponse {
    return TableShippingOfficeResponseFromJSONTyped(json, false);
}

export function TableShippingOfficeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableShippingOfficeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'regions': json['regions'] == null ? undefined : ((json['regions'] as Array<any>).map(TableShippingOfficeItemFromJSON)),
    };
}

export function TableShippingOfficeResponseToJSON(json: any): TableShippingOfficeResponse {
    return TableShippingOfficeResponseToJSONTyped(json, false);
}

export function TableShippingOfficeResponseToJSONTyped(value?: TableShippingOfficeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'regions': value['regions'] == null ? undefined : ((value['regions'] as Array<any>).map(TableShippingOfficeItemToJSON)),
    };
}

