/*
Заказы DBS

<div class=\"description_important\">     Узнать больше о заказах DBS можно в <a href=\"https://seller.wildberries.ru/instructions/category/6572e024-7428-4db1-86a8-a4c7dbebbfcf?goBackOption=prevRoute&categoryId=5a8e1202-0865-45b7-acae-5d0afc7add56\">справочном центре</a> </div>  Управление [сборочными заданиями](/openapi/orders-dbs#tag/Sborochnye-zadaniya-DBS) и [метаданными](/openapi/orders-dbs#tag/Metadannye-DBS) заказов DBS (Delivery by Seller). 

API version: order
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orders_dbs

import (
	"encoding/json"
)

// checks if the ApiV3DbsOrdersOrderIdMetaSgtinPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV3DbsOrdersOrderIdMetaSgtinPutRequest{}

// ApiV3DbsOrdersOrderIdMetaSgtinPutRequest struct for ApiV3DbsOrdersOrderIdMetaSgtinPutRequest
type ApiV3DbsOrdersOrderIdMetaSgtinPutRequest struct {
	// Массив кодов маркировки. Допускается от 16 до 135 символов для кода одной маркировки.
	Sgtins []string `json:"sgtins,omitempty"`
}

// NewApiV3DbsOrdersOrderIdMetaSgtinPutRequest instantiates a new ApiV3DbsOrdersOrderIdMetaSgtinPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV3DbsOrdersOrderIdMetaSgtinPutRequest() *ApiV3DbsOrdersOrderIdMetaSgtinPutRequest {
	this := ApiV3DbsOrdersOrderIdMetaSgtinPutRequest{}
	return &this
}

// NewApiV3DbsOrdersOrderIdMetaSgtinPutRequestWithDefaults instantiates a new ApiV3DbsOrdersOrderIdMetaSgtinPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV3DbsOrdersOrderIdMetaSgtinPutRequestWithDefaults() *ApiV3DbsOrdersOrderIdMetaSgtinPutRequest {
	this := ApiV3DbsOrdersOrderIdMetaSgtinPutRequest{}
	return &this
}

// GetSgtins returns the Sgtins field value if set, zero value otherwise.
func (o *ApiV3DbsOrdersOrderIdMetaSgtinPutRequest) GetSgtins() []string {
	if o == nil || IsNil(o.Sgtins) {
		var ret []string
		return ret
	}
	return o.Sgtins
}

// GetSgtinsOk returns a tuple with the Sgtins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV3DbsOrdersOrderIdMetaSgtinPutRequest) GetSgtinsOk() ([]string, bool) {
	if o == nil || IsNil(o.Sgtins) {
		return nil, false
	}
	return o.Sgtins, true
}

// HasSgtins returns a boolean if a field has been set.
func (o *ApiV3DbsOrdersOrderIdMetaSgtinPutRequest) HasSgtins() bool {
	if o != nil && !IsNil(o.Sgtins) {
		return true
	}

	return false
}

// SetSgtins gets a reference to the given []string and assigns it to the Sgtins field.
func (o *ApiV3DbsOrdersOrderIdMetaSgtinPutRequest) SetSgtins(v []string) {
	o.Sgtins = v
}

func (o ApiV3DbsOrdersOrderIdMetaSgtinPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV3DbsOrdersOrderIdMetaSgtinPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sgtins) {
		toSerialize["sgtins"] = o.Sgtins
	}
	return toSerialize, nil
}

type NullableApiV3DbsOrdersOrderIdMetaSgtinPutRequest struct {
	value *ApiV3DbsOrdersOrderIdMetaSgtinPutRequest
	isSet bool
}

func (v NullableApiV3DbsOrdersOrderIdMetaSgtinPutRequest) Get() *ApiV3DbsOrdersOrderIdMetaSgtinPutRequest {
	return v.value
}

func (v *NullableApiV3DbsOrdersOrderIdMetaSgtinPutRequest) Set(val *ApiV3DbsOrdersOrderIdMetaSgtinPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV3DbsOrdersOrderIdMetaSgtinPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV3DbsOrdersOrderIdMetaSgtinPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV3DbsOrdersOrderIdMetaSgtinPutRequest(val *ApiV3DbsOrdersOrderIdMetaSgtinPutRequest) *NullableApiV3DbsOrdersOrderIdMetaSgtinPutRequest {
	return &NullableApiV3DbsOrdersOrderIdMetaSgtinPutRequest{value: val, isSet: true}
}

func (v NullableApiV3DbsOrdersOrderIdMetaSgtinPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV3DbsOrdersOrderIdMetaSgtinPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


