/*
Общее

В этом разделе:   - [общая информация о WB API](/openapi/api-information#tag/Vvedenie)   - как [начать работу с WB API](/openapi/api-information#tag/Vvedenie/Kak-nachat-rabotu-s-API)   - как [авторизоваться](/openapi/api-information#tag/Avtorizaciya) и [создавать токены](/openapi/api-information#tag/Avtorizaciya/Kak-sozdat-personalnyj-bazovyj-ili-testovyj-token)   - основные [статус-коды ответов](/openapi/api-information#tag/Vvedenie/Status-kody-HTTP)   - [лимиты запросов](/openapi/api-information#tag/Vvedenie/Limity-zaprosov)   - как обратиться в [поддержку](/openapi/api-information#tag/Vvedenie/Podderzhka)  С помощью методов этого раздела вы можете:   - проверить [подключение к WB API](/openapi/api-information#tag/Proverka-podklyucheniya-k-WB-API/paths/~1ping/get)   - получить [новости портала продавцов](/openapi/api-information#tag/API-novostej/paths/~1api~1communications~1v2~1news/get)   - получить [информацию о продавце](/openapi/api-information#tag/Informaciya-o-prodavce/paths/~1api~1v1~1seller-info/get)   - [управлять пользователями продавца](/openapi/api-information#tag/Upravlenie-polzovatelyami-prodavca) 

API version: general
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package general

import (
	"encoding/json"
)

// checks if the ApiV1SellerInfoGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1SellerInfoGet200Response{}

// ApiV1SellerInfoGet200Response struct for ApiV1SellerInfoGet200Response
type ApiV1SellerInfoGet200Response struct {
	// Наименование продавца
	Name *string `json:"name,omitempty"`
	// Уникальный ID продавца на Wildberries, [находящийся в публичном поле токена](./api-information#tag/Avtorizaciya/Kak-ustroen-token)
	Sid *string `json:"sid,omitempty"`
	// Торговое наименование продавца
	TradeMark *string `json:"tradeMark,omitempty"`
}

// NewApiV1SellerInfoGet200Response instantiates a new ApiV1SellerInfoGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1SellerInfoGet200Response() *ApiV1SellerInfoGet200Response {
	this := ApiV1SellerInfoGet200Response{}
	return &this
}

// NewApiV1SellerInfoGet200ResponseWithDefaults instantiates a new ApiV1SellerInfoGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1SellerInfoGet200ResponseWithDefaults() *ApiV1SellerInfoGet200Response {
	this := ApiV1SellerInfoGet200Response{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApiV1SellerInfoGet200Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1SellerInfoGet200Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApiV1SellerInfoGet200Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApiV1SellerInfoGet200Response) SetName(v string) {
	o.Name = &v
}

// GetSid returns the Sid field value if set, zero value otherwise.
func (o *ApiV1SellerInfoGet200Response) GetSid() string {
	if o == nil || IsNil(o.Sid) {
		var ret string
		return ret
	}
	return *o.Sid
}

// GetSidOk returns a tuple with the Sid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1SellerInfoGet200Response) GetSidOk() (*string, bool) {
	if o == nil || IsNil(o.Sid) {
		return nil, false
	}
	return o.Sid, true
}

// HasSid returns a boolean if a field has been set.
func (o *ApiV1SellerInfoGet200Response) HasSid() bool {
	if o != nil && !IsNil(o.Sid) {
		return true
	}

	return false
}

// SetSid gets a reference to the given string and assigns it to the Sid field.
func (o *ApiV1SellerInfoGet200Response) SetSid(v string) {
	o.Sid = &v
}

// GetTradeMark returns the TradeMark field value if set, zero value otherwise.
func (o *ApiV1SellerInfoGet200Response) GetTradeMark() string {
	if o == nil || IsNil(o.TradeMark) {
		var ret string
		return ret
	}
	return *o.TradeMark
}

// GetTradeMarkOk returns a tuple with the TradeMark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1SellerInfoGet200Response) GetTradeMarkOk() (*string, bool) {
	if o == nil || IsNil(o.TradeMark) {
		return nil, false
	}
	return o.TradeMark, true
}

// HasTradeMark returns a boolean if a field has been set.
func (o *ApiV1SellerInfoGet200Response) HasTradeMark() bool {
	if o != nil && !IsNil(o.TradeMark) {
		return true
	}

	return false
}

// SetTradeMark gets a reference to the given string and assigns it to the TradeMark field.
func (o *ApiV1SellerInfoGet200Response) SetTradeMark(v string) {
	o.TradeMark = &v
}

func (o ApiV1SellerInfoGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1SellerInfoGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Sid) {
		toSerialize["sid"] = o.Sid
	}
	if !IsNil(o.TradeMark) {
		toSerialize["tradeMark"] = o.TradeMark
	}
	return toSerialize, nil
}

type NullableApiV1SellerInfoGet200Response struct {
	value *ApiV1SellerInfoGet200Response
	isSet bool
}

func (v NullableApiV1SellerInfoGet200Response) Get() *ApiV1SellerInfoGet200Response {
	return v.value
}

func (v *NullableApiV1SellerInfoGet200Response) Set(val *ApiV1SellerInfoGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1SellerInfoGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1SellerInfoGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1SellerInfoGet200Response(val *ApiV1SellerInfoGet200Response) *NullableApiV1SellerInfoGet200Response {
	return &NullableApiV1SellerInfoGet200Response{value: val, isSet: true}
}

func (v NullableApiV1SellerInfoGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1SellerInfoGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


