/*
Wildberries Цифровой

По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 

API version: wbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbd

import (
	"encoding/json"
)

// checks if the UploadInitResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadInitResponse{}

// UploadInitResponse Ответ. Содержит UUID контента, необходимый для метода [Загрузить контент (файл)](./wbd#tag/Kontent/operation/contentUploadChunk) 
type UploadInitResponse struct {
	// ID контента
	ContentId *int64 `json:"content_id,omitempty"`
	// Уникальный ID. Этот ID необходим для загрузки самого файла в методе [Загрузка контента (файла)](./wbd#tag/Kontent/operation/contentUploadChunk) 
	Uuid *string `json:"uuid,omitempty"`
}

// NewUploadInitResponse instantiates a new UploadInitResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadInitResponse() *UploadInitResponse {
	this := UploadInitResponse{}
	return &this
}

// NewUploadInitResponseWithDefaults instantiates a new UploadInitResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadInitResponseWithDefaults() *UploadInitResponse {
	this := UploadInitResponse{}
	return &this
}

// GetContentId returns the ContentId field value if set, zero value otherwise.
func (o *UploadInitResponse) GetContentId() int64 {
	if o == nil || IsNil(o.ContentId) {
		var ret int64
		return ret
	}
	return *o.ContentId
}

// GetContentIdOk returns a tuple with the ContentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadInitResponse) GetContentIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ContentId) {
		return nil, false
	}
	return o.ContentId, true
}

// HasContentId returns a boolean if a field has been set.
func (o *UploadInitResponse) HasContentId() bool {
	if o != nil && !IsNil(o.ContentId) {
		return true
	}

	return false
}

// SetContentId gets a reference to the given int64 and assigns it to the ContentId field.
func (o *UploadInitResponse) SetContentId(v int64) {
	o.ContentId = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *UploadInitResponse) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadInitResponse) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *UploadInitResponse) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *UploadInitResponse) SetUuid(v string) {
	o.Uuid = &v
}

func (o UploadInitResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadInitResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContentId) {
		toSerialize["content_id"] = o.ContentId
	}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	return toSerialize, nil
}

type NullableUploadInitResponse struct {
	value *UploadInitResponse
	isSet bool
}

func (v NullableUploadInitResponse) Get() *UploadInitResponse {
	return v.value
}

func (v *NullableUploadInitResponse) Set(val *UploadInitResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadInitResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadInitResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadInitResponse(val *UploadInitResponse) *NullableUploadInitResponse {
	return &NullableUploadInitResponse{value: val, isSet: true}
}

func (v NullableUploadInitResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadInitResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


