/*
Wildberries Цифровой

По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 

API version: wbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbd

import (
	"encoding/json"
)

// checks if the UploadChunkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadChunkResponse{}

// UploadChunkResponse Файл успешно загружен.<br> Ответ содержит URI адрес контента 
type UploadChunkResponse struct {
	// Количество переданных фреймов (частей контента)
	Chunk *int32 `json:"chunk,omitempty"`
	// URI адреса загруженного файла 
	Uri *string `json:"uri,omitempty"`
}

// NewUploadChunkResponse instantiates a new UploadChunkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadChunkResponse() *UploadChunkResponse {
	this := UploadChunkResponse{}
	return &this
}

// NewUploadChunkResponseWithDefaults instantiates a new UploadChunkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadChunkResponseWithDefaults() *UploadChunkResponse {
	this := UploadChunkResponse{}
	return &this
}

// GetChunk returns the Chunk field value if set, zero value otherwise.
func (o *UploadChunkResponse) GetChunk() int32 {
	if o == nil || IsNil(o.Chunk) {
		var ret int32
		return ret
	}
	return *o.Chunk
}

// GetChunkOk returns a tuple with the Chunk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadChunkResponse) GetChunkOk() (*int32, bool) {
	if o == nil || IsNil(o.Chunk) {
		return nil, false
	}
	return o.Chunk, true
}

// HasChunk returns a boolean if a field has been set.
func (o *UploadChunkResponse) HasChunk() bool {
	if o != nil && !IsNil(o.Chunk) {
		return true
	}

	return false
}

// SetChunk gets a reference to the given int32 and assigns it to the Chunk field.
func (o *UploadChunkResponse) SetChunk(v int32) {
	o.Chunk = &v
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *UploadChunkResponse) GetUri() string {
	if o == nil || IsNil(o.Uri) {
		var ret string
		return ret
	}
	return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadChunkResponse) GetUriOk() (*string, bool) {
	if o == nil || IsNil(o.Uri) {
		return nil, false
	}
	return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *UploadChunkResponse) HasUri() bool {
	if o != nil && !IsNil(o.Uri) {
		return true
	}

	return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *UploadChunkResponse) SetUri(v string) {
	o.Uri = &v
}

func (o UploadChunkResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadChunkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Chunk) {
		toSerialize["chunk"] = o.Chunk
	}
	if !IsNil(o.Uri) {
		toSerialize["uri"] = o.Uri
	}
	return toSerialize, nil
}

type NullableUploadChunkResponse struct {
	value *UploadChunkResponse
	isSet bool
}

func (v NullableUploadChunkResponse) Get() *UploadChunkResponse {
	return v.value
}

func (v *NullableUploadChunkResponse) Set(val *UploadChunkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadChunkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadChunkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadChunkResponse(val *UploadChunkResponse) *NullableUploadChunkResponse {
	return &NullableUploadChunkResponse{value: val, isSet: true}
}

func (v NullableUploadChunkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadChunkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


