/*
Wildberries Цифровой

По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 

API version: wbd
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbd

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProblemDetails400 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProblemDetails400{}

// ProblemDetails400 struct for ProblemDetails400
type ProblemDetails400 struct {
	// Дубликат HTTP статус-код
	Status *int32 `json:"status,omitempty"`
	// Короткое описание ошибки
	Title string `json:"title"`
	// Развернутое описание ошибки
	Detail *string `json:"detail,omitempty"`
	// Служебная информация об ошибке
	Code *string `json:"code,omitempty"`
	// Массив ошибок. Для передачи нескольких ошибок 
	Errors []ProblemDetails400 `json:"errors,omitempty"`
	// ID запроса. Дубликат заголовка `X-Request-Id` 
	RequestId string `json:"requestId"`
	// Имя сервиса
	Origin *string `json:"origin,omitempty"`
}

type _ProblemDetails400 ProblemDetails400

// NewProblemDetails400 instantiates a new ProblemDetails400 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProblemDetails400(title string, requestId string) *ProblemDetails400 {
	this := ProblemDetails400{}
	this.Title = title
	this.RequestId = requestId
	return &this
}

// NewProblemDetails400WithDefaults instantiates a new ProblemDetails400 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProblemDetails400WithDefaults() *ProblemDetails400 {
	this := ProblemDetails400{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ProblemDetails400) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProblemDetails400) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ProblemDetails400) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *ProblemDetails400) SetStatus(v int32) {
	o.Status = &v
}

// GetTitle returns the Title field value
func (o *ProblemDetails400) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ProblemDetails400) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ProblemDetails400) SetTitle(v string) {
	o.Title = v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *ProblemDetails400) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProblemDetails400) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *ProblemDetails400) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *ProblemDetails400) SetDetail(v string) {
	o.Detail = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ProblemDetails400) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProblemDetails400) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ProblemDetails400) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ProblemDetails400) SetCode(v string) {
	o.Code = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ProblemDetails400) GetErrors() []ProblemDetails400 {
	if o == nil || IsNil(o.Errors) {
		var ret []ProblemDetails400
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProblemDetails400) GetErrorsOk() ([]ProblemDetails400, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ProblemDetails400) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ProblemDetails400 and assigns it to the Errors field.
func (o *ProblemDetails400) SetErrors(v []ProblemDetails400) {
	o.Errors = v
}

// GetRequestId returns the RequestId field value
func (o *ProblemDetails400) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *ProblemDetails400) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *ProblemDetails400) SetRequestId(v string) {
	o.RequestId = v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *ProblemDetails400) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProblemDetails400) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *ProblemDetails400) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *ProblemDetails400) SetOrigin(v string) {
	o.Origin = &v
}

func (o ProblemDetails400) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProblemDetails400) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["title"] = o.Title
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	toSerialize["requestId"] = o.RequestId
	if !IsNil(o.Origin) {
		toSerialize["origin"] = o.Origin
	}
	return toSerialize, nil
}

func (o *ProblemDetails400) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"requestId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProblemDetails400 := _ProblemDetails400{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProblemDetails400)

	if err != nil {
		return err
	}

	*o = ProblemDetails400(varProblemDetails400)

	return err
}

type NullableProblemDetails400 struct {
	value *ProblemDetails400
	isSet bool
}

func (v NullableProblemDetails400) Get() *ProblemDetails400 {
	return v.value
}

func (v *NullableProblemDetails400) Set(val *ProblemDetails400) {
	v.value = val
	v.isSet = true
}

func (v NullableProblemDetails400) IsSet() bool {
	return v.isSet
}

func (v *NullableProblemDetails400) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProblemDetails400(val *ProblemDetails400) *NullableProblemDetails400 {
	return &NullableProblemDetails400{value: val, isSet: true}
}

func (v NullableProblemDetails400) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProblemDetails400) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


