/*
Заказы Самовывоз

Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [метаданными](/openapi/in-store-pickup#tag/Metadannye-Samovyvoz) заказов модели Самовывоз. 

API version: instorepickup
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package in_store_pickup

import (
	"encoding/json"
)

// checks if the ApiBaseMetaUin type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiBaseMetaUin{}

// ApiBaseMetaUin УИН
type ApiBaseMetaUin struct {
	Value NullableString `json:"value,omitempty"`
}

// NewApiBaseMetaUin instantiates a new ApiBaseMetaUin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiBaseMetaUin() *ApiBaseMetaUin {
	this := ApiBaseMetaUin{}
	return &this
}

// NewApiBaseMetaUinWithDefaults instantiates a new ApiBaseMetaUin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiBaseMetaUinWithDefaults() *ApiBaseMetaUin {
	this := ApiBaseMetaUin{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiBaseMetaUin) GetValue() string {
	if o == nil || IsNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiBaseMetaUin) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *ApiBaseMetaUin) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *ApiBaseMetaUin) SetValue(v string) {
	o.Value.Set(&v)
}
// SetValueNil sets the value for Value to be an explicit nil
func (o *ApiBaseMetaUin) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *ApiBaseMetaUin) UnsetValue() {
	o.Value.Unset()
}

func (o ApiBaseMetaUin) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiBaseMetaUin) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	return toSerialize, nil
}

type NullableApiBaseMetaUin struct {
	value *ApiBaseMetaUin
	isSet bool
}

func (v NullableApiBaseMetaUin) Get() *ApiBaseMetaUin {
	return v.value
}

func (v *NullableApiBaseMetaUin) Set(val *ApiBaseMetaUin) {
	v.value = val
	v.isSet = true
}

func (v NullableApiBaseMetaUin) IsSet() bool {
	return v.isSet
}

func (v *NullableApiBaseMetaUin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiBaseMetaUin(val *ApiBaseMetaUin) *NullableApiBaseMetaUin {
	return &NullableApiBaseMetaUin{value: val, isSet: true}
}

func (v NullableApiBaseMetaUin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiBaseMetaUin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


