/*
Работа с товарами

<div class=\"api-block\">  С помощью методов этого раздела вы можете:   - [создавать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получать [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загружать [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настраивать [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - устанавливать [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца  </div>  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami\">инструкции</a> по <strong>работе с товарами</strong> </div> 

API version: products
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package products

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseCardCreateAdditionalErrorsOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseCardCreateAdditionalErrorsOneOf1{}

// ResponseCardCreateAdditionalErrorsOneOf1 struct for ResponseCardCreateAdditionalErrorsOneOf1
type ResponseCardCreateAdditionalErrorsOneOf1 struct {
	Error string `json:"error"`
}

type _ResponseCardCreateAdditionalErrorsOneOf1 ResponseCardCreateAdditionalErrorsOneOf1

// NewResponseCardCreateAdditionalErrorsOneOf1 instantiates a new ResponseCardCreateAdditionalErrorsOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCardCreateAdditionalErrorsOneOf1(error_ string) *ResponseCardCreateAdditionalErrorsOneOf1 {
	this := ResponseCardCreateAdditionalErrorsOneOf1{}
	this.Error = error_
	return &this
}

// NewResponseCardCreateAdditionalErrorsOneOf1WithDefaults instantiates a new ResponseCardCreateAdditionalErrorsOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCardCreateAdditionalErrorsOneOf1WithDefaults() *ResponseCardCreateAdditionalErrorsOneOf1 {
	this := ResponseCardCreateAdditionalErrorsOneOf1{}
	return &this
}

// GetError returns the Error field value
func (o *ResponseCardCreateAdditionalErrorsOneOf1) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ResponseCardCreateAdditionalErrorsOneOf1) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ResponseCardCreateAdditionalErrorsOneOf1) SetError(v string) {
	o.Error = v
}

func (o ResponseCardCreateAdditionalErrorsOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseCardCreateAdditionalErrorsOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *ResponseCardCreateAdditionalErrorsOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseCardCreateAdditionalErrorsOneOf1 := _ResponseCardCreateAdditionalErrorsOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseCardCreateAdditionalErrorsOneOf1)

	if err != nil {
		return err
	}

	*o = ResponseCardCreateAdditionalErrorsOneOf1(varResponseCardCreateAdditionalErrorsOneOf1)

	return err
}

type NullableResponseCardCreateAdditionalErrorsOneOf1 struct {
	value *ResponseCardCreateAdditionalErrorsOneOf1
	isSet bool
}

func (v NullableResponseCardCreateAdditionalErrorsOneOf1) Get() *ResponseCardCreateAdditionalErrorsOneOf1 {
	return v.value
}

func (v *NullableResponseCardCreateAdditionalErrorsOneOf1) Set(val *ResponseCardCreateAdditionalErrorsOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCardCreateAdditionalErrorsOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCardCreateAdditionalErrorsOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCardCreateAdditionalErrorsOneOf1(val *ResponseCardCreateAdditionalErrorsOneOf1) *NullableResponseCardCreateAdditionalErrorsOneOf1 {
	return &NullableResponseCardCreateAdditionalErrorsOneOf1{value: val, isSet: true}
}

func (v NullableResponseCardCreateAdditionalErrorsOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCardCreateAdditionalErrorsOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


