/*
Работа с товарами

С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 

API version: products
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package products

import (
	"encoding/json"
)

// checks if the ApiV3StocksWarehouseIdPutRequestStocksInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV3StocksWarehouseIdPutRequestStocksInner{}

// ApiV3StocksWarehouseIdPutRequestStocksInner struct for ApiV3StocksWarehouseIdPutRequestStocksInner
type ApiV3StocksWarehouseIdPutRequestStocksInner struct {
	// ID размера товара
	ChrtId *int32 `json:"chrtId,omitempty"`
	// Баркод. Параметр будет отключен [9 февраля](https://dev.wildberries.ru/release-notes?id=386)
	// Deprecated
	Sku *string `json:"sku,omitempty"`
	// Остаток
	Amount *int32 `json:"amount,omitempty"`
}

// NewApiV3StocksWarehouseIdPutRequestStocksInner instantiates a new ApiV3StocksWarehouseIdPutRequestStocksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV3StocksWarehouseIdPutRequestStocksInner() *ApiV3StocksWarehouseIdPutRequestStocksInner {
	this := ApiV3StocksWarehouseIdPutRequestStocksInner{}
	return &this
}

// NewApiV3StocksWarehouseIdPutRequestStocksInnerWithDefaults instantiates a new ApiV3StocksWarehouseIdPutRequestStocksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV3StocksWarehouseIdPutRequestStocksInnerWithDefaults() *ApiV3StocksWarehouseIdPutRequestStocksInner {
	this := ApiV3StocksWarehouseIdPutRequestStocksInner{}
	return &this
}

// GetChrtId returns the ChrtId field value if set, zero value otherwise.
func (o *ApiV3StocksWarehouseIdPutRequestStocksInner) GetChrtId() int32 {
	if o == nil || IsNil(o.ChrtId) {
		var ret int32
		return ret
	}
	return *o.ChrtId
}

// GetChrtIdOk returns a tuple with the ChrtId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV3StocksWarehouseIdPutRequestStocksInner) GetChrtIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ChrtId) {
		return nil, false
	}
	return o.ChrtId, true
}

// HasChrtId returns a boolean if a field has been set.
func (o *ApiV3StocksWarehouseIdPutRequestStocksInner) HasChrtId() bool {
	if o != nil && !IsNil(o.ChrtId) {
		return true
	}

	return false
}

// SetChrtId gets a reference to the given int32 and assigns it to the ChrtId field.
func (o *ApiV3StocksWarehouseIdPutRequestStocksInner) SetChrtId(v int32) {
	o.ChrtId = &v
}

// GetSku returns the Sku field value if set, zero value otherwise.
// Deprecated
func (o *ApiV3StocksWarehouseIdPutRequestStocksInner) GetSku() string {
	if o == nil || IsNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *ApiV3StocksWarehouseIdPutRequestStocksInner) GetSkuOk() (*string, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *ApiV3StocksWarehouseIdPutRequestStocksInner) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
// Deprecated
func (o *ApiV3StocksWarehouseIdPutRequestStocksInner) SetSku(v string) {
	o.Sku = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ApiV3StocksWarehouseIdPutRequestStocksInner) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV3StocksWarehouseIdPutRequestStocksInner) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ApiV3StocksWarehouseIdPutRequestStocksInner) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *ApiV3StocksWarehouseIdPutRequestStocksInner) SetAmount(v int32) {
	o.Amount = &v
}

func (o ApiV3StocksWarehouseIdPutRequestStocksInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV3StocksWarehouseIdPutRequestStocksInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChrtId) {
		toSerialize["chrtId"] = o.ChrtId
	}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	return toSerialize, nil
}

type NullableApiV3StocksWarehouseIdPutRequestStocksInner struct {
	value *ApiV3StocksWarehouseIdPutRequestStocksInner
	isSet bool
}

func (v NullableApiV3StocksWarehouseIdPutRequestStocksInner) Get() *ApiV3StocksWarehouseIdPutRequestStocksInner {
	return v.value
}

func (v *NullableApiV3StocksWarehouseIdPutRequestStocksInner) Set(val *ApiV3StocksWarehouseIdPutRequestStocksInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV3StocksWarehouseIdPutRequestStocksInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV3StocksWarehouseIdPutRequestStocksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV3StocksWarehouseIdPutRequestStocksInner(val *ApiV3StocksWarehouseIdPutRequestStocksInner) *NullableApiV3StocksWarehouseIdPutRequestStocksInner {
	return &NullableApiV3StocksWarehouseIdPutRequestStocksInner{value: val, isSet: true}
}

func (v NullableApiV3StocksWarehouseIdPutRequestStocksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV3StocksWarehouseIdPutRequestStocksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


