/* tslint:disable */
/* eslint-disable */
/**
 * Маркетинг и продвижение
 * <div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 
 *
 * The version of the OpenAPI document: promotion
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdvV0BidsPatch400ResponseErrorsInner } from './AdvV0BidsPatch400ResponseErrorsInner';
import {
    AdvV0BidsPatch400ResponseErrorsInnerFromJSON,
    AdvV0BidsPatch400ResponseErrorsInnerFromJSONTyped,
    AdvV0BidsPatch400ResponseErrorsInnerToJSON,
    AdvV0BidsPatch400ResponseErrorsInnerToJSONTyped,
} from './AdvV0BidsPatch400ResponseErrorsInner';

/**
 * 
 * @export
 * @interface AdvV0BidsPatch400Response
 */
export interface AdvV0BidsPatch400Response {
    /**
     * Детали ошибки 
     * @type {string}
     * @memberof AdvV0BidsPatch400Response
     */
    detail?: string;
    /**
     * ID внутреннего сервиса WB 
     * @type {string}
     * @memberof AdvV0BidsPatch400Response
     */
    origin?: string;
    /**
     * Уникальный ID запроса
     * @type {string}
     * @memberof AdvV0BidsPatch400Response
     */
    requestId?: string;
    /**
     * HTTP статус-код
     * @type {number}
     * @memberof AdvV0BidsPatch400Response
     */
    status?: number;
    /**
     * Заголовок ошибки
     * @type {string}
     * @memberof AdvV0BidsPatch400Response
     */
    title?: string;
    /**
     * Детализация ошибки
     * @type {Array<AdvV0BidsPatch400ResponseErrorsInner>}
     * @memberof AdvV0BidsPatch400Response
     */
    errors?: Array<AdvV0BidsPatch400ResponseErrorsInner>;
    /**
     * Тип ошибки
     * @type {string}
     * @memberof AdvV0BidsPatch400Response
     */
    type?: string;
}

/**
 * Check if a given object implements the AdvV0BidsPatch400Response interface.
 */
export function instanceOfAdvV0BidsPatch400Response(value: object): value is AdvV0BidsPatch400Response {
    return true;
}

export function AdvV0BidsPatch400ResponseFromJSON(json: any): AdvV0BidsPatch400Response {
    return AdvV0BidsPatch400ResponseFromJSONTyped(json, false);
}

export function AdvV0BidsPatch400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdvV0BidsPatch400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'] == null ? undefined : json['detail'],
        'origin': json['origin'] == null ? undefined : json['origin'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'title': json['title'] == null ? undefined : json['title'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(AdvV0BidsPatch400ResponseErrorsInnerFromJSON)),
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function AdvV0BidsPatch400ResponseToJSON(json: any): AdvV0BidsPatch400Response {
    return AdvV0BidsPatch400ResponseToJSONTyped(json, false);
}

export function AdvV0BidsPatch400ResponseToJSONTyped(value?: AdvV0BidsPatch400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
        'origin': value['origin'],
        'request_id': value['requestId'],
        'status': value['status'],
        'title': value['title'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(AdvV0BidsPatch400ResponseErrorsInnerToJSON)),
        'type': value['type'],
    };
}

