/* tslint:disable */
/* eslint-disable */
/**
 * Маркетинг и продвижение
 * <div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 
 *
 * The version of the OpenAPI document: promotion
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseInfoAdvertType8AutoParamsSetsInner
 */
export interface ResponseInfoAdvertType8AutoParamsSetsInner {
    /**
     * ID set
     * @type {number}
     * @memberof ResponseInfoAdvertType8AutoParamsSetsInner
     */
    id?: number;
    /**
     * Название set
     * @type {string}
     * @memberof ResponseInfoAdvertType8AutoParamsSetsInner
     */
    name?: string;
}

/**
 * Check if a given object implements the ResponseInfoAdvertType8AutoParamsSetsInner interface.
 */
export function instanceOfResponseInfoAdvertType8AutoParamsSetsInner(value: object): value is ResponseInfoAdvertType8AutoParamsSetsInner {
    return true;
}

export function ResponseInfoAdvertType8AutoParamsSetsInnerFromJSON(json: any): ResponseInfoAdvertType8AutoParamsSetsInner {
    return ResponseInfoAdvertType8AutoParamsSetsInnerFromJSONTyped(json, false);
}

export function ResponseInfoAdvertType8AutoParamsSetsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseInfoAdvertType8AutoParamsSetsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ResponseInfoAdvertType8AutoParamsSetsInnerToJSON(json: any): ResponseInfoAdvertType8AutoParamsSetsInner {
    return ResponseInfoAdvertType8AutoParamsSetsInnerToJSONTyped(json, false);
}

export function ResponseInfoAdvertType8AutoParamsSetsInnerToJSONTyped(value?: ResponseInfoAdvertType8AutoParamsSetsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

