/* tslint:disable */
/* eslint-disable */
/**
 * Маркетинг и продвижение
 * <div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 
 *
 * The version of the OpenAPI document: promotion
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0AdvertMultiBidItem } from './V0AdvertMultiBidItem';
import {
    V0AdvertMultiBidItemFromJSON,
    V0AdvertMultiBidItemFromJSONTyped,
    V0AdvertMultiBidItemToJSON,
    V0AdvertMultiBidItemToJSONTyped,
} from './V0AdvertMultiBidItem';

/**
 * 
 * @export
 * @interface V0AdvertMultibid
 */
export interface V0AdvertMultibid {
    /**
     * ID кампании
     * @type {number}
     * @memberof V0AdvertMultibid
     */
    advertId: number;
    /**
     * Артикулы WB и ставки для них
     * @type {Array<V0AdvertMultiBidItem>}
     * @memberof V0AdvertMultibid
     */
    nmBids: Array<V0AdvertMultiBidItem>;
}

/**
 * Check if a given object implements the V0AdvertMultibid interface.
 */
export function instanceOfV0AdvertMultibid(value: object): value is V0AdvertMultibid {
    if (!('advertId' in value) || value['advertId'] === undefined) return false;
    if (!('nmBids' in value) || value['nmBids'] === undefined) return false;
    return true;
}

export function V0AdvertMultibidFromJSON(json: any): V0AdvertMultibid {
    return V0AdvertMultibidFromJSONTyped(json, false);
}

export function V0AdvertMultibidFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0AdvertMultibid {
    if (json == null) {
        return json;
    }
    return {
        
        'advertId': json['advert_id'],
        'nmBids': ((json['nm_bids'] as Array<any>).map(V0AdvertMultiBidItemFromJSON)),
    };
}

export function V0AdvertMultibidToJSON(json: any): V0AdvertMultibid {
    return V0AdvertMultibidToJSONTyped(json, false);
}

export function V0AdvertMultibidToJSONTyped(value?: V0AdvertMultibid | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advert_id': value['advertId'],
        'nm_bids': ((value['nmBids'] as Array<any>).map(V0AdvertMultiBidItemToJSON)),
    };
}

