/* tslint:disable */
/* eslint-disable */
/**
 * Маркетинг и продвижение
 * <div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 
 *
 * The version of the OpenAPI document: promotion
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0GetConfigCategoriesResponse
 */
export interface V0GetConfigCategoriesResponse {
    /**
     * ID категории товара
     * @type {number}
     * @memberof V0GetConfigCategoriesResponse
     */
    id: number;
    /**
     * Название категории товара
     * @type {string}
     * @memberof V0GetConfigCategoriesResponse
     */
    name: string;
    /**
     * Минимально допустимая ставка
     * @type {number}
     * @memberof V0GetConfigCategoriesResponse
     */
    cpmMin: number;
}

/**
 * Check if a given object implements the V0GetConfigCategoriesResponse interface.
 */
export function instanceOfV0GetConfigCategoriesResponse(value: object): value is V0GetConfigCategoriesResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('cpmMin' in value) || value['cpmMin'] === undefined) return false;
    return true;
}

export function V0GetConfigCategoriesResponseFromJSON(json: any): V0GetConfigCategoriesResponse {
    return V0GetConfigCategoriesResponseFromJSONTyped(json, false);
}

export function V0GetConfigCategoriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0GetConfigCategoriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'cpmMin': json['cpm_min'],
    };
}

export function V0GetConfigCategoriesResponseToJSON(json: any): V0GetConfigCategoriesResponse {
    return V0GetConfigCategoriesResponseToJSONTyped(json, false);
}

export function V0GetConfigCategoriesResponseToJSONTyped(value?: V0GetConfigCategoriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'cpm_min': value['cpmMin'],
    };
}

