/*
Маркетинг и продвижение

<div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
	"time"
)

// checks if the BoosterStatsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BoosterStatsInner{}

// BoosterStatsInner struct for BoosterStatsInner
type BoosterStatsInner struct {
	// Дата, за которую предоставлены данные
	Date *time.Time `json:"date,omitempty"`
	// Артикул WB
	Nm *int32 `json:"nm,omitempty"`
	// Средняя позиция товара на страницах поисковой выдачи и каталога
	AvgPosition *int32 `json:"avg_position,omitempty"`
}

// NewBoosterStatsInner instantiates a new BoosterStatsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBoosterStatsInner() *BoosterStatsInner {
	this := BoosterStatsInner{}
	return &this
}

// NewBoosterStatsInnerWithDefaults instantiates a new BoosterStatsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBoosterStatsInnerWithDefaults() *BoosterStatsInner {
	this := BoosterStatsInner{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *BoosterStatsInner) GetDate() time.Time {
	if o == nil || IsNil(o.Date) {
		var ret time.Time
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BoosterStatsInner) GetDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *BoosterStatsInner) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given time.Time and assigns it to the Date field.
func (o *BoosterStatsInner) SetDate(v time.Time) {
	o.Date = &v
}

// GetNm returns the Nm field value if set, zero value otherwise.
func (o *BoosterStatsInner) GetNm() int32 {
	if o == nil || IsNil(o.Nm) {
		var ret int32
		return ret
	}
	return *o.Nm
}

// GetNmOk returns a tuple with the Nm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BoosterStatsInner) GetNmOk() (*int32, bool) {
	if o == nil || IsNil(o.Nm) {
		return nil, false
	}
	return o.Nm, true
}

// HasNm returns a boolean if a field has been set.
func (o *BoosterStatsInner) HasNm() bool {
	if o != nil && !IsNil(o.Nm) {
		return true
	}

	return false
}

// SetNm gets a reference to the given int32 and assigns it to the Nm field.
func (o *BoosterStatsInner) SetNm(v int32) {
	o.Nm = &v
}

// GetAvgPosition returns the AvgPosition field value if set, zero value otherwise.
func (o *BoosterStatsInner) GetAvgPosition() int32 {
	if o == nil || IsNil(o.AvgPosition) {
		var ret int32
		return ret
	}
	return *o.AvgPosition
}

// GetAvgPositionOk returns a tuple with the AvgPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BoosterStatsInner) GetAvgPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.AvgPosition) {
		return nil, false
	}
	return o.AvgPosition, true
}

// HasAvgPosition returns a boolean if a field has been set.
func (o *BoosterStatsInner) HasAvgPosition() bool {
	if o != nil && !IsNil(o.AvgPosition) {
		return true
	}

	return false
}

// SetAvgPosition gets a reference to the given int32 and assigns it to the AvgPosition field.
func (o *BoosterStatsInner) SetAvgPosition(v int32) {
	o.AvgPosition = &v
}

func (o BoosterStatsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BoosterStatsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Nm) {
		toSerialize["nm"] = o.Nm
	}
	if !IsNil(o.AvgPosition) {
		toSerialize["avg_position"] = o.AvgPosition
	}
	return toSerialize, nil
}

type NullableBoosterStatsInner struct {
	value *BoosterStatsInner
	isSet bool
}

func (v NullableBoosterStatsInner) Get() *BoosterStatsInner {
	return v.value
}

func (v *NullableBoosterStatsInner) Set(val *BoosterStatsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBoosterStatsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBoosterStatsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBoosterStatsInner(val *BoosterStatsInner) *NullableBoosterStatsInner {
	return &NullableBoosterStatsInner{value: val, isSet: true}
}

func (v NullableBoosterStatsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBoosterStatsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


