/*
Маркетинг и продвижение

<div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
	"time"
)

// checks if the ResponseInfoAdvertType8 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseInfoAdvertType8{}

// ResponseInfoAdvertType8 struct for ResponseInfoAdvertType8
type ResponseInfoAdvertType8 struct {
	// Дата завершения кампании
	EndTime *time.Time `json:"endTime,omitempty"`
	// Дата создания кампании
	CreateTime *time.Time `json:"createTime,omitempty"`
	// Дата последнего изменения кампании
	ChangeTime *time.Time `json:"changeTime,omitempty"`
	// Дата последнего запуска кампании
	StartTime *time.Time `json:"startTime,omitempty"`
	AutoParams *ResponseInfoAdvertType8AutoParams `json:"autoParams,omitempty"`
	// Название кампании
	Name *string `json:"name,omitempty"`
	// Не используется
	DailyBudget *int32 `json:"dailyBudget,omitempty"`
	// ID кампании
	AdvertId *int32 `json:"advertId,omitempty"`
	// Статус кампании: - `-1` — удалена, процесс удаления будет завершён в течение 10 минут - `4` — готова к запуску - `7` — завершена - `8` — отменена - `9` — активна - `11` — на паузе 
	Status *int32 `json:"status,omitempty"`
	// Тип кампании:   - `8` — единая ставка 
	Type *int32 `json:"type,omitempty"`
	// Модель оплаты: - `cpm` — за показы 
	PaymentType *string `json:"paymentType,omitempty"`
}

// NewResponseInfoAdvertType8 instantiates a new ResponseInfoAdvertType8 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseInfoAdvertType8() *ResponseInfoAdvertType8 {
	this := ResponseInfoAdvertType8{}
	return &this
}

// NewResponseInfoAdvertType8WithDefaults instantiates a new ResponseInfoAdvertType8 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseInfoAdvertType8WithDefaults() *ResponseInfoAdvertType8 {
	this := ResponseInfoAdvertType8{}
	return &this
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *ResponseInfoAdvertType8) GetEndTime() time.Time {
	if o == nil || IsNil(o.EndTime) {
		var ret time.Time
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfoAdvertType8) GetEndTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndTime) {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *ResponseInfoAdvertType8) HasEndTime() bool {
	if o != nil && !IsNil(o.EndTime) {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given time.Time and assigns it to the EndTime field.
func (o *ResponseInfoAdvertType8) SetEndTime(v time.Time) {
	o.EndTime = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *ResponseInfoAdvertType8) GetCreateTime() time.Time {
	if o == nil || IsNil(o.CreateTime) {
		var ret time.Time
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfoAdvertType8) GetCreateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreateTime) {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *ResponseInfoAdvertType8) HasCreateTime() bool {
	if o != nil && !IsNil(o.CreateTime) {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given time.Time and assigns it to the CreateTime field.
func (o *ResponseInfoAdvertType8) SetCreateTime(v time.Time) {
	o.CreateTime = &v
}

// GetChangeTime returns the ChangeTime field value if set, zero value otherwise.
func (o *ResponseInfoAdvertType8) GetChangeTime() time.Time {
	if o == nil || IsNil(o.ChangeTime) {
		var ret time.Time
		return ret
	}
	return *o.ChangeTime
}

// GetChangeTimeOk returns a tuple with the ChangeTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfoAdvertType8) GetChangeTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ChangeTime) {
		return nil, false
	}
	return o.ChangeTime, true
}

// HasChangeTime returns a boolean if a field has been set.
func (o *ResponseInfoAdvertType8) HasChangeTime() bool {
	if o != nil && !IsNil(o.ChangeTime) {
		return true
	}

	return false
}

// SetChangeTime gets a reference to the given time.Time and assigns it to the ChangeTime field.
func (o *ResponseInfoAdvertType8) SetChangeTime(v time.Time) {
	o.ChangeTime = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *ResponseInfoAdvertType8) GetStartTime() time.Time {
	if o == nil || IsNil(o.StartTime) {
		var ret time.Time
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfoAdvertType8) GetStartTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *ResponseInfoAdvertType8) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given time.Time and assigns it to the StartTime field.
func (o *ResponseInfoAdvertType8) SetStartTime(v time.Time) {
	o.StartTime = &v
}

// GetAutoParams returns the AutoParams field value if set, zero value otherwise.
func (o *ResponseInfoAdvertType8) GetAutoParams() ResponseInfoAdvertType8AutoParams {
	if o == nil || IsNil(o.AutoParams) {
		var ret ResponseInfoAdvertType8AutoParams
		return ret
	}
	return *o.AutoParams
}

// GetAutoParamsOk returns a tuple with the AutoParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfoAdvertType8) GetAutoParamsOk() (*ResponseInfoAdvertType8AutoParams, bool) {
	if o == nil || IsNil(o.AutoParams) {
		return nil, false
	}
	return o.AutoParams, true
}

// HasAutoParams returns a boolean if a field has been set.
func (o *ResponseInfoAdvertType8) HasAutoParams() bool {
	if o != nil && !IsNil(o.AutoParams) {
		return true
	}

	return false
}

// SetAutoParams gets a reference to the given ResponseInfoAdvertType8AutoParams and assigns it to the AutoParams field.
func (o *ResponseInfoAdvertType8) SetAutoParams(v ResponseInfoAdvertType8AutoParams) {
	o.AutoParams = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ResponseInfoAdvertType8) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfoAdvertType8) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ResponseInfoAdvertType8) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ResponseInfoAdvertType8) SetName(v string) {
	o.Name = &v
}

// GetDailyBudget returns the DailyBudget field value if set, zero value otherwise.
func (o *ResponseInfoAdvertType8) GetDailyBudget() int32 {
	if o == nil || IsNil(o.DailyBudget) {
		var ret int32
		return ret
	}
	return *o.DailyBudget
}

// GetDailyBudgetOk returns a tuple with the DailyBudget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfoAdvertType8) GetDailyBudgetOk() (*int32, bool) {
	if o == nil || IsNil(o.DailyBudget) {
		return nil, false
	}
	return o.DailyBudget, true
}

// HasDailyBudget returns a boolean if a field has been set.
func (o *ResponseInfoAdvertType8) HasDailyBudget() bool {
	if o != nil && !IsNil(o.DailyBudget) {
		return true
	}

	return false
}

// SetDailyBudget gets a reference to the given int32 and assigns it to the DailyBudget field.
func (o *ResponseInfoAdvertType8) SetDailyBudget(v int32) {
	o.DailyBudget = &v
}

// GetAdvertId returns the AdvertId field value if set, zero value otherwise.
func (o *ResponseInfoAdvertType8) GetAdvertId() int32 {
	if o == nil || IsNil(o.AdvertId) {
		var ret int32
		return ret
	}
	return *o.AdvertId
}

// GetAdvertIdOk returns a tuple with the AdvertId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfoAdvertType8) GetAdvertIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AdvertId) {
		return nil, false
	}
	return o.AdvertId, true
}

// HasAdvertId returns a boolean if a field has been set.
func (o *ResponseInfoAdvertType8) HasAdvertId() bool {
	if o != nil && !IsNil(o.AdvertId) {
		return true
	}

	return false
}

// SetAdvertId gets a reference to the given int32 and assigns it to the AdvertId field.
func (o *ResponseInfoAdvertType8) SetAdvertId(v int32) {
	o.AdvertId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponseInfoAdvertType8) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfoAdvertType8) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponseInfoAdvertType8) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *ResponseInfoAdvertType8) SetStatus(v int32) {
	o.Status = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ResponseInfoAdvertType8) GetType() int32 {
	if o == nil || IsNil(o.Type) {
		var ret int32
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfoAdvertType8) GetTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ResponseInfoAdvertType8) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given int32 and assigns it to the Type field.
func (o *ResponseInfoAdvertType8) SetType(v int32) {
	o.Type = &v
}

// GetPaymentType returns the PaymentType field value if set, zero value otherwise.
func (o *ResponseInfoAdvertType8) GetPaymentType() string {
	if o == nil || IsNil(o.PaymentType) {
		var ret string
		return ret
	}
	return *o.PaymentType
}

// GetPaymentTypeOk returns a tuple with the PaymentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfoAdvertType8) GetPaymentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentType) {
		return nil, false
	}
	return o.PaymentType, true
}

// HasPaymentType returns a boolean if a field has been set.
func (o *ResponseInfoAdvertType8) HasPaymentType() bool {
	if o != nil && !IsNil(o.PaymentType) {
		return true
	}

	return false
}

// SetPaymentType gets a reference to the given string and assigns it to the PaymentType field.
func (o *ResponseInfoAdvertType8) SetPaymentType(v string) {
	o.PaymentType = &v
}

func (o ResponseInfoAdvertType8) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseInfoAdvertType8) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndTime) {
		toSerialize["endTime"] = o.EndTime
	}
	if !IsNil(o.CreateTime) {
		toSerialize["createTime"] = o.CreateTime
	}
	if !IsNil(o.ChangeTime) {
		toSerialize["changeTime"] = o.ChangeTime
	}
	if !IsNil(o.StartTime) {
		toSerialize["startTime"] = o.StartTime
	}
	if !IsNil(o.AutoParams) {
		toSerialize["autoParams"] = o.AutoParams
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.DailyBudget) {
		toSerialize["dailyBudget"] = o.DailyBudget
	}
	if !IsNil(o.AdvertId) {
		toSerialize["advertId"] = o.AdvertId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.PaymentType) {
		toSerialize["paymentType"] = o.PaymentType
	}
	return toSerialize, nil
}

type NullableResponseInfoAdvertType8 struct {
	value *ResponseInfoAdvertType8
	isSet bool
}

func (v NullableResponseInfoAdvertType8) Get() *ResponseInfoAdvertType8 {
	return v.value
}

func (v *NullableResponseInfoAdvertType8) Set(val *ResponseInfoAdvertType8) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseInfoAdvertType8) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseInfoAdvertType8) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseInfoAdvertType8(val *ResponseInfoAdvertType8) *NullableResponseInfoAdvertType8 {
	return &NullableResponseInfoAdvertType8{value: val, isSet: true}
}

func (v NullableResponseInfoAdvertType8) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseInfoAdvertType8) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


