/*
Маркетинг и продвижение

<div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V0KeywordsStatistic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0KeywordsStatistic{}

// V0KeywordsStatistic struct for V0KeywordsStatistic
type V0KeywordsStatistic struct {
	// Количество кликов
	Clicks int32 `json:"clicks"`
	// CTR (Click-Through Rate) — показатель кликабельности
	Ctr float32 `json:"ctr"`
	// Ключевая фраза
	Keyword string `json:"keyword"`
	// Сумма затрат по ключевой фразе
	Sum float32 `json:"sum"`
	// Количество показов
	Views int32 `json:"views"`
}

type _V0KeywordsStatistic V0KeywordsStatistic

// NewV0KeywordsStatistic instantiates a new V0KeywordsStatistic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0KeywordsStatistic(clicks int32, ctr float32, keyword string, sum float32, views int32) *V0KeywordsStatistic {
	this := V0KeywordsStatistic{}
	this.Clicks = clicks
	this.Ctr = ctr
	this.Keyword = keyword
	this.Sum = sum
	this.Views = views
	return &this
}

// NewV0KeywordsStatisticWithDefaults instantiates a new V0KeywordsStatistic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0KeywordsStatisticWithDefaults() *V0KeywordsStatistic {
	this := V0KeywordsStatistic{}
	return &this
}

// GetClicks returns the Clicks field value
func (o *V0KeywordsStatistic) GetClicks() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Clicks
}

// GetClicksOk returns a tuple with the Clicks field value
// and a boolean to check if the value has been set.
func (o *V0KeywordsStatistic) GetClicksOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Clicks, true
}

// SetClicks sets field value
func (o *V0KeywordsStatistic) SetClicks(v int32) {
	o.Clicks = v
}

// GetCtr returns the Ctr field value
func (o *V0KeywordsStatistic) GetCtr() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Ctr
}

// GetCtrOk returns a tuple with the Ctr field value
// and a boolean to check if the value has been set.
func (o *V0KeywordsStatistic) GetCtrOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ctr, true
}

// SetCtr sets field value
func (o *V0KeywordsStatistic) SetCtr(v float32) {
	o.Ctr = v
}

// GetKeyword returns the Keyword field value
func (o *V0KeywordsStatistic) GetKeyword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Keyword
}

// GetKeywordOk returns a tuple with the Keyword field value
// and a boolean to check if the value has been set.
func (o *V0KeywordsStatistic) GetKeywordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Keyword, true
}

// SetKeyword sets field value
func (o *V0KeywordsStatistic) SetKeyword(v string) {
	o.Keyword = v
}

// GetSum returns the Sum field value
func (o *V0KeywordsStatistic) GetSum() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Sum
}

// GetSumOk returns a tuple with the Sum field value
// and a boolean to check if the value has been set.
func (o *V0KeywordsStatistic) GetSumOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sum, true
}

// SetSum sets field value
func (o *V0KeywordsStatistic) SetSum(v float32) {
	o.Sum = v
}

// GetViews returns the Views field value
func (o *V0KeywordsStatistic) GetViews() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Views
}

// GetViewsOk returns a tuple with the Views field value
// and a boolean to check if the value has been set.
func (o *V0KeywordsStatistic) GetViewsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Views, true
}

// SetViews sets field value
func (o *V0KeywordsStatistic) SetViews(v int32) {
	o.Views = v
}

func (o V0KeywordsStatistic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0KeywordsStatistic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clicks"] = o.Clicks
	toSerialize["ctr"] = o.Ctr
	toSerialize["keyword"] = o.Keyword
	toSerialize["sum"] = o.Sum
	toSerialize["views"] = o.Views
	return toSerialize, nil
}

func (o *V0KeywordsStatistic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"clicks",
		"ctr",
		"keyword",
		"sum",
		"views",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV0KeywordsStatistic := _V0KeywordsStatistic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV0KeywordsStatistic)

	if err != nil {
		return err
	}

	*o = V0KeywordsStatistic(varV0KeywordsStatistic)

	return err
}

type NullableV0KeywordsStatistic struct {
	value *V0KeywordsStatistic
	isSet bool
}

func (v NullableV0KeywordsStatistic) Get() *V0KeywordsStatistic {
	return v.value
}

func (v *NullableV0KeywordsStatistic) Set(val *V0KeywordsStatistic) {
	v.value = val
	v.isSet = true
}

func (v NullableV0KeywordsStatistic) IsSet() bool {
	return v.isSet
}

func (v *NullableV0KeywordsStatistic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0KeywordsStatistic(val *V0KeywordsStatistic) *NullableV0KeywordsStatistic {
	return &NullableV0KeywordsStatistic{value: val, isSet: true}
}

func (v NullableV0KeywordsStatistic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0KeywordsStatistic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


