/*
Маркетинг и продвижение

<div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
	"time"
)

// checks if the DaysInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DaysInner{}

// DaysInner struct for DaysInner
type DaysInner struct {
	// Дата, за которую представлены данные
	Date *time.Time `json:"date,omitempty"`
	// Количество просмотров
	Views *int32 `json:"views,omitempty"`
	// Количество кликов
	Clicks *int32 `json:"clicks,omitempty"`
	// Показатель кликабельности, отношение числа кликов к количеству показов, % 
	Ctr *float32 `json:"ctr,omitempty"`
	// Средняя стоимость клика, ₽
	Cpc *float32 `json:"cpc,omitempty"`
	// Затраты, ₽
	Sum *float32 `json:"sum,omitempty"`
	// Количество добавлений товаров в корзину
	Atbs *int32 `json:"atbs,omitempty"`
	// Количество заказов
	Orders *int32 `json:"orders,omitempty"`
	// CR(conversion rate) — отношение количества заказов к общему количеству посещений кампании 
	Cr *float32 `json:"cr,omitempty"`
	// Количество заказанных товаров, шт.
	Shks *int32 `json:"shks,omitempty"`
	// Заказов на сумму, ₽
	SumPrice *float32 `json:"sum_price,omitempty"`
	// Блок информации о платформе
	Apps []DaysInnerAppsInner `json:"apps,omitempty"`
}

// NewDaysInner instantiates a new DaysInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDaysInner() *DaysInner {
	this := DaysInner{}
	return &this
}

// NewDaysInnerWithDefaults instantiates a new DaysInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDaysInnerWithDefaults() *DaysInner {
	this := DaysInner{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *DaysInner) GetDate() time.Time {
	if o == nil || IsNil(o.Date) {
		var ret time.Time
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaysInner) GetDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *DaysInner) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given time.Time and assigns it to the Date field.
func (o *DaysInner) SetDate(v time.Time) {
	o.Date = &v
}

// GetViews returns the Views field value if set, zero value otherwise.
func (o *DaysInner) GetViews() int32 {
	if o == nil || IsNil(o.Views) {
		var ret int32
		return ret
	}
	return *o.Views
}

// GetViewsOk returns a tuple with the Views field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaysInner) GetViewsOk() (*int32, bool) {
	if o == nil || IsNil(o.Views) {
		return nil, false
	}
	return o.Views, true
}

// HasViews returns a boolean if a field has been set.
func (o *DaysInner) HasViews() bool {
	if o != nil && !IsNil(o.Views) {
		return true
	}

	return false
}

// SetViews gets a reference to the given int32 and assigns it to the Views field.
func (o *DaysInner) SetViews(v int32) {
	o.Views = &v
}

// GetClicks returns the Clicks field value if set, zero value otherwise.
func (o *DaysInner) GetClicks() int32 {
	if o == nil || IsNil(o.Clicks) {
		var ret int32
		return ret
	}
	return *o.Clicks
}

// GetClicksOk returns a tuple with the Clicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaysInner) GetClicksOk() (*int32, bool) {
	if o == nil || IsNil(o.Clicks) {
		return nil, false
	}
	return o.Clicks, true
}

// HasClicks returns a boolean if a field has been set.
func (o *DaysInner) HasClicks() bool {
	if o != nil && !IsNil(o.Clicks) {
		return true
	}

	return false
}

// SetClicks gets a reference to the given int32 and assigns it to the Clicks field.
func (o *DaysInner) SetClicks(v int32) {
	o.Clicks = &v
}

// GetCtr returns the Ctr field value if set, zero value otherwise.
func (o *DaysInner) GetCtr() float32 {
	if o == nil || IsNil(o.Ctr) {
		var ret float32
		return ret
	}
	return *o.Ctr
}

// GetCtrOk returns a tuple with the Ctr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaysInner) GetCtrOk() (*float32, bool) {
	if o == nil || IsNil(o.Ctr) {
		return nil, false
	}
	return o.Ctr, true
}

// HasCtr returns a boolean if a field has been set.
func (o *DaysInner) HasCtr() bool {
	if o != nil && !IsNil(o.Ctr) {
		return true
	}

	return false
}

// SetCtr gets a reference to the given float32 and assigns it to the Ctr field.
func (o *DaysInner) SetCtr(v float32) {
	o.Ctr = &v
}

// GetCpc returns the Cpc field value if set, zero value otherwise.
func (o *DaysInner) GetCpc() float32 {
	if o == nil || IsNil(o.Cpc) {
		var ret float32
		return ret
	}
	return *o.Cpc
}

// GetCpcOk returns a tuple with the Cpc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaysInner) GetCpcOk() (*float32, bool) {
	if o == nil || IsNil(o.Cpc) {
		return nil, false
	}
	return o.Cpc, true
}

// HasCpc returns a boolean if a field has been set.
func (o *DaysInner) HasCpc() bool {
	if o != nil && !IsNil(o.Cpc) {
		return true
	}

	return false
}

// SetCpc gets a reference to the given float32 and assigns it to the Cpc field.
func (o *DaysInner) SetCpc(v float32) {
	o.Cpc = &v
}

// GetSum returns the Sum field value if set, zero value otherwise.
func (o *DaysInner) GetSum() float32 {
	if o == nil || IsNil(o.Sum) {
		var ret float32
		return ret
	}
	return *o.Sum
}

// GetSumOk returns a tuple with the Sum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaysInner) GetSumOk() (*float32, bool) {
	if o == nil || IsNil(o.Sum) {
		return nil, false
	}
	return o.Sum, true
}

// HasSum returns a boolean if a field has been set.
func (o *DaysInner) HasSum() bool {
	if o != nil && !IsNil(o.Sum) {
		return true
	}

	return false
}

// SetSum gets a reference to the given float32 and assigns it to the Sum field.
func (o *DaysInner) SetSum(v float32) {
	o.Sum = &v
}

// GetAtbs returns the Atbs field value if set, zero value otherwise.
func (o *DaysInner) GetAtbs() int32 {
	if o == nil || IsNil(o.Atbs) {
		var ret int32
		return ret
	}
	return *o.Atbs
}

// GetAtbsOk returns a tuple with the Atbs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaysInner) GetAtbsOk() (*int32, bool) {
	if o == nil || IsNil(o.Atbs) {
		return nil, false
	}
	return o.Atbs, true
}

// HasAtbs returns a boolean if a field has been set.
func (o *DaysInner) HasAtbs() bool {
	if o != nil && !IsNil(o.Atbs) {
		return true
	}

	return false
}

// SetAtbs gets a reference to the given int32 and assigns it to the Atbs field.
func (o *DaysInner) SetAtbs(v int32) {
	o.Atbs = &v
}

// GetOrders returns the Orders field value if set, zero value otherwise.
func (o *DaysInner) GetOrders() int32 {
	if o == nil || IsNil(o.Orders) {
		var ret int32
		return ret
	}
	return *o.Orders
}

// GetOrdersOk returns a tuple with the Orders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaysInner) GetOrdersOk() (*int32, bool) {
	if o == nil || IsNil(o.Orders) {
		return nil, false
	}
	return o.Orders, true
}

// HasOrders returns a boolean if a field has been set.
func (o *DaysInner) HasOrders() bool {
	if o != nil && !IsNil(o.Orders) {
		return true
	}

	return false
}

// SetOrders gets a reference to the given int32 and assigns it to the Orders field.
func (o *DaysInner) SetOrders(v int32) {
	o.Orders = &v
}

// GetCr returns the Cr field value if set, zero value otherwise.
func (o *DaysInner) GetCr() float32 {
	if o == nil || IsNil(o.Cr) {
		var ret float32
		return ret
	}
	return *o.Cr
}

// GetCrOk returns a tuple with the Cr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaysInner) GetCrOk() (*float32, bool) {
	if o == nil || IsNil(o.Cr) {
		return nil, false
	}
	return o.Cr, true
}

// HasCr returns a boolean if a field has been set.
func (o *DaysInner) HasCr() bool {
	if o != nil && !IsNil(o.Cr) {
		return true
	}

	return false
}

// SetCr gets a reference to the given float32 and assigns it to the Cr field.
func (o *DaysInner) SetCr(v float32) {
	o.Cr = &v
}

// GetShks returns the Shks field value if set, zero value otherwise.
func (o *DaysInner) GetShks() int32 {
	if o == nil || IsNil(o.Shks) {
		var ret int32
		return ret
	}
	return *o.Shks
}

// GetShksOk returns a tuple with the Shks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaysInner) GetShksOk() (*int32, bool) {
	if o == nil || IsNil(o.Shks) {
		return nil, false
	}
	return o.Shks, true
}

// HasShks returns a boolean if a field has been set.
func (o *DaysInner) HasShks() bool {
	if o != nil && !IsNil(o.Shks) {
		return true
	}

	return false
}

// SetShks gets a reference to the given int32 and assigns it to the Shks field.
func (o *DaysInner) SetShks(v int32) {
	o.Shks = &v
}

// GetSumPrice returns the SumPrice field value if set, zero value otherwise.
func (o *DaysInner) GetSumPrice() float32 {
	if o == nil || IsNil(o.SumPrice) {
		var ret float32
		return ret
	}
	return *o.SumPrice
}

// GetSumPriceOk returns a tuple with the SumPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaysInner) GetSumPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.SumPrice) {
		return nil, false
	}
	return o.SumPrice, true
}

// HasSumPrice returns a boolean if a field has been set.
func (o *DaysInner) HasSumPrice() bool {
	if o != nil && !IsNil(o.SumPrice) {
		return true
	}

	return false
}

// SetSumPrice gets a reference to the given float32 and assigns it to the SumPrice field.
func (o *DaysInner) SetSumPrice(v float32) {
	o.SumPrice = &v
}

// GetApps returns the Apps field value if set, zero value otherwise.
func (o *DaysInner) GetApps() []DaysInnerAppsInner {
	if o == nil || IsNil(o.Apps) {
		var ret []DaysInnerAppsInner
		return ret
	}
	return o.Apps
}

// GetAppsOk returns a tuple with the Apps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaysInner) GetAppsOk() ([]DaysInnerAppsInner, bool) {
	if o == nil || IsNil(o.Apps) {
		return nil, false
	}
	return o.Apps, true
}

// HasApps returns a boolean if a field has been set.
func (o *DaysInner) HasApps() bool {
	if o != nil && !IsNil(o.Apps) {
		return true
	}

	return false
}

// SetApps gets a reference to the given []DaysInnerAppsInner and assigns it to the Apps field.
func (o *DaysInner) SetApps(v []DaysInnerAppsInner) {
	o.Apps = v
}

func (o DaysInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DaysInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Views) {
		toSerialize["views"] = o.Views
	}
	if !IsNil(o.Clicks) {
		toSerialize["clicks"] = o.Clicks
	}
	if !IsNil(o.Ctr) {
		toSerialize["ctr"] = o.Ctr
	}
	if !IsNil(o.Cpc) {
		toSerialize["cpc"] = o.Cpc
	}
	if !IsNil(o.Sum) {
		toSerialize["sum"] = o.Sum
	}
	if !IsNil(o.Atbs) {
		toSerialize["atbs"] = o.Atbs
	}
	if !IsNil(o.Orders) {
		toSerialize["orders"] = o.Orders
	}
	if !IsNil(o.Cr) {
		toSerialize["cr"] = o.Cr
	}
	if !IsNil(o.Shks) {
		toSerialize["shks"] = o.Shks
	}
	if !IsNil(o.SumPrice) {
		toSerialize["sum_price"] = o.SumPrice
	}
	if !IsNil(o.Apps) {
		toSerialize["apps"] = o.Apps
	}
	return toSerialize, nil
}

type NullableDaysInner struct {
	value *DaysInner
	isSet bool
}

func (v NullableDaysInner) Get() *DaysInner {
	return v.value
}

func (v *NullableDaysInner) Set(val *DaysInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDaysInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDaysInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaysInner(val *DaysInner) *NullableDaysInner {
	return &NullableDaysInner{value: val, isSet: true}
}

func (v NullableDaysInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaysInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


