/*
Маркетинг и продвижение

<div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdvV0AuctionBidsPatch200ResponseBidsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvV0AuctionBidsPatch200ResponseBidsInner{}

// AdvV0AuctionBidsPatch200ResponseBidsInner struct for AdvV0AuctionBidsPatch200ResponseBidsInner
type AdvV0AuctionBidsPatch200ResponseBidsInner struct {
	// ID кампании
	AdvertId int64 `json:"advert_id"`
	// Ставки
	NmBids []AdvV0AuctionBidsPatch200ResponseBidsInnerNmBidsInner `json:"nm_bids"`
}

type _AdvV0AuctionBidsPatch200ResponseBidsInner AdvV0AuctionBidsPatch200ResponseBidsInner

// NewAdvV0AuctionBidsPatch200ResponseBidsInner instantiates a new AdvV0AuctionBidsPatch200ResponseBidsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvV0AuctionBidsPatch200ResponseBidsInner(advertId int64, nmBids []AdvV0AuctionBidsPatch200ResponseBidsInnerNmBidsInner) *AdvV0AuctionBidsPatch200ResponseBidsInner {
	this := AdvV0AuctionBidsPatch200ResponseBidsInner{}
	this.AdvertId = advertId
	this.NmBids = nmBids
	return &this
}

// NewAdvV0AuctionBidsPatch200ResponseBidsInnerWithDefaults instantiates a new AdvV0AuctionBidsPatch200ResponseBidsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvV0AuctionBidsPatch200ResponseBidsInnerWithDefaults() *AdvV0AuctionBidsPatch200ResponseBidsInner {
	this := AdvV0AuctionBidsPatch200ResponseBidsInner{}
	return &this
}

// GetAdvertId returns the AdvertId field value
func (o *AdvV0AuctionBidsPatch200ResponseBidsInner) GetAdvertId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AdvertId
}

// GetAdvertIdOk returns a tuple with the AdvertId field value
// and a boolean to check if the value has been set.
func (o *AdvV0AuctionBidsPatch200ResponseBidsInner) GetAdvertIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdvertId, true
}

// SetAdvertId sets field value
func (o *AdvV0AuctionBidsPatch200ResponseBidsInner) SetAdvertId(v int64) {
	o.AdvertId = v
}

// GetNmBids returns the NmBids field value
func (o *AdvV0AuctionBidsPatch200ResponseBidsInner) GetNmBids() []AdvV0AuctionBidsPatch200ResponseBidsInnerNmBidsInner {
	if o == nil {
		var ret []AdvV0AuctionBidsPatch200ResponseBidsInnerNmBidsInner
		return ret
	}

	return o.NmBids
}

// GetNmBidsOk returns a tuple with the NmBids field value
// and a boolean to check if the value has been set.
func (o *AdvV0AuctionBidsPatch200ResponseBidsInner) GetNmBidsOk() ([]AdvV0AuctionBidsPatch200ResponseBidsInnerNmBidsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.NmBids, true
}

// SetNmBids sets field value
func (o *AdvV0AuctionBidsPatch200ResponseBidsInner) SetNmBids(v []AdvV0AuctionBidsPatch200ResponseBidsInnerNmBidsInner) {
	o.NmBids = v
}

func (o AdvV0AuctionBidsPatch200ResponseBidsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvV0AuctionBidsPatch200ResponseBidsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["advert_id"] = o.AdvertId
	toSerialize["nm_bids"] = o.NmBids
	return toSerialize, nil
}

func (o *AdvV0AuctionBidsPatch200ResponseBidsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"advert_id",
		"nm_bids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdvV0AuctionBidsPatch200ResponseBidsInner := _AdvV0AuctionBidsPatch200ResponseBidsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdvV0AuctionBidsPatch200ResponseBidsInner)

	if err != nil {
		return err
	}

	*o = AdvV0AuctionBidsPatch200ResponseBidsInner(varAdvV0AuctionBidsPatch200ResponseBidsInner)

	return err
}

type NullableAdvV0AuctionBidsPatch200ResponseBidsInner struct {
	value *AdvV0AuctionBidsPatch200ResponseBidsInner
	isSet bool
}

func (v NullableAdvV0AuctionBidsPatch200ResponseBidsInner) Get() *AdvV0AuctionBidsPatch200ResponseBidsInner {
	return v.value
}

func (v *NullableAdvV0AuctionBidsPatch200ResponseBidsInner) Set(val *AdvV0AuctionBidsPatch200ResponseBidsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvV0AuctionBidsPatch200ResponseBidsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvV0AuctionBidsPatch200ResponseBidsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvV0AuctionBidsPatch200ResponseBidsInner(val *AdvV0AuctionBidsPatch200ResponseBidsInner) *NullableAdvV0AuctionBidsPatch200ResponseBidsInner {
	return &NullableAdvV0AuctionBidsPatch200ResponseBidsInner{value: val, isSet: true}
}

func (v NullableAdvV0AuctionBidsPatch200ResponseBidsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvV0AuctionBidsPatch200ResponseBidsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


