/*
Маркетинг и продвижение

<div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdvV0BidsPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvV0BidsPatchRequest{}

// AdvV0BidsPatchRequest struct for AdvV0BidsPatchRequest
type AdvV0BidsPatchRequest struct {
	Bids []V0AdvertMultibid `json:"bids"`
}

type _AdvV0BidsPatchRequest AdvV0BidsPatchRequest

// NewAdvV0BidsPatchRequest instantiates a new AdvV0BidsPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvV0BidsPatchRequest(bids []V0AdvertMultibid) *AdvV0BidsPatchRequest {
	this := AdvV0BidsPatchRequest{}
	this.Bids = bids
	return &this
}

// NewAdvV0BidsPatchRequestWithDefaults instantiates a new AdvV0BidsPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvV0BidsPatchRequestWithDefaults() *AdvV0BidsPatchRequest {
	this := AdvV0BidsPatchRequest{}
	return &this
}

// GetBids returns the Bids field value
func (o *AdvV0BidsPatchRequest) GetBids() []V0AdvertMultibid {
	if o == nil {
		var ret []V0AdvertMultibid
		return ret
	}

	return o.Bids
}

// GetBidsOk returns a tuple with the Bids field value
// and a boolean to check if the value has been set.
func (o *AdvV0BidsPatchRequest) GetBidsOk() ([]V0AdvertMultibid, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bids, true
}

// SetBids sets field value
func (o *AdvV0BidsPatchRequest) SetBids(v []V0AdvertMultibid) {
	o.Bids = v
}

func (o AdvV0BidsPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvV0BidsPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bids"] = o.Bids
	return toSerialize, nil
}

func (o *AdvV0BidsPatchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdvV0BidsPatchRequest := _AdvV0BidsPatchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdvV0BidsPatchRequest)

	if err != nil {
		return err
	}

	*o = AdvV0BidsPatchRequest(varAdvV0BidsPatchRequest)

	return err
}

type NullableAdvV0BidsPatchRequest struct {
	value *AdvV0BidsPatchRequest
	isSet bool
}

func (v NullableAdvV0BidsPatchRequest) Get() *AdvV0BidsPatchRequest {
	return v.value
}

func (v *NullableAdvV0BidsPatchRequest) Set(val *AdvV0BidsPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvV0BidsPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvV0BidsPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvV0BidsPatchRequest(val *AdvV0BidsPatchRequest) *NullableAdvV0BidsPatchRequest {
	return &NullableAdvV0BidsPatchRequest{value: val, isSet: true}
}

func (v NullableAdvV0BidsPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvV0BidsPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


