/*
Маркетинг и продвижение

<div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
)

// checks if the AdvV0BidsPatch400ResponseErrorsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvV0BidsPatch400ResponseErrorsInner{}

// AdvV0BidsPatch400ResponseErrorsInner struct for AdvV0BidsPatch400ResponseErrorsInner
type AdvV0BidsPatch400ResponseErrorsInner struct {
	// Детали ошибки
	Detail *string `json:"detail,omitempty"`
	// Поле с ошибкой
	Field *string `json:"field,omitempty"`
}

// NewAdvV0BidsPatch400ResponseErrorsInner instantiates a new AdvV0BidsPatch400ResponseErrorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvV0BidsPatch400ResponseErrorsInner() *AdvV0BidsPatch400ResponseErrorsInner {
	this := AdvV0BidsPatch400ResponseErrorsInner{}
	return &this
}

// NewAdvV0BidsPatch400ResponseErrorsInnerWithDefaults instantiates a new AdvV0BidsPatch400ResponseErrorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvV0BidsPatch400ResponseErrorsInnerWithDefaults() *AdvV0BidsPatch400ResponseErrorsInner {
	this := AdvV0BidsPatch400ResponseErrorsInner{}
	return &this
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *AdvV0BidsPatch400ResponseErrorsInner) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvV0BidsPatch400ResponseErrorsInner) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *AdvV0BidsPatch400ResponseErrorsInner) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *AdvV0BidsPatch400ResponseErrorsInner) SetDetail(v string) {
	o.Detail = &v
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *AdvV0BidsPatch400ResponseErrorsInner) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvV0BidsPatch400ResponseErrorsInner) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *AdvV0BidsPatch400ResponseErrorsInner) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *AdvV0BidsPatch400ResponseErrorsInner) SetField(v string) {
	o.Field = &v
}

func (o AdvV0BidsPatch400ResponseErrorsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvV0BidsPatch400ResponseErrorsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	return toSerialize, nil
}

type NullableAdvV0BidsPatch400ResponseErrorsInner struct {
	value *AdvV0BidsPatch400ResponseErrorsInner
	isSet bool
}

func (v NullableAdvV0BidsPatch400ResponseErrorsInner) Get() *AdvV0BidsPatch400ResponseErrorsInner {
	return v.value
}

func (v *NullableAdvV0BidsPatch400ResponseErrorsInner) Set(val *AdvV0BidsPatch400ResponseErrorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvV0BidsPatch400ResponseErrorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvV0BidsPatch400ResponseErrorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvV0BidsPatch400ResponseErrorsInner(val *AdvV0BidsPatch400ResponseErrorsInner) *NullableAdvV0BidsPatch400ResponseErrorsInner {
	return &NullableAdvV0BidsPatch400ResponseErrorsInner{value: val, isSet: true}
}

func (v NullableAdvV0BidsPatch400ResponseErrorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvV0BidsPatch400ResponseErrorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


