/*
Маркетинг и продвижение

<div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
)

// checks if the ResponseInfoAdvertType8AutoParamsSetsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseInfoAdvertType8AutoParamsSetsInner{}

// ResponseInfoAdvertType8AutoParamsSetsInner struct for ResponseInfoAdvertType8AutoParamsSetsInner
type ResponseInfoAdvertType8AutoParamsSetsInner struct {
	// ID set
	Id *int32 `json:"id,omitempty"`
	// Название set
	Name *string `json:"name,omitempty"`
}

// NewResponseInfoAdvertType8AutoParamsSetsInner instantiates a new ResponseInfoAdvertType8AutoParamsSetsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseInfoAdvertType8AutoParamsSetsInner() *ResponseInfoAdvertType8AutoParamsSetsInner {
	this := ResponseInfoAdvertType8AutoParamsSetsInner{}
	return &this
}

// NewResponseInfoAdvertType8AutoParamsSetsInnerWithDefaults instantiates a new ResponseInfoAdvertType8AutoParamsSetsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseInfoAdvertType8AutoParamsSetsInnerWithDefaults() *ResponseInfoAdvertType8AutoParamsSetsInner {
	this := ResponseInfoAdvertType8AutoParamsSetsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ResponseInfoAdvertType8AutoParamsSetsInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfoAdvertType8AutoParamsSetsInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ResponseInfoAdvertType8AutoParamsSetsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ResponseInfoAdvertType8AutoParamsSetsInner) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ResponseInfoAdvertType8AutoParamsSetsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseInfoAdvertType8AutoParamsSetsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ResponseInfoAdvertType8AutoParamsSetsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ResponseInfoAdvertType8AutoParamsSetsInner) SetName(v string) {
	o.Name = &v
}

func (o ResponseInfoAdvertType8AutoParamsSetsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseInfoAdvertType8AutoParamsSetsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableResponseInfoAdvertType8AutoParamsSetsInner struct {
	value *ResponseInfoAdvertType8AutoParamsSetsInner
	isSet bool
}

func (v NullableResponseInfoAdvertType8AutoParamsSetsInner) Get() *ResponseInfoAdvertType8AutoParamsSetsInner {
	return v.value
}

func (v *NullableResponseInfoAdvertType8AutoParamsSetsInner) Set(val *ResponseInfoAdvertType8AutoParamsSetsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseInfoAdvertType8AutoParamsSetsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseInfoAdvertType8AutoParamsSetsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseInfoAdvertType8AutoParamsSetsInner(val *ResponseInfoAdvertType8AutoParamsSetsInner) *NullableResponseInfoAdvertType8AutoParamsSetsInner {
	return &NullableResponseInfoAdvertType8AutoParamsSetsInner{value: val, isSet: true}
}

func (v NullableResponseInfoAdvertType8AutoParamsSetsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseInfoAdvertType8AutoParamsSetsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


