/*
Маркетинг и продвижение

<div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
)

// checks if the AdvV1StatWordsGet200ResponseWords type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvV1StatWordsGet200ResponseWords{}

// AdvV1StatWordsGet200ResponseWords Блок информации по ключевым фразам
type AdvV1StatWordsGet200ResponseWords struct {
	// Фразовое соответствие (минус фразы)
	Phrase []string `json:"phrase,omitempty"`
	// Точное соответствие (минус фразы)
	Strong []string `json:"strong,omitempty"`
	// Минус фразы из поиска
	Excluded []string `json:"excluded,omitempty"`
	// Фиксированные фразы
	Pluse []string `json:"pluse,omitempty"`
	// Блок со статистикой по ключевым фразам
	Keywords []AdvV1StatWordsGet200ResponseWordsKeywordsInner `json:"keywords,omitempty"`
	// Фиксированные ключевые фразы (`true` — включены, `false` — выключены) 
	Fixed *bool `json:"fixed,omitempty"`
}

// NewAdvV1StatWordsGet200ResponseWords instantiates a new AdvV1StatWordsGet200ResponseWords object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvV1StatWordsGet200ResponseWords() *AdvV1StatWordsGet200ResponseWords {
	this := AdvV1StatWordsGet200ResponseWords{}
	return &this
}

// NewAdvV1StatWordsGet200ResponseWordsWithDefaults instantiates a new AdvV1StatWordsGet200ResponseWords object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvV1StatWordsGet200ResponseWordsWithDefaults() *AdvV1StatWordsGet200ResponseWords {
	this := AdvV1StatWordsGet200ResponseWords{}
	return &this
}

// GetPhrase returns the Phrase field value if set, zero value otherwise.
func (o *AdvV1StatWordsGet200ResponseWords) GetPhrase() []string {
	if o == nil || IsNil(o.Phrase) {
		var ret []string
		return ret
	}
	return o.Phrase
}

// GetPhraseOk returns a tuple with the Phrase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvV1StatWordsGet200ResponseWords) GetPhraseOk() ([]string, bool) {
	if o == nil || IsNil(o.Phrase) {
		return nil, false
	}
	return o.Phrase, true
}

// HasPhrase returns a boolean if a field has been set.
func (o *AdvV1StatWordsGet200ResponseWords) HasPhrase() bool {
	if o != nil && !IsNil(o.Phrase) {
		return true
	}

	return false
}

// SetPhrase gets a reference to the given []string and assigns it to the Phrase field.
func (o *AdvV1StatWordsGet200ResponseWords) SetPhrase(v []string) {
	o.Phrase = v
}

// GetStrong returns the Strong field value if set, zero value otherwise.
func (o *AdvV1StatWordsGet200ResponseWords) GetStrong() []string {
	if o == nil || IsNil(o.Strong) {
		var ret []string
		return ret
	}
	return o.Strong
}

// GetStrongOk returns a tuple with the Strong field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvV1StatWordsGet200ResponseWords) GetStrongOk() ([]string, bool) {
	if o == nil || IsNil(o.Strong) {
		return nil, false
	}
	return o.Strong, true
}

// HasStrong returns a boolean if a field has been set.
func (o *AdvV1StatWordsGet200ResponseWords) HasStrong() bool {
	if o != nil && !IsNil(o.Strong) {
		return true
	}

	return false
}

// SetStrong gets a reference to the given []string and assigns it to the Strong field.
func (o *AdvV1StatWordsGet200ResponseWords) SetStrong(v []string) {
	o.Strong = v
}

// GetExcluded returns the Excluded field value if set, zero value otherwise.
func (o *AdvV1StatWordsGet200ResponseWords) GetExcluded() []string {
	if o == nil || IsNil(o.Excluded) {
		var ret []string
		return ret
	}
	return o.Excluded
}

// GetExcludedOk returns a tuple with the Excluded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvV1StatWordsGet200ResponseWords) GetExcludedOk() ([]string, bool) {
	if o == nil || IsNil(o.Excluded) {
		return nil, false
	}
	return o.Excluded, true
}

// HasExcluded returns a boolean if a field has been set.
func (o *AdvV1StatWordsGet200ResponseWords) HasExcluded() bool {
	if o != nil && !IsNil(o.Excluded) {
		return true
	}

	return false
}

// SetExcluded gets a reference to the given []string and assigns it to the Excluded field.
func (o *AdvV1StatWordsGet200ResponseWords) SetExcluded(v []string) {
	o.Excluded = v
}

// GetPluse returns the Pluse field value if set, zero value otherwise.
func (o *AdvV1StatWordsGet200ResponseWords) GetPluse() []string {
	if o == nil || IsNil(o.Pluse) {
		var ret []string
		return ret
	}
	return o.Pluse
}

// GetPluseOk returns a tuple with the Pluse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvV1StatWordsGet200ResponseWords) GetPluseOk() ([]string, bool) {
	if o == nil || IsNil(o.Pluse) {
		return nil, false
	}
	return o.Pluse, true
}

// HasPluse returns a boolean if a field has been set.
func (o *AdvV1StatWordsGet200ResponseWords) HasPluse() bool {
	if o != nil && !IsNil(o.Pluse) {
		return true
	}

	return false
}

// SetPluse gets a reference to the given []string and assigns it to the Pluse field.
func (o *AdvV1StatWordsGet200ResponseWords) SetPluse(v []string) {
	o.Pluse = v
}

// GetKeywords returns the Keywords field value if set, zero value otherwise.
func (o *AdvV1StatWordsGet200ResponseWords) GetKeywords() []AdvV1StatWordsGet200ResponseWordsKeywordsInner {
	if o == nil || IsNil(o.Keywords) {
		var ret []AdvV1StatWordsGet200ResponseWordsKeywordsInner
		return ret
	}
	return o.Keywords
}

// GetKeywordsOk returns a tuple with the Keywords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvV1StatWordsGet200ResponseWords) GetKeywordsOk() ([]AdvV1StatWordsGet200ResponseWordsKeywordsInner, bool) {
	if o == nil || IsNil(o.Keywords) {
		return nil, false
	}
	return o.Keywords, true
}

// HasKeywords returns a boolean if a field has been set.
func (o *AdvV1StatWordsGet200ResponseWords) HasKeywords() bool {
	if o != nil && !IsNil(o.Keywords) {
		return true
	}

	return false
}

// SetKeywords gets a reference to the given []AdvV1StatWordsGet200ResponseWordsKeywordsInner and assigns it to the Keywords field.
func (o *AdvV1StatWordsGet200ResponseWords) SetKeywords(v []AdvV1StatWordsGet200ResponseWordsKeywordsInner) {
	o.Keywords = v
}

// GetFixed returns the Fixed field value if set, zero value otherwise.
func (o *AdvV1StatWordsGet200ResponseWords) GetFixed() bool {
	if o == nil || IsNil(o.Fixed) {
		var ret bool
		return ret
	}
	return *o.Fixed
}

// GetFixedOk returns a tuple with the Fixed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvV1StatWordsGet200ResponseWords) GetFixedOk() (*bool, bool) {
	if o == nil || IsNil(o.Fixed) {
		return nil, false
	}
	return o.Fixed, true
}

// HasFixed returns a boolean if a field has been set.
func (o *AdvV1StatWordsGet200ResponseWords) HasFixed() bool {
	if o != nil && !IsNil(o.Fixed) {
		return true
	}

	return false
}

// SetFixed gets a reference to the given bool and assigns it to the Fixed field.
func (o *AdvV1StatWordsGet200ResponseWords) SetFixed(v bool) {
	o.Fixed = &v
}

func (o AdvV1StatWordsGet200ResponseWords) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvV1StatWordsGet200ResponseWords) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Phrase) {
		toSerialize["phrase"] = o.Phrase
	}
	if !IsNil(o.Strong) {
		toSerialize["strong"] = o.Strong
	}
	if !IsNil(o.Excluded) {
		toSerialize["excluded"] = o.Excluded
	}
	if !IsNil(o.Pluse) {
		toSerialize["pluse"] = o.Pluse
	}
	if !IsNil(o.Keywords) {
		toSerialize["keywords"] = o.Keywords
	}
	if !IsNil(o.Fixed) {
		toSerialize["fixed"] = o.Fixed
	}
	return toSerialize, nil
}

type NullableAdvV1StatWordsGet200ResponseWords struct {
	value *AdvV1StatWordsGet200ResponseWords
	isSet bool
}

func (v NullableAdvV1StatWordsGet200ResponseWords) Get() *AdvV1StatWordsGet200ResponseWords {
	return v.value
}

func (v *NullableAdvV1StatWordsGet200ResponseWords) Set(val *AdvV1StatWordsGet200ResponseWords) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvV1StatWordsGet200ResponseWords) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvV1StatWordsGet200ResponseWords) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvV1StatWordsGet200ResponseWords(val *AdvV1StatWordsGet200ResponseWords) *NullableAdvV1StatWordsGet200ResponseWords {
	return &NullableAdvV1StatWordsGet200ResponseWords{value: val, isSet: true}
}

func (v NullableAdvV1StatWordsGet200ResponseWords) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvV1StatWordsGet200ResponseWords) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


