/*
Маркетинг и продвижение

<div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdvertSubject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvertSubject{}

// AdvertSubject Предмет
type AdvertSubject struct {
	// ID предмета
	Id int64 `json:"id"`
	// Название предмета
	Name string `json:"name"`
}

type _AdvertSubject AdvertSubject

// NewAdvertSubject instantiates a new AdvertSubject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvertSubject(id int64, name string) *AdvertSubject {
	this := AdvertSubject{}
	this.Id = id
	this.Name = name
	return &this
}

// NewAdvertSubjectWithDefaults instantiates a new AdvertSubject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvertSubjectWithDefaults() *AdvertSubject {
	this := AdvertSubject{}
	return &this
}

// GetId returns the Id field value
func (o *AdvertSubject) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AdvertSubject) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AdvertSubject) SetId(v int64) {
	o.Id = v
}

// GetName returns the Name field value
func (o *AdvertSubject) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AdvertSubject) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AdvertSubject) SetName(v string) {
	o.Name = v
}

func (o AdvertSubject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvertSubject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *AdvertSubject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdvertSubject := _AdvertSubject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdvertSubject)

	if err != nil {
		return err
	}

	*o = AdvertSubject(varAdvertSubject)

	return err
}

type NullableAdvertSubject struct {
	value *AdvertSubject
	isSet bool
}

func (v NullableAdvertSubject) Get() *AdvertSubject {
	return v.value
}

func (v *NullableAdvertSubject) Set(val *AdvertSubject) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvertSubject) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvertSubject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvertSubject(val *AdvertSubject) *NullableAdvertSubject {
	return &NullableAdvertSubject{value: val, isSet: true}
}

func (v NullableAdvertSubject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvertSubject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


