/*
Заказы FBS

<div class=\"description_important\"> <b>Методы для работы со сборочными заданиями модели DBW (Доставка курьером WB) теперь на <a href=\"https://dev.wildberries.ru/release-notes?id=312\">отдельном контуре</a>.</b> </div>  С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [метаданные](/openapi/orders-fbs#tag/Metadannye-FBS) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуски](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB <br>    <div class=\"description_ref\">     Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/127\">инструкции по работе с заказами FBS</a>   </div>  <div class=\"description_important\">     Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 

API version: order
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orders_fbs

import (
	"encoding/json"
)

// checks if the V3OrderMetaAPI type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V3OrderMetaAPI{}

// V3OrderMetaAPI struct for V3OrderMetaAPI
type V3OrderMetaAPI struct {
	// ID сборочного задания
	Id *int32 `json:"id,omitempty"`
	Meta *Meta `json:"meta,omitempty"`
}

// NewV3OrderMetaAPI instantiates a new V3OrderMetaAPI object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3OrderMetaAPI() *V3OrderMetaAPI {
	this := V3OrderMetaAPI{}
	return &this
}

// NewV3OrderMetaAPIWithDefaults instantiates a new V3OrderMetaAPI object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3OrderMetaAPIWithDefaults() *V3OrderMetaAPI {
	this := V3OrderMetaAPI{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V3OrderMetaAPI) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3OrderMetaAPI) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V3OrderMetaAPI) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *V3OrderMetaAPI) SetId(v int32) {
	o.Id = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V3OrderMetaAPI) GetMeta() Meta {
	if o == nil || IsNil(o.Meta) {
		var ret Meta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3OrderMetaAPI) GetMetaOk() (*Meta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V3OrderMetaAPI) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given Meta and assigns it to the Meta field.
func (o *V3OrderMetaAPI) SetMeta(v Meta) {
	o.Meta = &v
}

func (o V3OrderMetaAPI) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V3OrderMetaAPI) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableV3OrderMetaAPI struct {
	value *V3OrderMetaAPI
	isSet bool
}

func (v NullableV3OrderMetaAPI) Get() *V3OrderMetaAPI {
	return v.value
}

func (v *NullableV3OrderMetaAPI) Set(val *V3OrderMetaAPI) {
	v.value = val
	v.isSet = true
}

func (v NullableV3OrderMetaAPI) IsSet() bool {
	return v.isSet
}

func (v *NullableV3OrderMetaAPI) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3OrderMetaAPI(val *V3OrderMetaAPI) *NullableV3OrderMetaAPI {
	return &NullableV3OrderMetaAPI{value: val, isSet: true}
}

func (v NullableV3OrderMetaAPI) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3OrderMetaAPI) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


