/*
 * Аналитика и данные
 *
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorObject400 {
    /// Заголовок ошибки
    #[serde(rename = "title")]
    pub title: String,
    /// Детали ошибки
    #[serde(rename = "detail")]
    pub detail: String,
    /// Уникальный ID запроса
    #[serde(rename = "requestId")]
    pub request_id: String,
    /// ID внутреннего сервиса WB
    #[serde(rename = "origin")]
    pub origin: String,
}

impl ErrorObject400 {
    pub fn new(title: String, detail: String, request_id: String, origin: String) -> ErrorObject400 {
        ErrorObject400 {
            title,
            detail,
            request_id,
            origin,
        }
    }
}

