/*
 * Аналитика и данные
 *
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderByItemRating : Параметры сортировки
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderByItemRating {
    /// Поле для сортировки:   - `feedbackRating` — Рейтинг товара по отзывам   - `feedbackCount` — Все отзывы за период   - `fiveStar` — Отзывы 5 звёзд   - `fourStar` — Отзывы 4 звезды   - `threeStar` — Отзывы 3 звезды   - `twoStar` — Отзывы 2 звезды   - `oneStar` — Отзывы 1 звезда   - `disqualified` — Отзывы, исключённые из рейтинга 
    #[serde(rename = "field")]
    pub field: Field,
    /// Порядок сортировки:   - `asc` — по возрастанию   - `desc` — по убыванию 
    #[serde(rename = "mode")]
    pub mode: Mode,
}

impl OrderByItemRating {
    /// Параметры сортировки
    pub fn new(field: Field, mode: Mode) -> OrderByItemRating {
        OrderByItemRating {
            field,
            mode,
        }
    }
}
/// Поле для сортировки:   - `feedbackRating` — Рейтинг товара по отзывам   - `feedbackCount` — Все отзывы за период   - `fiveStar` — Отзывы 5 звёзд   - `fourStar` — Отзывы 4 звезды   - `threeStar` — Отзывы 3 звезды   - `twoStar` — Отзывы 2 звезды   - `oneStar` — Отзывы 1 звезда   - `disqualified` — Отзывы, исключённые из рейтинга 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Field {
    #[serde(rename = "feedbackRating")]
    FeedbackRating,
    #[serde(rename = "feedbackCount")]
    FeedbackCount,
    #[serde(rename = "fiveStar")]
    FiveStar,
    #[serde(rename = "fourStar")]
    FourStar,
    #[serde(rename = "threeStar")]
    ThreeStar,
    #[serde(rename = "twoStar")]
    TwoStar,
    #[serde(rename = "oneStar")]
    OneStar,
    #[serde(rename = "disqualified")]
    Disqualified,
}

impl Default for Field {
    fn default() -> Field {
        Self::FeedbackRating
    }
}
/// Порядок сортировки:   - `asc` — по возрастанию   - `desc` — по убыванию 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Asc
    }
}

