/*
 * Аналитика и данные
 *
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV) 
 *
 * The version of the OpenAPI document: analytics
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SalesFunnelGroupReqParams : Параметры отчёта
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SalesFunnelGroupReqParams {
    /// Список ID предметов для фильтрации
    #[serde(rename = "subjectIds", skip_serializing_if = "Option::is_none")]
    pub subject_ids: Option<Vec<i32>>,
    /// Список брендов для фильтрации
    #[serde(rename = "brandNames", skip_serializing_if = "Option::is_none")]
    pub brand_names: Option<Vec<String>>,
    /// Список ID ярлыков для фильтрации
    #[serde(rename = "tagIds", skip_serializing_if = "Option::is_none")]
    pub tag_ids: Option<Vec<i64>>,
    /// Начало периода
    #[serde(rename = "startDate")]
    pub start_date: String,
    /// Конец периода
    #[serde(rename = "endDate")]
    pub end_date: String,
    /// Временная зона, по умолчанию Europe/Moscow 
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Как сгруппировать данные (по умолчанию по дням):    * `day` — по дням   * `week` — по неделям   * `month` — по месяцам 
    #[serde(rename = "aggregationLevel", skip_serializing_if = "Option::is_none")]
    pub aggregation_level: Option<String>,
    /// Скрыть удалённые товары
    #[serde(rename = "skipDeletedNm", skip_serializing_if = "Option::is_none")]
    pub skip_deleted_nm: Option<bool>,
}

impl SalesFunnelGroupReqParams {
    /// Параметры отчёта
    pub fn new(start_date: String, end_date: String) -> SalesFunnelGroupReqParams {
        SalesFunnelGroupReqParams {
            subject_ids: None,
            brand_names: None,
            tag_ids: None,
            start_date,
            end_date,
            timezone: None,
            aggregation_level: None,
            skip_deleted_nm: None,
        }
    }
}

