/*
 * Аналитика и данные
 *
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TableCommonMetricsOfficeMissingTime : Время отсутствия товара на складе. Особые случаи:   1. `\"hours\":-1` — бесконечная длительность   2. `\"hours\":-2` — нулевая длительность   3. `\"hours\":-3` — нерассчитанная длительность   4. `\"hours\":-4` — отсутствие в течение всего периода 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableCommonMetricsOfficeMissingTime {
    /// Количество дней
    #[serde(rename = "days")]
    pub days: i32,
    /// Количество часов
    #[serde(rename = "hours")]
    pub hours: i32,
}

impl TableCommonMetricsOfficeMissingTime {
    /// Время отсутствия товара на складе. Особые случаи:   1. `\"hours\":-1` — бесконечная длительность   2. `\"hours\":-2` — нулевая длительность   3. `\"hours\":-3` — нерассчитанная длительность   4. `\"hours\":-4` — отсутствие в течение всего периода 
    pub fn new(days: i32, hours: i32) -> TableCommonMetricsOfficeMissingTime {
        TableCommonMetricsOfficeMissingTime {
            days,
            hours,
        }
    }
}

