/*
 * Аналитика и данные
 *
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableItemBaseCommon {
    /// Артикул WB
    #[serde(rename = "nmId", skip_serializing_if = "Option::is_none")]
    pub nm_id: Option<i64>,
    /// Название товара
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Артикул продавца
    #[serde(rename = "vendorCode", skip_serializing_if = "Option::is_none")]
    pub vendor_code: Option<String>,
    /// ID предмета
    #[serde(rename = "subjectId", skip_serializing_if = "Option::is_none")]
    pub subject_id: Option<i32>,
    /// Название предмета
    #[serde(rename = "subjectName", skip_serializing_if = "Option::is_none")]
    pub subject_name: Option<String>,
    /// Бренд
    #[serde(rename = "brandName", skip_serializing_if = "Option::is_none")]
    pub brand_name: Option<String>,
    /// Название ярлыка
    #[serde(rename = "tagName", skip_serializing_if = "Option::is_none")]
    pub tag_name: Option<String>,
    /// ID ярлыка
    #[serde(rename = "tagId", skip_serializing_if = "Option::is_none")]
    pub tag_id: Option<i64>,
    /// Отзыв закреплён
    #[serde(rename = "pinnedFeedback", skip_serializing_if = "Option::is_none")]
    pub pinned_feedback: Option<bool>,
    /// Рейтинг карточки товара
    #[serde(rename = "rating", skip_serializing_if = "Option::is_none")]
    pub rating: Option<f64>,
    #[serde(rename = "feedbackRating", skip_serializing_if = "Option::is_none")]
    pub feedback_rating: Option<Box<models::TableItemBaseCommonFeedbackRating>>,
}

impl TableItemBaseCommon {
    pub fn new() -> TableItemBaseCommon {
        TableItemBaseCommon {
            nm_id: None,
            title: None,
            vendor_code: None,
            subject_id: None,
            subject_name: None,
            brand_name: None,
            tag_name: None,
            tag_id: None,
            pinned_feedback: None,
            rating: None,
            feedback_rating: None,
        }
    }
}

