/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV3StocksWarehouseIdPost200ResponseStocksInner
 */
export interface ApiV3StocksWarehouseIdPost200ResponseStocksInner {
    /**
     * ID размера товара
     * @type {number}
     * @memberof ApiV3StocksWarehouseIdPost200ResponseStocksInner
     */
    chrtId?: number;
    /**
     * Баркод. Поле будет отключено [9 февраля](https://dev.wildberries.ru/release-notes?id=386)
     * @type {string}
     * @memberof ApiV3StocksWarehouseIdPost200ResponseStocksInner
     * @deprecated
     */
    sku?: string;
    /**
     * Остаток
     * @type {number}
     * @memberof ApiV3StocksWarehouseIdPost200ResponseStocksInner
     */
    amount?: number;
}

/**
 * Check if a given object implements the ApiV3StocksWarehouseIdPost200ResponseStocksInner interface.
 */
export function instanceOfApiV3StocksWarehouseIdPost200ResponseStocksInner(value: object): value is ApiV3StocksWarehouseIdPost200ResponseStocksInner {
    return true;
}

export function ApiV3StocksWarehouseIdPost200ResponseStocksInnerFromJSON(json: any): ApiV3StocksWarehouseIdPost200ResponseStocksInner {
    return ApiV3StocksWarehouseIdPost200ResponseStocksInnerFromJSONTyped(json, false);
}

export function ApiV3StocksWarehouseIdPost200ResponseStocksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV3StocksWarehouseIdPost200ResponseStocksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'chrtId': json['chrtId'] == null ? undefined : json['chrtId'],
        'sku': json['sku'] == null ? undefined : json['sku'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function ApiV3StocksWarehouseIdPost200ResponseStocksInnerToJSON(json: any): ApiV3StocksWarehouseIdPost200ResponseStocksInner {
    return ApiV3StocksWarehouseIdPost200ResponseStocksInnerToJSONTyped(json, false);
}

export function ApiV3StocksWarehouseIdPost200ResponseStocksInnerToJSONTyped(value?: ApiV3StocksWarehouseIdPost200ResponseStocksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chrtId': value['chrtId'],
        'sku': value['sku'],
        'amount': value['amount'],
    };
}

