/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2QuarantineGoodsGet200ResponseData } from './ApiV2QuarantineGoodsGet200ResponseData';
import {
    ApiV2QuarantineGoodsGet200ResponseDataFromJSON,
    ApiV2QuarantineGoodsGet200ResponseDataFromJSONTyped,
    ApiV2QuarantineGoodsGet200ResponseDataToJSON,
    ApiV2QuarantineGoodsGet200ResponseDataToJSONTyped,
} from './ApiV2QuarantineGoodsGet200ResponseData';

/**
 * 
 * @export
 * @interface ApiV2QuarantineGoodsGet200Response
 */
export interface ApiV2QuarantineGoodsGet200Response {
    /**
     * 
     * @type {ApiV2QuarantineGoodsGet200ResponseData}
     * @memberof ApiV2QuarantineGoodsGet200Response
     */
    data?: ApiV2QuarantineGoodsGet200ResponseData | null;
    /**
     * Флаг ошибки
     * @type {boolean}
     * @memberof ApiV2QuarantineGoodsGet200Response
     */
    error?: boolean;
    /**
     * Текст ошибки
     * @type {string}
     * @memberof ApiV2QuarantineGoodsGet200Response
     */
    errorText?: string;
}

/**
 * Check if a given object implements the ApiV2QuarantineGoodsGet200Response interface.
 */
export function instanceOfApiV2QuarantineGoodsGet200Response(value: object): value is ApiV2QuarantineGoodsGet200Response {
    return true;
}

export function ApiV2QuarantineGoodsGet200ResponseFromJSON(json: any): ApiV2QuarantineGoodsGet200Response {
    return ApiV2QuarantineGoodsGet200ResponseFromJSONTyped(json, false);
}

export function ApiV2QuarantineGoodsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2QuarantineGoodsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ApiV2QuarantineGoodsGet200ResponseDataFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'errorText': json['errorText'] == null ? undefined : json['errorText'],
    };
}

export function ApiV2QuarantineGoodsGet200ResponseToJSON(json: any): ApiV2QuarantineGoodsGet200Response {
    return ApiV2QuarantineGoodsGet200ResponseToJSONTyped(json, false);
}

export function ApiV2QuarantineGoodsGet200ResponseToJSONTyped(value?: ApiV2QuarantineGoodsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ApiV2QuarantineGoodsGet200ResponseDataToJSON(value['data']),
        'error': value['error'],
        'errorText': value['errorText'],
    };
}

