/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BrandsResponseBrandsInner } from './BrandsResponseBrandsInner';
import {
    BrandsResponseBrandsInnerFromJSON,
    BrandsResponseBrandsInnerFromJSONTyped,
    BrandsResponseBrandsInnerToJSON,
    BrandsResponseBrandsInnerToJSONTyped,
} from './BrandsResponseBrandsInner';

/**
 * 
 * @export
 * @interface BrandsResponse
 */
export interface BrandsResponse {
    /**
     * 
     * @type {Array<BrandsResponseBrandsInner>}
     * @memberof BrandsResponse
     */
    brands: Array<BrandsResponseBrandsInner>;
    /**
     * Параметр пагинации. Укажите это значение в запросе, чтобы получить следующий пакет данных. Если поле отсутствует, вы получили все данные
     * @type {number}
     * @memberof BrandsResponse
     */
    next?: number;
    /**
     * Общее количество брендов предмета
     * @type {number}
     * @memberof BrandsResponse
     */
    total: number;
}

/**
 * Check if a given object implements the BrandsResponse interface.
 */
export function instanceOfBrandsResponse(value: object): value is BrandsResponse {
    if (!('brands' in value) || value['brands'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function BrandsResponseFromJSON(json: any): BrandsResponse {
    return BrandsResponseFromJSONTyped(json, false);
}

export function BrandsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrandsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'brands': ((json['brands'] as Array<any>).map(BrandsResponseBrandsInnerFromJSON)),
        'next': json['next'] == null ? undefined : json['next'],
        'total': json['total'],
    };
}

export function BrandsResponseToJSON(json: any): BrandsResponse {
    return BrandsResponseToJSONTyped(json, false);
}

export function BrandsResponseToJSONTyped(value?: BrandsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'brands': ((value['brands'] as Array<any>).map(BrandsResponseBrandsInnerToJSON)),
        'next': value['next'],
        'total': value['total'],
    };
}

