/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BrandsResponseErrorErrorsInner
 */
export interface BrandsResponseErrorErrorsInner {
    /**
     * Текст ошибки
     * @type {string}
     * @memberof BrandsResponseErrorErrorsInner
     */
    message?: string;
    /**
     * Параметр, где произошла ошибка
     * @type {string}
     * @memberof BrandsResponseErrorErrorsInner
     */
    location?: string;
    /**
     * Значение параметра, где произошла ошибка
     * @type {any}
     * @memberof BrandsResponseErrorErrorsInner
     */
    value?: any | null;
}

/**
 * Check if a given object implements the BrandsResponseErrorErrorsInner interface.
 */
export function instanceOfBrandsResponseErrorErrorsInner(value: object): value is BrandsResponseErrorErrorsInner {
    return true;
}

export function BrandsResponseErrorErrorsInnerFromJSON(json: any): BrandsResponseErrorErrorsInner {
    return BrandsResponseErrorErrorsInnerFromJSONTyped(json, false);
}

export function BrandsResponseErrorErrorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrandsResponseErrorErrorsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'location': json['location'] == null ? undefined : json['location'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function BrandsResponseErrorErrorsInnerToJSON(json: any): BrandsResponseErrorErrorsInner {
    return BrandsResponseErrorErrorsInnerToJSONTyped(json, false);
}

export function BrandsResponseErrorErrorsInnerToJSONTyped(value?: BrandsResponseErrorErrorsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'location': value['location'],
        'value': value['value'],
    };
}

