/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentV2DirectoryCountriesGet200ResponseDataInner } from './ContentV2DirectoryCountriesGet200ResponseDataInner';
import {
    ContentV2DirectoryCountriesGet200ResponseDataInnerFromJSON,
    ContentV2DirectoryCountriesGet200ResponseDataInnerFromJSONTyped,
    ContentV2DirectoryCountriesGet200ResponseDataInnerToJSON,
    ContentV2DirectoryCountriesGet200ResponseDataInnerToJSONTyped,
} from './ContentV2DirectoryCountriesGet200ResponseDataInner';

/**
 * 
 * @export
 * @interface ContentV2DirectoryCountriesGet200Response
 */
export interface ContentV2DirectoryCountriesGet200Response {
    /**
     * 
     * @type {Array<ContentV2DirectoryCountriesGet200ResponseDataInner>}
     * @memberof ContentV2DirectoryCountriesGet200Response
     */
    data?: Array<ContentV2DirectoryCountriesGet200ResponseDataInner>;
    /**
     * Флаг ошибки
     * @type {boolean}
     * @memberof ContentV2DirectoryCountriesGet200Response
     */
    error?: boolean;
    /**
     * Описание ошибки
     * @type {string}
     * @memberof ContentV2DirectoryCountriesGet200Response
     */
    errorText?: string;
    /**
     * Дополнительные ошибки
     * @type {string}
     * @memberof ContentV2DirectoryCountriesGet200Response
     */
    additionalErrors?: string | null;
}

/**
 * Check if a given object implements the ContentV2DirectoryCountriesGet200Response interface.
 */
export function instanceOfContentV2DirectoryCountriesGet200Response(value: object): value is ContentV2DirectoryCountriesGet200Response {
    return true;
}

export function ContentV2DirectoryCountriesGet200ResponseFromJSON(json: any): ContentV2DirectoryCountriesGet200Response {
    return ContentV2DirectoryCountriesGet200ResponseFromJSONTyped(json, false);
}

export function ContentV2DirectoryCountriesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentV2DirectoryCountriesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ContentV2DirectoryCountriesGet200ResponseDataInnerFromJSON)),
        'error': json['error'] == null ? undefined : json['error'],
        'errorText': json['errorText'] == null ? undefined : json['errorText'],
        'additionalErrors': json['additionalErrors'] == null ? undefined : json['additionalErrors'],
    };
}

export function ContentV2DirectoryCountriesGet200ResponseToJSON(json: any): ContentV2DirectoryCountriesGet200Response {
    return ContentV2DirectoryCountriesGet200ResponseToJSONTyped(json, false);
}

export function ContentV2DirectoryCountriesGet200ResponseToJSONTyped(value?: ContentV2DirectoryCountriesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ContentV2DirectoryCountriesGet200ResponseDataInnerToJSON)),
        'error': value['error'],
        'errorText': value['errorText'],
        'additionalErrors': value['additionalErrors'],
    };
}

