/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Пагинатор
 * @export
 * @interface ContentV2GetCardsTrashPostRequestSettingsCursor
 */
export interface ContentV2GetCardsTrashPostRequestSettingsCursor {
    /**
     * Сколько карточек товаров выдать в ответе
     * @type {number}
     * @memberof ContentV2GetCardsTrashPostRequestSettingsCursor
     */
    limit?: number;
    /**
     * Дата и время помещения в корзину
     * @type {string}
     * @memberof ContentV2GetCardsTrashPostRequestSettingsCursor
     */
    trashedAt?: string;
    /**
     * Артикул WB, с которого надо запрашивать следующий список карточек товаров
     * @type {number}
     * @memberof ContentV2GetCardsTrashPostRequestSettingsCursor
     */
    nmID?: number;
}

/**
 * Check if a given object implements the ContentV2GetCardsTrashPostRequestSettingsCursor interface.
 */
export function instanceOfContentV2GetCardsTrashPostRequestSettingsCursor(value: object): value is ContentV2GetCardsTrashPostRequestSettingsCursor {
    return true;
}

export function ContentV2GetCardsTrashPostRequestSettingsCursorFromJSON(json: any): ContentV2GetCardsTrashPostRequestSettingsCursor {
    return ContentV2GetCardsTrashPostRequestSettingsCursorFromJSONTyped(json, false);
}

export function ContentV2GetCardsTrashPostRequestSettingsCursorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentV2GetCardsTrashPostRequestSettingsCursor {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'trashedAt': json['trashedAt'] == null ? undefined : json['trashedAt'],
        'nmID': json['nmID'] == null ? undefined : json['nmID'],
    };
}

export function ContentV2GetCardsTrashPostRequestSettingsCursorToJSON(json: any): ContentV2GetCardsTrashPostRequestSettingsCursor {
    return ContentV2GetCardsTrashPostRequestSettingsCursorToJSONTyped(json, false);
}

export function ContentV2GetCardsTrashPostRequestSettingsCursorToJSONTyped(value?: ContentV2GetCardsTrashPostRequestSettingsCursor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'trashedAt': value['trashedAt'],
        'nmID': value['nmID'],
    };
}

