/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentV2GetCardsTrashPostRequestSettingsCursor } from './ContentV2GetCardsTrashPostRequestSettingsCursor';
import {
    ContentV2GetCardsTrashPostRequestSettingsCursorFromJSON,
    ContentV2GetCardsTrashPostRequestSettingsCursorFromJSONTyped,
    ContentV2GetCardsTrashPostRequestSettingsCursorToJSON,
    ContentV2GetCardsTrashPostRequestSettingsCursorToJSONTyped,
} from './ContentV2GetCardsTrashPostRequestSettingsCursor';
import type { ContentV2GetCardsTrashPostRequestSettingsFilter } from './ContentV2GetCardsTrashPostRequestSettingsFilter';
import {
    ContentV2GetCardsTrashPostRequestSettingsFilterFromJSON,
    ContentV2GetCardsTrashPostRequestSettingsFilterFromJSONTyped,
    ContentV2GetCardsTrashPostRequestSettingsFilterToJSON,
    ContentV2GetCardsTrashPostRequestSettingsFilterToJSONTyped,
} from './ContentV2GetCardsTrashPostRequestSettingsFilter';
import type { ContentV2GetCardsTrashPostRequestSettingsSort } from './ContentV2GetCardsTrashPostRequestSettingsSort';
import {
    ContentV2GetCardsTrashPostRequestSettingsSortFromJSON,
    ContentV2GetCardsTrashPostRequestSettingsSortFromJSONTyped,
    ContentV2GetCardsTrashPostRequestSettingsSortToJSON,
    ContentV2GetCardsTrashPostRequestSettingsSortToJSONTyped,
} from './ContentV2GetCardsTrashPostRequestSettingsSort';

/**
 * Настройки
 * @export
 * @interface ContentV2GetCardsTrashPostRequestSettings
 */
export interface ContentV2GetCardsTrashPostRequestSettings {
    /**
     * 
     * @type {ContentV2GetCardsTrashPostRequestSettingsSort}
     * @memberof ContentV2GetCardsTrashPostRequestSettings
     */
    sort?: ContentV2GetCardsTrashPostRequestSettingsSort;
    /**
     * 
     * @type {ContentV2GetCardsTrashPostRequestSettingsCursor}
     * @memberof ContentV2GetCardsTrashPostRequestSettings
     */
    cursor?: ContentV2GetCardsTrashPostRequestSettingsCursor;
    /**
     * 
     * @type {ContentV2GetCardsTrashPostRequestSettingsFilter}
     * @memberof ContentV2GetCardsTrashPostRequestSettings
     */
    filter?: ContentV2GetCardsTrashPostRequestSettingsFilter;
}

/**
 * Check if a given object implements the ContentV2GetCardsTrashPostRequestSettings interface.
 */
export function instanceOfContentV2GetCardsTrashPostRequestSettings(value: object): value is ContentV2GetCardsTrashPostRequestSettings {
    return true;
}

export function ContentV2GetCardsTrashPostRequestSettingsFromJSON(json: any): ContentV2GetCardsTrashPostRequestSettings {
    return ContentV2GetCardsTrashPostRequestSettingsFromJSONTyped(json, false);
}

export function ContentV2GetCardsTrashPostRequestSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentV2GetCardsTrashPostRequestSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'sort': json['sort'] == null ? undefined : ContentV2GetCardsTrashPostRequestSettingsSortFromJSON(json['sort']),
        'cursor': json['cursor'] == null ? undefined : ContentV2GetCardsTrashPostRequestSettingsCursorFromJSON(json['cursor']),
        'filter': json['filter'] == null ? undefined : ContentV2GetCardsTrashPostRequestSettingsFilterFromJSON(json['filter']),
    };
}

export function ContentV2GetCardsTrashPostRequestSettingsToJSON(json: any): ContentV2GetCardsTrashPostRequestSettings {
    return ContentV2GetCardsTrashPostRequestSettingsToJSONTyped(json, false);
}

export function ContentV2GetCardsTrashPostRequestSettingsToJSONTyped(value?: ContentV2GetCardsTrashPostRequestSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sort': ContentV2GetCardsTrashPostRequestSettingsSortToJSON(value['sort']),
        'cursor': ContentV2GetCardsTrashPostRequestSettingsCursorToJSON(value['cursor']),
        'filter': ContentV2GetCardsTrashPostRequestSettingsFilterToJSON(value['filter']),
    };
}

