/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Пагинатор
 * @export
 * @interface ContentV2GetCardsTrashPost200ResponseCursor
 */
export interface ContentV2GetCardsTrashPost200ResponseCursor {
    /**
     * Дата и время, с которых надо запрашивать следующий список карточек товаров
     * @type {string}
     * @memberof ContentV2GetCardsTrashPost200ResponseCursor
     */
    trashedAt?: string;
    /**
     * Артикул WB, с которого надо запрашивать следующий список карточек товаров
     * @type {number}
     * @memberof ContentV2GetCardsTrashPost200ResponseCursor
     */
    nmID?: number;
    /**
     * Количество возвращённых карточек товаров
     * @type {number}
     * @memberof ContentV2GetCardsTrashPost200ResponseCursor
     */
    total?: number;
}

/**
 * Check if a given object implements the ContentV2GetCardsTrashPost200ResponseCursor interface.
 */
export function instanceOfContentV2GetCardsTrashPost200ResponseCursor(value: object): value is ContentV2GetCardsTrashPost200ResponseCursor {
    return true;
}

export function ContentV2GetCardsTrashPost200ResponseCursorFromJSON(json: any): ContentV2GetCardsTrashPost200ResponseCursor {
    return ContentV2GetCardsTrashPost200ResponseCursorFromJSONTyped(json, false);
}

export function ContentV2GetCardsTrashPost200ResponseCursorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentV2GetCardsTrashPost200ResponseCursor {
    if (json == null) {
        return json;
    }
    return {
        
        'trashedAt': json['trashedAt'] == null ? undefined : json['trashedAt'],
        'nmID': json['nmID'] == null ? undefined : json['nmID'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ContentV2GetCardsTrashPost200ResponseCursorToJSON(json: any): ContentV2GetCardsTrashPost200ResponseCursor {
    return ContentV2GetCardsTrashPost200ResponseCursorToJSONTyped(json, false);
}

export function ContentV2GetCardsTrashPost200ResponseCursorToJSONTyped(value?: ContentV2GetCardsTrashPost200ResponseCursor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trashedAt': value['trashedAt'],
        'nmID': value['nmID'],
        'total': value['total'],
    };
}

