/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoodsListSizesInner
 */
export interface GoodsListSizesInner {
    /**
     * ID размера. В методах Контента это поле `chrtID`
     * @type {number}
     * @memberof GoodsListSizesInner
     */
    sizeID: number;
    /**
     * Цена
     * @type {number}
     * @memberof GoodsListSizesInner
     */
    price: number;
    /**
     * Цена со скидкой
     * @type {number}
     * @memberof GoodsListSizesInner
     */
    discountedPrice: number;
    /**
     * Цена со скидкой, включая скидку WB Клуба
     * @type {number}
     * @memberof GoodsListSizesInner
     */
    clubDiscountedPrice: number;
    /**
     * Размер товара
     * @type {string}
     * @memberof GoodsListSizesInner
     */
    techSizeName: string;
}

/**
 * Check if a given object implements the GoodsListSizesInner interface.
 */
export function instanceOfGoodsListSizesInner(value: object): value is GoodsListSizesInner {
    if (!('sizeID' in value) || value['sizeID'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('discountedPrice' in value) || value['discountedPrice'] === undefined) return false;
    if (!('clubDiscountedPrice' in value) || value['clubDiscountedPrice'] === undefined) return false;
    if (!('techSizeName' in value) || value['techSizeName'] === undefined) return false;
    return true;
}

export function GoodsListSizesInnerFromJSON(json: any): GoodsListSizesInner {
    return GoodsListSizesInnerFromJSONTyped(json, false);
}

export function GoodsListSizesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoodsListSizesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'sizeID': json['sizeID'],
        'price': json['price'],
        'discountedPrice': json['discountedPrice'],
        'clubDiscountedPrice': json['clubDiscountedPrice'],
        'techSizeName': json['techSizeName'],
    };
}

export function GoodsListSizesInnerToJSON(json: any): GoodsListSizesInner {
    return GoodsListSizesInnerToJSONTyped(json, false);
}

export function GoodsListSizesInnerToJSONTyped(value?: GoodsListSizesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sizeID': value['sizeID'],
        'price': value['price'],
        'discountedPrice': value['discountedPrice'],
        'clubDiscountedPrice': value['clubDiscountedPrice'],
        'techSizeName': value['techSizeName'],
    };
}

