/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaErrors
 */
export interface MediaErrors {
    /**
     * Дополнительные ошибки
     * @type {object}
     * @memberof MediaErrors
     */
    additionalErrors?: object | null;
    /**
     * Данные ошибки
     * @type {object}
     * @memberof MediaErrors
     */
    data?: object | null;
    /**
     * Флаг ошибки
     * @type {boolean}
     * @memberof MediaErrors
     */
    error?: boolean;
    /**
     * Текст ошибки
     * @type {string}
     * @memberof MediaErrors
     */
    errorText?: string;
}

/**
 * Check if a given object implements the MediaErrors interface.
 */
export function instanceOfMediaErrors(value: object): value is MediaErrors {
    return true;
}

export function MediaErrorsFromJSON(json: any): MediaErrors {
    return MediaErrorsFromJSONTyped(json, false);
}

export function MediaErrorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaErrors {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalErrors': json['additionalErrors'] == null ? undefined : json['additionalErrors'],
        'data': json['data'] == null ? undefined : json['data'],
        'error': json['error'] == null ? undefined : json['error'],
        'errorText': json['errorText'] == null ? undefined : json['errorText'],
    };
}

export function MediaErrorsToJSON(json: any): MediaErrors {
    return MediaErrorsToJSONTyped(json, false);
}

export function MediaErrorsToJSONTyped(value?: MediaErrors | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additionalErrors': value['additionalErrors'],
        'data': value['data'],
        'error': value['error'],
        'errorText': value['errorText'],
    };
}

