/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseCardCreateAdditionalErrorsOneOf
 */
export interface ResponseCardCreateAdditionalErrorsOneOf {
    /**
     * 
     * @type {string}
     * @memberof ResponseCardCreateAdditionalErrorsOneOf
     */
    string?: string;
}

/**
 * Check if a given object implements the ResponseCardCreateAdditionalErrorsOneOf interface.
 */
export function instanceOfResponseCardCreateAdditionalErrorsOneOf(value: object): value is ResponseCardCreateAdditionalErrorsOneOf {
    return true;
}

export function ResponseCardCreateAdditionalErrorsOneOfFromJSON(json: any): ResponseCardCreateAdditionalErrorsOneOf {
    return ResponseCardCreateAdditionalErrorsOneOfFromJSONTyped(json, false);
}

export function ResponseCardCreateAdditionalErrorsOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseCardCreateAdditionalErrorsOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'string': json['string'] == null ? undefined : json['string'],
    };
}

export function ResponseCardCreateAdditionalErrorsOneOfToJSON(json: any): ResponseCardCreateAdditionalErrorsOneOf {
    return ResponseCardCreateAdditionalErrorsOneOfToJSONTyped(json, false);
}

export function ResponseCardCreateAdditionalErrorsOneOfToJSONTyped(value?: ResponseCardCreateAdditionalErrorsOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'string': value['string'],
    };
}

