/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * <div class=\"api-block\">  С помощью методов этого раздела вы можете:   - [создавать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получать [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загружать [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настраивать [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - устанавливать [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца  </div>  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami\">инструкции</a> по <strong>работе с товарами</strong> </div> 
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Данные ответа
 * @export
 * @interface SupplierTaskMetadata
 */
export interface SupplierTaskMetadata {
    /**
     * ID загрузки
     * @type {number}
     * @memberof SupplierTaskMetadata
     */
    uploadID?: number;
    /**
     * Статус загрузки:
     *   * `3` — обработана, в товарах нет ошибок, цены и скидки обновились
     *   * `4` — отменена
     *   * `5` — обработана, но в товарах есть ошибки. Для товаров без ошибок цены и скидки обновились, а ошибки в остальных товарах можно получить с помощью метода [Детализация обработанной загрузки](./work-with-products#tag/Ceny-i-skidki/paths/~1api~1v2~1history~1goods~1task/get)
     *   * `6` — обработана, но во всех товарах есть ошибки. Их тоже можно получить с помощью метода [Детализация обработанной загрузки](./work-with-products#tag/Ceny-i-skidki/paths/~1api~1v2~1history~1goods~1task/get)
     * 
     * @type {number}
     * @memberof SupplierTaskMetadata
     */
    status?: number;
    /**
     * Дата и время, когда загрузка создана
     * @type {Date}
     * @memberof SupplierTaskMetadata
     */
    uploadDate?: Date;
    /**
     * Дата и время, когда загрузка отправляется в обработку
     * @type {Date}
     * @memberof SupplierTaskMetadata
     */
    activationDate?: Date;
    /**
     * Всего товаров
     * @type {number}
     * @memberof SupplierTaskMetadata
     */
    overAllGoodsNumber?: number;
    /**
     * Товаров без ошибок
     * @type {number}
     * @memberof SupplierTaskMetadata
     */
    successGoodsNumber?: number;
}

/**
 * Check if a given object implements the SupplierTaskMetadata interface.
 */
export function instanceOfSupplierTaskMetadata(value: object): value is SupplierTaskMetadata {
    return true;
}

export function SupplierTaskMetadataFromJSON(json: any): SupplierTaskMetadata {
    return SupplierTaskMetadataFromJSONTyped(json, false);
}

export function SupplierTaskMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplierTaskMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'uploadID': json['uploadID'] == null ? undefined : json['uploadID'],
        'status': json['status'] == null ? undefined : json['status'],
        'uploadDate': json['uploadDate'] == null ? undefined : (new Date(json['uploadDate'])),
        'activationDate': json['activationDate'] == null ? undefined : (new Date(json['activationDate'])),
        'overAllGoodsNumber': json['overAllGoodsNumber'] == null ? undefined : json['overAllGoodsNumber'],
        'successGoodsNumber': json['successGoodsNumber'] == null ? undefined : json['successGoodsNumber'],
    };
}

export function SupplierTaskMetadataToJSON(json: any): SupplierTaskMetadata {
    return SupplierTaskMetadataToJSONTyped(json, false);
}

export function SupplierTaskMetadataToJSONTyped(value?: SupplierTaskMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uploadID': value['uploadID'],
        'status': value['status'],
        'uploadDate': value['uploadDate'] == null ? value['uploadDate'] : value['uploadDate'].toISOString(),
        'activationDate': value['activationDate'] == null ? value['activationDate'] : value['activationDate'].toISOString(),
        'overAllGoodsNumber': value['overAllGoodsNumber'],
        'successGoodsNumber': value['successGoodsNumber'],
    };
}

