/*
 * Заказы FBS
 *
 * <div class=\"api-block\">  С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [идентификаторы маркировки](/openapi/orders-fbs#tag/fbs-label-identifiers) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуска](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB  </div>  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/knowledge-base/articles/019d49a4-0771-7571-aea9-11d5b597f34c/zakazy-fbs\">инструкции</a> по работе с <strong>заказами FBS</strong> </div>  <div class=\"description_important\">   Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Meta : Устарело. [Будет отключено 30 апреля](https://dev.wildberries.ru/release-notes?id=500)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Meta {
    #[serde(rename = "imei", skip_serializing_if = "Option::is_none")]
    pub imei: Option<Box<models::MetaImei>>,
    #[serde(rename = "uin", skip_serializing_if = "Option::is_none")]
    pub uin: Option<Box<models::MetaUin>>,
    #[serde(rename = "gtin", skip_serializing_if = "Option::is_none")]
    pub gtin: Option<Box<models::MetaGtin>>,
    #[serde(rename = "sgtin", skip_serializing_if = "Option::is_none")]
    pub sgtin: Option<Box<models::MetaSgtin>>,
    #[serde(rename = "expiration", skip_serializing_if = "Option::is_none")]
    pub expiration: Option<Box<models::MetaExpiration>>,
    #[serde(rename = "customsDeclaration", skip_serializing_if = "Option::is_none")]
    pub customs_declaration: Option<Box<models::MetaCustomsDeclaration>>,
}

impl Meta {
    /// Устарело. [Будет отключено 30 апреля](https://dev.wildberries.ru/release-notes?id=500)
    pub fn new() -> Meta {
        Meta {
            imei: None,
            uin: None,
            gtin: None,
            sgtin: None,
            expiration: None,
            customs_declaration: None,
        }
    }
}

