/*
Аналитика и данные

<div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV) 

API version: analytics
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ApiV2NmReportDownloadsPostRequest - struct for ApiV2NmReportDownloadsPostRequest
type ApiV2NmReportDownloadsPostRequest struct {
	SalesFunnelGroupReq *SalesFunnelGroupReq
	SalesFunnelProductReq *SalesFunnelProductReq
	SearchReportGroupReq *SearchReportGroupReq
	SearchReportProductReq *SearchReportProductReq
	SearchReportTextReq *SearchReportTextReq
	StocksReportReq *StocksReportReq
}

// SalesFunnelGroupReqAsApiV2NmReportDownloadsPostRequest is a convenience function that returns SalesFunnelGroupReq wrapped in ApiV2NmReportDownloadsPostRequest
func SalesFunnelGroupReqAsApiV2NmReportDownloadsPostRequest(v *SalesFunnelGroupReq) ApiV2NmReportDownloadsPostRequest {
	return ApiV2NmReportDownloadsPostRequest{
		SalesFunnelGroupReq: v,
	}
}

// SalesFunnelProductReqAsApiV2NmReportDownloadsPostRequest is a convenience function that returns SalesFunnelProductReq wrapped in ApiV2NmReportDownloadsPostRequest
func SalesFunnelProductReqAsApiV2NmReportDownloadsPostRequest(v *SalesFunnelProductReq) ApiV2NmReportDownloadsPostRequest {
	return ApiV2NmReportDownloadsPostRequest{
		SalesFunnelProductReq: v,
	}
}

// SearchReportGroupReqAsApiV2NmReportDownloadsPostRequest is a convenience function that returns SearchReportGroupReq wrapped in ApiV2NmReportDownloadsPostRequest
func SearchReportGroupReqAsApiV2NmReportDownloadsPostRequest(v *SearchReportGroupReq) ApiV2NmReportDownloadsPostRequest {
	return ApiV2NmReportDownloadsPostRequest{
		SearchReportGroupReq: v,
	}
}

// SearchReportProductReqAsApiV2NmReportDownloadsPostRequest is a convenience function that returns SearchReportProductReq wrapped in ApiV2NmReportDownloadsPostRequest
func SearchReportProductReqAsApiV2NmReportDownloadsPostRequest(v *SearchReportProductReq) ApiV2NmReportDownloadsPostRequest {
	return ApiV2NmReportDownloadsPostRequest{
		SearchReportProductReq: v,
	}
}

// SearchReportTextReqAsApiV2NmReportDownloadsPostRequest is a convenience function that returns SearchReportTextReq wrapped in ApiV2NmReportDownloadsPostRequest
func SearchReportTextReqAsApiV2NmReportDownloadsPostRequest(v *SearchReportTextReq) ApiV2NmReportDownloadsPostRequest {
	return ApiV2NmReportDownloadsPostRequest{
		SearchReportTextReq: v,
	}
}

// StocksReportReqAsApiV2NmReportDownloadsPostRequest is a convenience function that returns StocksReportReq wrapped in ApiV2NmReportDownloadsPostRequest
func StocksReportReqAsApiV2NmReportDownloadsPostRequest(v *StocksReportReq) ApiV2NmReportDownloadsPostRequest {
	return ApiV2NmReportDownloadsPostRequest{
		StocksReportReq: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ApiV2NmReportDownloadsPostRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into SalesFunnelGroupReq
	err = newStrictDecoder(data).Decode(&dst.SalesFunnelGroupReq)
	if err == nil {
		jsonSalesFunnelGroupReq, _ := json.Marshal(dst.SalesFunnelGroupReq)
		if string(jsonSalesFunnelGroupReq) == "{}" { // empty struct
			dst.SalesFunnelGroupReq = nil
		} else {
			if err = validator.Validate(dst.SalesFunnelGroupReq); err != nil {
				dst.SalesFunnelGroupReq = nil
			} else {
				match++
			}
		}
	} else {
		dst.SalesFunnelGroupReq = nil
	}

	// try to unmarshal data into SalesFunnelProductReq
	err = newStrictDecoder(data).Decode(&dst.SalesFunnelProductReq)
	if err == nil {
		jsonSalesFunnelProductReq, _ := json.Marshal(dst.SalesFunnelProductReq)
		if string(jsonSalesFunnelProductReq) == "{}" { // empty struct
			dst.SalesFunnelProductReq = nil
		} else {
			if err = validator.Validate(dst.SalesFunnelProductReq); err != nil {
				dst.SalesFunnelProductReq = nil
			} else {
				match++
			}
		}
	} else {
		dst.SalesFunnelProductReq = nil
	}

	// try to unmarshal data into SearchReportGroupReq
	err = newStrictDecoder(data).Decode(&dst.SearchReportGroupReq)
	if err == nil {
		jsonSearchReportGroupReq, _ := json.Marshal(dst.SearchReportGroupReq)
		if string(jsonSearchReportGroupReq) == "{}" { // empty struct
			dst.SearchReportGroupReq = nil
		} else {
			if err = validator.Validate(dst.SearchReportGroupReq); err != nil {
				dst.SearchReportGroupReq = nil
			} else {
				match++
			}
		}
	} else {
		dst.SearchReportGroupReq = nil
	}

	// try to unmarshal data into SearchReportProductReq
	err = newStrictDecoder(data).Decode(&dst.SearchReportProductReq)
	if err == nil {
		jsonSearchReportProductReq, _ := json.Marshal(dst.SearchReportProductReq)
		if string(jsonSearchReportProductReq) == "{}" { // empty struct
			dst.SearchReportProductReq = nil
		} else {
			if err = validator.Validate(dst.SearchReportProductReq); err != nil {
				dst.SearchReportProductReq = nil
			} else {
				match++
			}
		}
	} else {
		dst.SearchReportProductReq = nil
	}

	// try to unmarshal data into SearchReportTextReq
	err = newStrictDecoder(data).Decode(&dst.SearchReportTextReq)
	if err == nil {
		jsonSearchReportTextReq, _ := json.Marshal(dst.SearchReportTextReq)
		if string(jsonSearchReportTextReq) == "{}" { // empty struct
			dst.SearchReportTextReq = nil
		} else {
			if err = validator.Validate(dst.SearchReportTextReq); err != nil {
				dst.SearchReportTextReq = nil
			} else {
				match++
			}
		}
	} else {
		dst.SearchReportTextReq = nil
	}

	// try to unmarshal data into StocksReportReq
	err = newStrictDecoder(data).Decode(&dst.StocksReportReq)
	if err == nil {
		jsonStocksReportReq, _ := json.Marshal(dst.StocksReportReq)
		if string(jsonStocksReportReq) == "{}" { // empty struct
			dst.StocksReportReq = nil
		} else {
			if err = validator.Validate(dst.StocksReportReq); err != nil {
				dst.StocksReportReq = nil
			} else {
				match++
			}
		}
	} else {
		dst.StocksReportReq = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.SalesFunnelGroupReq = nil
		dst.SalesFunnelProductReq = nil
		dst.SearchReportGroupReq = nil
		dst.SearchReportProductReq = nil
		dst.SearchReportTextReq = nil
		dst.StocksReportReq = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ApiV2NmReportDownloadsPostRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ApiV2NmReportDownloadsPostRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ApiV2NmReportDownloadsPostRequest) MarshalJSON() ([]byte, error) {
	if src.SalesFunnelGroupReq != nil {
		return json.Marshal(&src.SalesFunnelGroupReq)
	}

	if src.SalesFunnelProductReq != nil {
		return json.Marshal(&src.SalesFunnelProductReq)
	}

	if src.SearchReportGroupReq != nil {
		return json.Marshal(&src.SearchReportGroupReq)
	}

	if src.SearchReportProductReq != nil {
		return json.Marshal(&src.SearchReportProductReq)
	}

	if src.SearchReportTextReq != nil {
		return json.Marshal(&src.SearchReportTextReq)
	}

	if src.StocksReportReq != nil {
		return json.Marshal(&src.StocksReportReq)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ApiV2NmReportDownloadsPostRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.SalesFunnelGroupReq != nil {
		return obj.SalesFunnelGroupReq
	}

	if obj.SalesFunnelProductReq != nil {
		return obj.SalesFunnelProductReq
	}

	if obj.SearchReportGroupReq != nil {
		return obj.SearchReportGroupReq
	}

	if obj.SearchReportProductReq != nil {
		return obj.SearchReportProductReq
	}

	if obj.SearchReportTextReq != nil {
		return obj.SearchReportTextReq
	}

	if obj.StocksReportReq != nil {
		return obj.StocksReportReq
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ApiV2NmReportDownloadsPostRequest) GetActualInstanceValue() (interface{}) {
	if obj.SalesFunnelGroupReq != nil {
		return *obj.SalesFunnelGroupReq
	}

	if obj.SalesFunnelProductReq != nil {
		return *obj.SalesFunnelProductReq
	}

	if obj.SearchReportGroupReq != nil {
		return *obj.SearchReportGroupReq
	}

	if obj.SearchReportProductReq != nil {
		return *obj.SearchReportProductReq
	}

	if obj.SearchReportTextReq != nil {
		return *obj.SearchReportTextReq
	}

	if obj.StocksReportReq != nil {
		return *obj.StocksReportReq
	}

	// all schemas are nil
	return nil
}

type NullableApiV2NmReportDownloadsPostRequest struct {
	value *ApiV2NmReportDownloadsPostRequest
	isSet bool
}

func (v NullableApiV2NmReportDownloadsPostRequest) Get() *ApiV2NmReportDownloadsPostRequest {
	return v.value
}

func (v *NullableApiV2NmReportDownloadsPostRequest) Set(val *ApiV2NmReportDownloadsPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV2NmReportDownloadsPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV2NmReportDownloadsPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV2NmReportDownloadsPostRequest(val *ApiV2NmReportDownloadsPostRequest) *NullableApiV2NmReportDownloadsPostRequest {
	return &NullableApiV2NmReportDownloadsPostRequest{value: val, isSet: true}
}

func (v NullableApiV2NmReportDownloadsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV2NmReportDownloadsPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


