/* tslint:disable */
/* eslint-disable */
/**
 * Wildberries Цифровой
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentFilesInner } from './ContentFilesInner';
import {
    ContentFilesInnerFromJSON,
    ContentFilesInnerFromJSONTyped,
    ContentFilesInnerToJSON,
    ContentFilesInnerToJSONTyped,
} from './ContentFilesInner';

/**
 * 
 * @export
 * @interface Content
 */
export interface Content {
    /**
     * ID контента
     * @type {number}
     * @memberof Content
     */
    id: number;
    /**
     * ID автора
     * @type {number}
     * @memberof Content
     */
    authorId: number;
    /**
     * Название контента
     * @type {string}
     * @memberof Content
     */
    title: string;
    /**
     * Описание контента
     * @type {string}
     * @memberof Content
     */
    description: string;
    /**
     * Тип файла:
     * - Видеоконтент:
     *     - `video/mp4`
     * - Аудиоконтент:
     *     - `audio/mpeg`
     * - Документ:
     *     - `application/pdf`
     *     - `application/epub+zip`
     *     - `text/plain`
     * 
     * @type {string}
     * @memberof Content
     */
    contentType: ContentContentTypeEnum;
    /**
     * URI адрес контента
     * @type {string}
     * @memberof Content
     */
    uri: string;
    /**
     * Список с информацией о дополнительных файлах
     * @type {Array<ContentFilesInner>}
     * @memberof Content
     */
    files: Array<ContentFilesInner>;
    /**
     * URI адрес на плейлист контента.<br><br>
     * 
     * Если контент является аудио или видео контентом, то файл декодируется в плейлист
     * 
     * @type {string}
     * @memberof Content
     */
    playlist: string;
    /**
     * Хранит в себе метаданные контента:
     * - `bisac` —  ISBN (Международный стандартный книжный номер)
     * - `voice` — Актер озвучивающий аудиоконтент
     * - `author` — Автор контента
     * - `rating` — Возрастное ограничение
     * - `preview` — Короткий отрезок контента для предварительного просмотра
     * - `duration` — Продолжительность контента
     * - `thumbnail` — Список обложки для контента разного разрешения
     * - `dimensions` — Список разрешений видео
     * - `duration_ms` — Продолжительность контента в миллисекундах
     * - `translator` — Автор перевода
     * - `original_name` — Оригинальное название контента
     * - `pages` — Количество страниц в контенте
     * - `encoded_videos` — Список информации (размер, разрешение) для декодированного видео
     * - `encoded_audios` — Список информации (размер, битрейт) для декодированного аудио
     * 
     * @type {any}
     * @memberof Content
     */
    meta?: any | null;
    /**
     * ID категории контента:
     * - `1` — Видеоконтент
     * - `2` — Аудиоконтент
     * - `4` — Документ
     * 
     * @type {number}
     * @memberof Content
     */
    categoryId: ContentCategoryIdEnum;
    /**
     * Статус контента:
     * - `0` — Создан
     * - `1` — Загружено на сервер
     * - `2` — Опубликован
     * - `3` — Ошибка в обработке или публикации
     * - `4` — Обрабатывается
     * - `5` — Отправлено на сервер
     * 
     * @type {number}
     * @memberof Content
     */
    status: number;
    /**
     * Дата создания, UTC+3 (Москва)
     * @type {string}
     * @memberof Content
     */
    created: string;
    /**
     * Дата обновления, UTC+3 (Москва)
     * @type {string}
     * @memberof Content
     */
    updated: string;
}


/**
 * @export
 */
export const ContentContentTypeEnum = {
    VideoMp4: 'video/mp4',
    AudioMpeg: 'audio/mpeg',
    TextPlain: 'text/plain',
    ApplicationPdf: 'application/pdf',
    ApplicationEpubzip: 'application/epub+zip'
} as const;
export type ContentContentTypeEnum = typeof ContentContentTypeEnum[keyof typeof ContentContentTypeEnum];

/**
 * @export
 */
export const ContentCategoryIdEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_4: 4
} as const;
export type ContentCategoryIdEnum = typeof ContentCategoryIdEnum[keyof typeof ContentCategoryIdEnum];


/**
 * Check if a given object implements the Content interface.
 */
export function instanceOfContent(value: object): value is Content {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('uri' in value) || value['uri'] === undefined) return false;
    if (!('files' in value) || value['files'] === undefined) return false;
    if (!('playlist' in value) || value['playlist'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    if (!('updated' in value) || value['updated'] === undefined) return false;
    return true;
}

export function ContentFromJSON(json: any): Content {
    return ContentFromJSONTyped(json, false);
}

export function ContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Content {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'authorId': json['author_id'],
        'title': json['title'],
        'description': json['description'],
        'contentType': json['content_type'],
        'uri': json['uri'],
        'files': ((json['files'] as Array<any>).map(ContentFilesInnerFromJSON)),
        'playlist': json['playlist'],
        'meta': json['meta'] == null ? undefined : json['meta'],
        'categoryId': json['category_id'],
        'status': json['status'],
        'created': json['created'],
        'updated': json['updated'],
    };
}

export function ContentToJSON(json: any): Content {
    return ContentToJSONTyped(json, false);
}

export function ContentToJSONTyped(value?: Content | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'author_id': value['authorId'],
        'title': value['title'],
        'description': value['description'],
        'content_type': value['contentType'],
        'uri': value['uri'],
        'files': ((value['files'] as Array<any>).map(ContentFilesInnerToJSON)),
        'playlist': value['playlist'],
        'meta': value['meta'],
        'category_id': value['categoryId'],
        'status': value['status'],
        'created': value['created'],
        'updated': value['updated'],
    };
}

