/* tslint:disable */
/* eslint-disable */
/**
 * Wildberries Цифровой
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OfferContent } from './OfferContent';
import {
    OfferContentFromJSON,
    OfferContentFromJSONTyped,
    OfferContentToJSON,
    OfferContentToJSONTyped,
} from './OfferContent';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
    TagToJSONTyped,
} from './Tag';

/**
 * 
 * @export
 * @interface OfferResponse
 */
export interface OfferResponse {
    /**
     * ID предложения
     * @type {number}
     * @memberof OfferResponse
     */
    id?: number;
    /**
     * Название предложения
     * @type {string}
     * @memberof OfferResponse
     */
    title?: string;
    /**
     * Описание предложения
     * @type {string}
     * @memberof OfferResponse
     */
    description?: string;
    /**
     * ID категории товара:
     * - `1` — Видеоконтент
     * - `2` — Аудиоконтент
     * - `3` — Ключи активации
     * - `4` — Электронные книги
     * - `5` — Аудиокниги
     * - `6` — Цифровые товары
     * - `8` — Услуги
     * - `12` — Купоны и развлечения
     * - `13` — Подарочные сертификаты
     * 
     * @type {number}
     * @memberof OfferResponse
     */
    section?: OfferResponseSectionEnum;
    /**
     * Массив ID подкатегорий, в котором находится предложение
     * @type {Array<number>}
     * @memberof OfferResponse
     */
    catalogPath?: Array<number>;
    /**
     * Цена предложения, ₽
     * @type {number}
     * @memberof OfferResponse
     */
    price?: number;
    /**
     * Цена с учетом скидки, ₽
     * @type {number}
     * @memberof OfferResponse
     */
    discountPrice?: number;
    /**
     * Список URL-адресов дополнительных изображений, а так же видео превью
     * @type {Array<string>}
     * @memberof OfferResponse
     */
    gallery?: Array<string>;
    /**
     * Метаданные предложения
     * @type {string}
     * @memberof OfferResponse
     */
    meta?: string;
    /**
     * Список тегов. Теги нужны для группирования, ранжирования и облегчения поиска вашего товара
     * @type {Array<Tag>}
     * @memberof OfferResponse
     */
    tags?: Array<Tag> | null;
    /**
     * Обложка предложения
     * @type {Array<string>}
     * @memberof OfferResponse
     */
    thumbnail?: Array<string>;
    /**
     * Контент предложения
     * @type {Array<OfferContent>}
     * @memberof OfferResponse
     */
    content?: Array<OfferContent>;
    /**
     * Дата создания, UTC+3 (Москва)
     * @type {string}
     * @memberof OfferResponse
     */
    created?: string;
    /**
     * Дата обновления, UTC+3 (Москва)
     * @type {string}
     * @memberof OfferResponse
     */
    updated?: string;
    /**
     * Дата удаления, UTC+3 (Москва). `1970-01-01T00:00:00Z` — является нулевым значением
     * @type {string}
     * @memberof OfferResponse
     */
    deleted?: string;
    /**
     * Статус вашего предложения:
     * - `0` — Добавить в черновик
     * - `1` — Опубликовать
     * 
     * @type {number}
     * @memberof OfferResponse
     */
    status?: OfferResponseStatusEnum | null;
    /**
     * Количество просмотров
     * @type {number}
     * @memberof OfferResponse
     */
    viewCount?: number;
    /**
     * Количество покупок
     * @type {number}
     * @memberof OfferResponse
     */
    purchaseCount?: number;
    /**
     * Флаг, который отвечает за ограничение контента для взрослых (блюр контента)
     * @type {boolean}
     * @memberof OfferResponse
     */
    adult?: boolean;
    /**
     * Возрастное ограничение. Это система, которая используется для определения, подходит ли ваше предложение для определенной возрастной группы
     * @type {string}
     * @memberof OfferResponse
     */
    ageRating?: OfferResponseAgeRatingEnum;
    /**
     * Рейтинг предложения
     * @type {number}
     * @memberof OfferResponse
     */
    rating?: number;
}


/**
 * @export
 */
export const OfferResponseSectionEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_10: 10,
    NUMBER_12: 12,
    NUMBER_13: 13
} as const;
export type OfferResponseSectionEnum = typeof OfferResponseSectionEnum[keyof typeof OfferResponseSectionEnum];

/**
 * @export
 */
export const OfferResponseStatusEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type OfferResponseStatusEnum = typeof OfferResponseStatusEnum[keyof typeof OfferResponseStatusEnum];

/**
 * @export
 */
export const OfferResponseAgeRatingEnum = {
    _0: '0+',
    _6: '6+',
    _12: '12+',
    _14: '14+',
    _16: '16+',
    _18: '18+'
} as const;
export type OfferResponseAgeRatingEnum = typeof OfferResponseAgeRatingEnum[keyof typeof OfferResponseAgeRatingEnum];


/**
 * Check if a given object implements the OfferResponse interface.
 */
export function instanceOfOfferResponse(value: object): value is OfferResponse {
    return true;
}

export function OfferResponseFromJSON(json: any): OfferResponse {
    return OfferResponseFromJSONTyped(json, false);
}

export function OfferResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfferResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'section': json['section'] == null ? undefined : json['section'],
        'catalogPath': json['catalog_path'] == null ? undefined : json['catalog_path'],
        'price': json['price'] == null ? undefined : json['price'],
        'discountPrice': json['discount_price'] == null ? undefined : json['discount_price'],
        'gallery': json['gallery'] == null ? undefined : json['gallery'],
        'meta': json['meta'] == null ? undefined : json['meta'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagFromJSON)),
        'thumbnail': json['thumbnail'] == null ? undefined : json['thumbnail'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(OfferContentFromJSON)),
        'created': json['created'] == null ? undefined : json['created'],
        'updated': json['updated'] == null ? undefined : json['updated'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
        'status': json['status'] == null ? undefined : json['status'],
        'viewCount': json['view_count'] == null ? undefined : json['view_count'],
        'purchaseCount': json['purchase_count'] == null ? undefined : json['purchase_count'],
        'adult': json['adult'] == null ? undefined : json['adult'],
        'ageRating': json['age_rating'] == null ? undefined : json['age_rating'],
        'rating': json['rating'] == null ? undefined : json['rating'],
    };
}

export function OfferResponseToJSON(json: any): OfferResponse {
    return OfferResponseToJSONTyped(json, false);
}

export function OfferResponseToJSONTyped(value?: OfferResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'section': value['section'],
        'catalog_path': value['catalogPath'],
        'price': value['price'],
        'discount_price': value['discountPrice'],
        'gallery': value['gallery'],
        'meta': value['meta'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagToJSON)),
        'thumbnail': value['thumbnail'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(OfferContentToJSON)),
        'created': value['created'],
        'updated': value['updated'],
        'deleted': value['deleted'],
        'status': value['status'],
        'view_count': value['viewCount'],
        'purchase_count': value['purchaseCount'],
        'adult': value['adult'],
        'age_rating': value['ageRating'],
        'rating': value['rating'],
    };
}

