/* tslint:disable */
/* eslint-disable */
/**
 * Wildberries Цифровой
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OfferCreateContent } from './OfferCreateContent';
import {
    OfferCreateContentFromJSON,
    OfferCreateContentFromJSONTyped,
    OfferCreateContentToJSON,
    OfferCreateContentToJSONTyped,
} from './OfferCreateContent';
import type { OfferMetaRequest } from './OfferMetaRequest';
import {
    OfferMetaRequestFromJSON,
    OfferMetaRequestFromJSONTyped,
    OfferMetaRequestToJSON,
    OfferMetaRequestToJSONTyped,
} from './OfferMetaRequest';

/**
 * Новое предложение
 * @export
 * @interface OfferCreateRequest
 */
export interface OfferCreateRequest {
    /**
     * Название предложения.<br>Максимальная длина — **500 символов.**
     * @type {string}
     * @memberof OfferCreateRequest
     */
    title: string;
    /**
     * Описание предложения. Это текст, который описывает ваше предложение и помогает людям понять, что именно представляет из себя продаваемый вами товар и чем он может быть полезен. Важно правильно назвать предложение и более подробно прописать его описание, чтобы пользователи узнали как можно больше информации еще до покупки.<br>Максимальная длина — **5000 символов.**
     * @type {string}
     * @memberof OfferCreateRequest
     */
    description: string;
    /**
     * Массив тегов. Теги нужны для группирования, ранжирования и облегчения поиска вашего товара.<br><br>
     * 
     * **Ограничения**:
     * - Максимальное количество тегов — **5**
     * - Максимальная длина тега — **45 символов**
     * 
     * @type {Array<string>}
     * @memberof OfferCreateRequest
     */
    tags: Array<string>;
    /**
     * ID категории предложения:
     * - `1` — Видеоконтент
     * - `2` — Аудиоконтент
     * - `3` — Ключи активации
     * - `4` — Электронные книги
     * - `5` — Аудиокниги
     * - `6` — Цифровые товары
     * - `8` — Услуги
     * - `12` — Купоны и развлечения
     * - `13` — Подарочные сертификаты
     * 
     * @type {number}
     * @memberof OfferCreateRequest
     */
    section: OfferCreateRequestSectionEnum;
    /**
     * Массив ID подкатегорий, в котором находится предложение.<br>
     * Воспользуйтесь методом [Получить категории и их подкатегории](./wbd#tag/Predlozheniya/operation/GetCatalog) для получения ID и правильного сопоставления с категорией.
     * 
     * @type {Array<number>}
     * @memberof OfferCreateRequest
     */
    catalogPath: Array<number>;
    /**
     * Возрастное ограничение. Это система, которая используется для определения, подходит ли ваше предложение для определенной возрастной группы.
     * @type {string}
     * @memberof OfferCreateRequest
     */
    ageRating: OfferCreateRequestAgeRatingEnum;
    /**
     * Цена предложения, ₽
     * @type {number}
     * @memberof OfferCreateRequest
     */
    price: number;
    /**
     * Цена с учетом скидки, ₽
     * @type {number}
     * @memberof OfferCreateRequest
     */
    discountPrice?: number;
    /**
     * Список URL-адресов дополнительных изображений, а так же видео превью.<br>
     * **Можно передать до 8 медиафайлов.**<br>
     * **Важно, чтобы все изображения были в формате JPG или PNG, а видео в формате MP4**
     * 
     * @type {Array<string>}
     * @memberof OfferCreateRequest
     */
    gallery?: Array<string>;
    /**
     * Список ключей.<br>
     * Это **обязательное поле**, если вы хотите создать предложение из категории (`section`):
     * - **Ключи активации** — `3`
     * - **Купоны и развлечения** — `12`
     * - **Подарочные сертификаты** — `13`
     * 
     * **Ограничения:**
     * - Максимальное количество ключей — **1000**
     * - Максимальная длина ключа — **200 символов**
     * 
     * @type {Array<string>}
     * @memberof OfferCreateRequest
     */
    keys?: Array<string>;
    /**
     * Задается статус вашего предложения:
     * - `0` — Добавить в черновик
     * - `1` — Опубликовать
     * 
     * @type {number}
     * @memberof OfferCreateRequest
     */
    status?: OfferCreateRequestStatusEnum;
    /**
     * Список контента
     * @type {Array<OfferCreateContent>}
     * @memberof OfferCreateRequest
     */
    content?: Array<OfferCreateContent>;
    /**
     * 
     * @type {OfferMetaRequest}
     * @memberof OfferCreateRequest
     */
    meta?: OfferMetaRequest;
}


/**
 * @export
 */
export const OfferCreateRequestSectionEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_12: 12,
    NUMBER_13: 13
} as const;
export type OfferCreateRequestSectionEnum = typeof OfferCreateRequestSectionEnum[keyof typeof OfferCreateRequestSectionEnum];

/**
 * @export
 */
export const OfferCreateRequestAgeRatingEnum = {
    _0: '0+',
    _6: '6+',
    _12: '12+',
    _14: '14+',
    _16: '16+',
    _18: '18+'
} as const;
export type OfferCreateRequestAgeRatingEnum = typeof OfferCreateRequestAgeRatingEnum[keyof typeof OfferCreateRequestAgeRatingEnum];

/**
 * @export
 */
export const OfferCreateRequestStatusEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type OfferCreateRequestStatusEnum = typeof OfferCreateRequestStatusEnum[keyof typeof OfferCreateRequestStatusEnum];


/**
 * Check if a given object implements the OfferCreateRequest interface.
 */
export function instanceOfOfferCreateRequest(value: object): value is OfferCreateRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('section' in value) || value['section'] === undefined) return false;
    if (!('catalogPath' in value) || value['catalogPath'] === undefined) return false;
    if (!('ageRating' in value) || value['ageRating'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function OfferCreateRequestFromJSON(json: any): OfferCreateRequest {
    return OfferCreateRequestFromJSONTyped(json, false);
}

export function OfferCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfferCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'tags': json['tags'],
        'section': json['section'],
        'catalogPath': json['catalog_path'],
        'ageRating': json['age_rating'],
        'price': json['price'],
        'discountPrice': json['discount_price'] == null ? undefined : json['discount_price'],
        'gallery': json['gallery'] == null ? undefined : json['gallery'],
        'keys': json['keys'] == null ? undefined : json['keys'],
        'status': json['status'] == null ? undefined : json['status'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(OfferCreateContentFromJSON)),
        'meta': json['meta'] == null ? undefined : OfferMetaRequestFromJSON(json['meta']),
    };
}

export function OfferCreateRequestToJSON(json: any): OfferCreateRequest {
    return OfferCreateRequestToJSONTyped(json, false);
}

export function OfferCreateRequestToJSONTyped(value?: OfferCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'tags': value['tags'],
        'section': value['section'],
        'catalog_path': value['catalogPath'],
        'age_rating': value['ageRating'],
        'price': value['price'],
        'discount_price': value['discountPrice'],
        'gallery': value['gallery'],
        'keys': value['keys'],
        'status': value['status'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(OfferCreateContentToJSON)),
        'meta': OfferMetaRequestToJSON(value['meta']),
    };
}

