/* tslint:disable */
/* eslint-disable */
/**
 * Wildberries Цифровой
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProblemDetails403
 */
export interface ProblemDetails403 {
    /**
     * Дубликат HTTP статус-код
     * @type {number}
     * @memberof ProblemDetails403
     */
    status?: number;
    /**
     * Короткое описание ошибки
     * @type {string}
     * @memberof ProblemDetails403
     */
    title: string;
    /**
     * Служебная информация об ошибке
     * @type {string}
     * @memberof ProblemDetails403
     */
    code?: string;
    /**
     * ID запроса. Дубликат заголовка `X-Request-Id`
     * 
     * @type {string}
     * @memberof ProblemDetails403
     */
    requestId: string;
    /**
     * Имя сервиса
     * @type {string}
     * @memberof ProblemDetails403
     */
    origin?: string;
}

/**
 * Check if a given object implements the ProblemDetails403 interface.
 */
export function instanceOfProblemDetails403(value: object): value is ProblemDetails403 {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function ProblemDetails403FromJSON(json: any): ProblemDetails403 {
    return ProblemDetails403FromJSONTyped(json, false);
}

export function ProblemDetails403FromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemDetails403 {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'title': json['title'],
        'code': json['code'] == null ? undefined : json['code'],
        'requestId': json['requestId'],
        'origin': json['origin'] == null ? undefined : json['origin'],
    };
}

export function ProblemDetails403ToJSON(json: any): ProblemDetails403 {
    return ProblemDetails403ToJSONTyped(json, false);
}

export function ProblemDetails403ToJSONTyped(value?: ProblemDetails403 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'title': value['title'],
        'code': value['code'],
        'requestId': value['requestId'],
        'origin': value['origin'],
    };
}

