/* tslint:disable */
/* eslint-disable */
/**
 * Wildberries Цифровой
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProblemDetails400
 */
export interface ProblemDetails400 {
    /**
     * Дубликат HTTP статус-код
     * @type {number}
     * @memberof ProblemDetails400
     */
    status?: number;
    /**
     * Короткое описание ошибки
     * @type {string}
     * @memberof ProblemDetails400
     */
    title: string;
    /**
     * Развернутое описание ошибки
     * @type {string}
     * @memberof ProblemDetails400
     */
    detail?: string;
    /**
     * Служебная информация об ошибке
     * @type {string}
     * @memberof ProblemDetails400
     */
    code?: string;
    /**
     * Массив ошибок. Для передачи нескольких ошибок
     * 
     * @type {Array<ProblemDetails400>}
     * @memberof ProblemDetails400
     */
    errors?: Array<ProblemDetails400>;
    /**
     * ID запроса. Дубликат заголовка `X-Request-Id`
     * 
     * @type {string}
     * @memberof ProblemDetails400
     */
    requestId: string;
    /**
     * Имя сервиса
     * @type {string}
     * @memberof ProblemDetails400
     */
    origin?: string;
}

/**
 * Check if a given object implements the ProblemDetails400 interface.
 */
export function instanceOfProblemDetails400(value: object): value is ProblemDetails400 {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function ProblemDetails400FromJSON(json: any): ProblemDetails400 {
    return ProblemDetails400FromJSONTyped(json, false);
}

export function ProblemDetails400FromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemDetails400 {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'title': json['title'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'code': json['code'] == null ? undefined : json['code'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ProblemDetails400FromJSON)),
        'requestId': json['requestId'],
        'origin': json['origin'] == null ? undefined : json['origin'],
    };
}

export function ProblemDetails400ToJSON(json: any): ProblemDetails400 {
    return ProblemDetails400ToJSONTyped(json, false);
}

export function ProblemDetails400ToJSONTyped(value?: ProblemDetails400 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'title': value['title'],
        'detail': value['detail'],
        'code': value['code'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ProblemDetails400ToJSON)),
        'requestId': value['requestId'],
        'origin': value['origin'],
    };
}

