/* tslint:disable */
/* eslint-disable */
/**
 * Wildberries Цифровой
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Файл успешно загружен.<br>
 * Ответ содержит URI адрес контента
 * 
 * @export
 * @interface UploadChunkResponse
 */
export interface UploadChunkResponse {
    /**
     * Количество переданных фреймов (частей контента)
     * @type {number}
     * @memberof UploadChunkResponse
     */
    chunk?: number;
    /**
     * URI адреса загруженного файла
     * 
     * @type {string}
     * @memberof UploadChunkResponse
     */
    uri?: string;
}

/**
 * Check if a given object implements the UploadChunkResponse interface.
 */
export function instanceOfUploadChunkResponse(value: object): value is UploadChunkResponse {
    return true;
}

export function UploadChunkResponseFromJSON(json: any): UploadChunkResponse {
    return UploadChunkResponseFromJSONTyped(json, false);
}

export function UploadChunkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadChunkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'chunk': json['chunk'] == null ? undefined : json['chunk'],
        'uri': json['uri'] == null ? undefined : json['uri'],
    };
}

export function UploadChunkResponseToJSON(json: any): UploadChunkResponse {
    return UploadChunkResponseToJSONTyped(json, false);
}

export function UploadChunkResponseToJSONTyped(value?: UploadChunkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chunk': value['chunk'],
        'uri': value['uri'],
    };
}

