/* tslint:disable */
/* eslint-disable */
/**
 * Заказы FBS
 * <div class=\"description_important\"> <b>Методы для работы со сборочными заданиями модели DBW (Доставка курьером WB) теперь на <a href=\"https://dev.wildberries.ru/release-notes?id=312\">отдельном контуре</a>.</b> </div>   В разделе заказов FBS (Fulfillment by Seller) вам доступны методы:   1. Управления [сборочными заданиями](/openapi/orders-fbs#tag/Sborochnye-zadaniya): информация о сборочных заданиях, метаданные, стикеры и так далее.   2. Управления [поставками заказов](/openapi/orders-fbs#tag/Postavki-FBS) продавца на склады WB.   3. Заказа [пропусков](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB. <br> <div class=\"description_important\">     Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV3SuppliesPost201Response
 */
export interface ApiV3SuppliesPost201Response {
    /**
     * ID поставки
     * @type {string}
     * @memberof ApiV3SuppliesPost201Response
     */
    id?: string;
}

/**
 * Check if a given object implements the ApiV3SuppliesPost201Response interface.
 */
export function instanceOfApiV3SuppliesPost201Response(value: object): value is ApiV3SuppliesPost201Response {
    return true;
}

export function ApiV3SuppliesPost201ResponseFromJSON(json: any): ApiV3SuppliesPost201Response {
    return ApiV3SuppliesPost201ResponseFromJSONTyped(json, false);
}

export function ApiV3SuppliesPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV3SuppliesPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function ApiV3SuppliesPost201ResponseToJSON(json: any): ApiV3SuppliesPost201Response {
    return ApiV3SuppliesPost201ResponseToJSONTyped(json, false);
}

export function ApiV3SuppliesPost201ResponseToJSONTyped(value?: ApiV3SuppliesPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

