/* tslint:disable */
/* eslint-disable */
/**
 * Заказы FBS
 * <div class=\"description_important\"> <b>Методы для работы со сборочными заданиями модели DBW (Доставка курьером WB) теперь на <a href=\"https://dev.wildberries.ru/release-notes?id=312\">отдельном контуре</a>.</b> </div>   В разделе заказов FBS (Fulfillment by Seller) вам доступны методы:   1. Управления [сборочными заданиями](/openapi/orders-fbs#tag/Sborochnye-zadaniya): информация о сборочных заданиях, метаданные, стикеры и так далее.   2. Управления [поставками заказов](/openapi/orders-fbs#tag/Postavki-FBS) продавца на склады WB.   3. Заказа [пропусков](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB. <br> <div class=\"description_important\">     Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV3SuppliesSupplyIdBarcodeGet200Response
 */
export interface ApiV3SuppliesSupplyIdBarcodeGet200Response {
    /**
     * Закодированное значение стикера (ID поставки)
     * @type {string}
     * @memberof ApiV3SuppliesSupplyIdBarcodeGet200Response
     */
    barcode?: string;
    /**
     * Полное представление стикера в заданном формате (кодировка base64)
     * @type {string}
     * @memberof ApiV3SuppliesSupplyIdBarcodeGet200Response
     */
    file?: string;
}

/**
 * Check if a given object implements the ApiV3SuppliesSupplyIdBarcodeGet200Response interface.
 */
export function instanceOfApiV3SuppliesSupplyIdBarcodeGet200Response(value: object): value is ApiV3SuppliesSupplyIdBarcodeGet200Response {
    return true;
}

export function ApiV3SuppliesSupplyIdBarcodeGet200ResponseFromJSON(json: any): ApiV3SuppliesSupplyIdBarcodeGet200Response {
    return ApiV3SuppliesSupplyIdBarcodeGet200ResponseFromJSONTyped(json, false);
}

export function ApiV3SuppliesSupplyIdBarcodeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV3SuppliesSupplyIdBarcodeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'barcode': json['barcode'] == null ? undefined : json['barcode'],
        'file': json['file'] == null ? undefined : json['file'],
    };
}

export function ApiV3SuppliesSupplyIdBarcodeGet200ResponseToJSON(json: any): ApiV3SuppliesSupplyIdBarcodeGet200Response {
    return ApiV3SuppliesSupplyIdBarcodeGet200ResponseToJSONTyped(json, false);
}

export function ApiV3SuppliesSupplyIdBarcodeGet200ResponseToJSONTyped(value?: ApiV3SuppliesSupplyIdBarcodeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'barcode': value['barcode'],
        'file': value['file'],
    };
}

