/* tslint:disable */
/* eslint-disable */
/**
 * Заказы FBS
 * <div class=\"description_important\"> <b>Методы для работы со сборочными заданиями модели DBW (Доставка курьером WB) теперь на <a href=\"https://dev.wildberries.ru/release-notes?id=312\">отдельном контуре</a>.</b> </div>   В разделе заказов FBS (Fulfillment by Seller) вам доступны методы:   1. Управления [сборочными заданиями](/openapi/orders-fbs#tag/Sborochnye-zadaniya): информация о сборочных заданиях, метаданные, стикеры и так далее.   2. Управления [поставками заказов](/openapi/orders-fbs#tag/Postavki-FBS) продавца на склады WB.   3. Заказа [пропусков](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB. <br> <div class=\"description_important\">     Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CrossborderTurkeyClientInfo
 */
export interface CrossborderTurkeyClientInfo {
    /**
     * Имя клиента
     * @type {string}
     * @memberof CrossborderTurkeyClientInfo
     */
    firstName?: string;
    /**
     * Фамилия, Имя, Отчество
     * @type {string}
     * @memberof CrossborderTurkeyClientInfo
     */
    fullName?: string;
    /**
     * Фамилия клиента
     * @type {string}
     * @memberof CrossborderTurkeyClientInfo
     */
    lastName?: string;
    /**
     * Отчество клиента
     * @type {string}
     * @memberof CrossborderTurkeyClientInfo
     */
    middleName?: string;
    /**
     * Номер заказа
     * @type {number}
     * @memberof CrossborderTurkeyClientInfo
     */
    orderID?: number;
    /**
     * Телефон для связи с клиентом
     * @type {string}
     * @memberof CrossborderTurkeyClientInfo
     */
    phone?: string;
    /**
     * Не используется
     * @type {string}
     * @memberof CrossborderTurkeyClientInfo
     */
    phoneCode?: string;
}

/**
 * Check if a given object implements the CrossborderTurkeyClientInfo interface.
 */
export function instanceOfCrossborderTurkeyClientInfo(value: object): value is CrossborderTurkeyClientInfo {
    return true;
}

export function CrossborderTurkeyClientInfoFromJSON(json: any): CrossborderTurkeyClientInfo {
    return CrossborderTurkeyClientInfoFromJSONTyped(json, false);
}

export function CrossborderTurkeyClientInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrossborderTurkeyClientInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'middleName': json['middleName'] == null ? undefined : json['middleName'],
        'orderID': json['orderID'] == null ? undefined : json['orderID'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'phoneCode': json['phoneCode'] == null ? undefined : json['phoneCode'],
    };
}

export function CrossborderTurkeyClientInfoToJSON(json: any): CrossborderTurkeyClientInfo {
    return CrossborderTurkeyClientInfoToJSONTyped(json, false);
}

export function CrossborderTurkeyClientInfoToJSONTyped(value?: CrossborderTurkeyClientInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'fullName': value['fullName'],
        'lastName': value['lastName'],
        'middleName': value['middleName'],
        'orderID': value['orderID'],
        'phone': value['phone'],
        'phoneCode': value['phoneCode'],
    };
}

