/* tslint:disable */
/* eslint-disable */
/**
 * Заказы FBS
 * <div class=\"description_important\"> <b>Методы для работы со сборочными заданиями модели DBW (Доставка курьером WB) теперь на <a href=\"https://dev.wildberries.ru/release-notes?id=312\">отдельном контуре</a>.</b> </div>   В разделе заказов FBS (Fulfillment by Seller) вам доступны методы:   1. Управления [сборочными заданиями](/openapi/orders-fbs#tag/Sborochnye-zadaniya): информация о сборочных заданиях, метаданные, стикеры и так далее.   2. Управления [поставками заказов](/openapi/orders-fbs#tag/Postavki-FBS) продавца на склады WB.   3. Заказа [пропусков](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB. <br> <div class=\"description_important\">     Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * GTIN
 * @export
 * @interface MetaGtin
 */
export interface MetaGtin {
    /**
     * 
     * @type {string}
     * @memberof MetaGtin
     */
    value?: string | null;
}

/**
 * Check if a given object implements the MetaGtin interface.
 */
export function instanceOfMetaGtin(value: object): value is MetaGtin {
    return true;
}

export function MetaGtinFromJSON(json: any): MetaGtin {
    return MetaGtinFromJSONTyped(json, false);
}

export function MetaGtinFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaGtin {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function MetaGtinToJSON(json: any): MetaGtin {
    return MetaGtinToJSONTyped(json, false);
}

export function MetaGtinToJSONTyped(value?: MetaGtin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

