/* tslint:disable */
/* eslint-disable */
/**
 * Заказы FBS
 * <div class=\"description_important\"> <b>Методы для работы со сборочными заданиями модели DBW (Доставка курьером WB) теперь на <a href=\"https://dev.wildberries.ru/release-notes?id=312\">отдельном контуре</a>.</b> </div>   В разделе заказов FBS (Fulfillment by Seller) вам доступны методы:   1. Управления [сборочными заданиями](/openapi/orders-fbs#tag/Sborochnye-zadaniya): информация о сборочных заданиях, метаданные, стикеры и так далее.   2. Управления [поставками заказов](/openapi/orders-fbs#tag/Postavki-FBS) продавца на склады WB.   3. Заказа [пропусков](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB. <br> <div class=\"description_important\">     Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';

/**
 * 
 * @export
 * @interface V3OrderMetaAPI
 */
export interface V3OrderMetaAPI {
    /**
     * ID сборочного задания
     * @type {number}
     * @memberof V3OrderMetaAPI
     */
    id?: number;
    /**
     * 
     * @type {Meta}
     * @memberof V3OrderMetaAPI
     */
    meta?: Meta;
}

/**
 * Check if a given object implements the V3OrderMetaAPI interface.
 */
export function instanceOfV3OrderMetaAPI(value: object): value is V3OrderMetaAPI {
    return true;
}

export function V3OrderMetaAPIFromJSON(json: any): V3OrderMetaAPI {
    return V3OrderMetaAPIFromJSONTyped(json, false);
}

export function V3OrderMetaAPIFromJSONTyped(json: any, ignoreDiscriminator: boolean): V3OrderMetaAPI {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function V3OrderMetaAPIToJSON(json: any): V3OrderMetaAPI {
    return V3OrderMetaAPIToJSONTyped(json, false);
}

export function V3OrderMetaAPIToJSONTyped(value?: V3OrderMetaAPI | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'meta': value['meta'],
    };
}

