/*
Отчёты

<div class=\"description_important\">   Узнать больше об отчётах можно в <a href=\"https://seller.wildberries.ru/instructions/subcategory/5f2162c5-069b-416d-a4e1-48da2a76e6b0\">справочном центре</a> </div>  С помощью этих методов вы можете получить [основные отчёты](/openapi/reports#tag/Osnovnye-otchyoty) и отчёты о:   1. [Остатках на складах](/openapi/reports#tag/Otchyot-ob-ostatkah-na-skladah)   2. [Товарах с обязательной маркировкой](/openapi/reports#tag/Otchyot-o-tovarah-c-obyazatelnoj-markirovkoj)   3. [Удержаниях](/openapi/reports#tag/Otchyoty-ob-uderzhaniyah)   4. [Платной приёмке](/openapi/reports#tag/Platnaya-priyomka)   5. [Платном хранении](/openapi/reports#tag/Platnoe-hranenie)   6. [Продажах по регионам](/openapi/reports#tag/Prodazhi-po-regionam)   7. [Доле бренда в продажах](/openapi/reports#tag/Dolya-brenda-v-prodazhah)   8. [Скрытых товарах](/openapi/reports#tag/Skrytye-tovary)   9. [Возвратах и перемещении товаров](/openapi/reports#tag/Otchyot-o-vozvratah-i-peremeshenii-tovarov) 

API version: reports
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"time"
)

// checks if the ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner{}

// ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner struct for ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner
type ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner struct {
	// Сумма штрафа в копейках
	Amount *int32 `json:"amount,omitempty"`
	// Дата изменения характеристик товара на складе
	Date *time.Time `json:"date,omitempty"`
	// Новый баркод в карточке товара
	NewBarcode *string `json:"newBarcode,omitempty"`
	// Новый цвет
	NewColor *string `json:"newColor,omitempty"`
	// Новый артикул продавца
	NewSa *string `json:"newSa,omitempty"`
	// Новый штрихкод товара в WB
	NewShkID *int32 `json:"newShkID,omitempty"`
	// Новый размер
	NewSize *string `json:"newSize,omitempty"`
	// Артикул WB
	NmID *int32 `json:"nmID,omitempty"`
	// Старый баркод из карточки товара
	OldBarcode *string `json:"oldBarcode,omitempty"`
	// Старый цвет
	OldColor *string `json:"oldColor,omitempty"`
	// Старый артикул продавца
	OldSa *string `json:"oldSa,omitempty"`
	// Старый штрихкод товара в WB
	OldShkID *int32 `json:"oldShkID,omitempty"`
	// Старый размер
	OldSize *string `json:"oldSize,omitempty"`
}

// NewApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner instantiates a new ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner() *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner {
	this := ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner{}
	return &this
}

// NewApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInnerWithDefaults instantiates a new ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInnerWithDefaults() *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner {
	this := ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) SetAmount(v int32) {
	o.Amount = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetDate() time.Time {
	if o == nil || IsNil(o.Date) {
		var ret time.Time
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given time.Time and assigns it to the Date field.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) SetDate(v time.Time) {
	o.Date = &v
}

// GetNewBarcode returns the NewBarcode field value if set, zero value otherwise.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetNewBarcode() string {
	if o == nil || IsNil(o.NewBarcode) {
		var ret string
		return ret
	}
	return *o.NewBarcode
}

// GetNewBarcodeOk returns a tuple with the NewBarcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetNewBarcodeOk() (*string, bool) {
	if o == nil || IsNil(o.NewBarcode) {
		return nil, false
	}
	return o.NewBarcode, true
}

// HasNewBarcode returns a boolean if a field has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) HasNewBarcode() bool {
	if o != nil && !IsNil(o.NewBarcode) {
		return true
	}

	return false
}

// SetNewBarcode gets a reference to the given string and assigns it to the NewBarcode field.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) SetNewBarcode(v string) {
	o.NewBarcode = &v
}

// GetNewColor returns the NewColor field value if set, zero value otherwise.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetNewColor() string {
	if o == nil || IsNil(o.NewColor) {
		var ret string
		return ret
	}
	return *o.NewColor
}

// GetNewColorOk returns a tuple with the NewColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetNewColorOk() (*string, bool) {
	if o == nil || IsNil(o.NewColor) {
		return nil, false
	}
	return o.NewColor, true
}

// HasNewColor returns a boolean if a field has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) HasNewColor() bool {
	if o != nil && !IsNil(o.NewColor) {
		return true
	}

	return false
}

// SetNewColor gets a reference to the given string and assigns it to the NewColor field.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) SetNewColor(v string) {
	o.NewColor = &v
}

// GetNewSa returns the NewSa field value if set, zero value otherwise.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetNewSa() string {
	if o == nil || IsNil(o.NewSa) {
		var ret string
		return ret
	}
	return *o.NewSa
}

// GetNewSaOk returns a tuple with the NewSa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetNewSaOk() (*string, bool) {
	if o == nil || IsNil(o.NewSa) {
		return nil, false
	}
	return o.NewSa, true
}

// HasNewSa returns a boolean if a field has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) HasNewSa() bool {
	if o != nil && !IsNil(o.NewSa) {
		return true
	}

	return false
}

// SetNewSa gets a reference to the given string and assigns it to the NewSa field.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) SetNewSa(v string) {
	o.NewSa = &v
}

// GetNewShkID returns the NewShkID field value if set, zero value otherwise.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetNewShkID() int32 {
	if o == nil || IsNil(o.NewShkID) {
		var ret int32
		return ret
	}
	return *o.NewShkID
}

// GetNewShkIDOk returns a tuple with the NewShkID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetNewShkIDOk() (*int32, bool) {
	if o == nil || IsNil(o.NewShkID) {
		return nil, false
	}
	return o.NewShkID, true
}

// HasNewShkID returns a boolean if a field has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) HasNewShkID() bool {
	if o != nil && !IsNil(o.NewShkID) {
		return true
	}

	return false
}

// SetNewShkID gets a reference to the given int32 and assigns it to the NewShkID field.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) SetNewShkID(v int32) {
	o.NewShkID = &v
}

// GetNewSize returns the NewSize field value if set, zero value otherwise.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetNewSize() string {
	if o == nil || IsNil(o.NewSize) {
		var ret string
		return ret
	}
	return *o.NewSize
}

// GetNewSizeOk returns a tuple with the NewSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetNewSizeOk() (*string, bool) {
	if o == nil || IsNil(o.NewSize) {
		return nil, false
	}
	return o.NewSize, true
}

// HasNewSize returns a boolean if a field has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) HasNewSize() bool {
	if o != nil && !IsNil(o.NewSize) {
		return true
	}

	return false
}

// SetNewSize gets a reference to the given string and assigns it to the NewSize field.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) SetNewSize(v string) {
	o.NewSize = &v
}

// GetNmID returns the NmID field value if set, zero value otherwise.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetNmID() int32 {
	if o == nil || IsNil(o.NmID) {
		var ret int32
		return ret
	}
	return *o.NmID
}

// GetNmIDOk returns a tuple with the NmID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetNmIDOk() (*int32, bool) {
	if o == nil || IsNil(o.NmID) {
		return nil, false
	}
	return o.NmID, true
}

// HasNmID returns a boolean if a field has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) HasNmID() bool {
	if o != nil && !IsNil(o.NmID) {
		return true
	}

	return false
}

// SetNmID gets a reference to the given int32 and assigns it to the NmID field.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) SetNmID(v int32) {
	o.NmID = &v
}

// GetOldBarcode returns the OldBarcode field value if set, zero value otherwise.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetOldBarcode() string {
	if o == nil || IsNil(o.OldBarcode) {
		var ret string
		return ret
	}
	return *o.OldBarcode
}

// GetOldBarcodeOk returns a tuple with the OldBarcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetOldBarcodeOk() (*string, bool) {
	if o == nil || IsNil(o.OldBarcode) {
		return nil, false
	}
	return o.OldBarcode, true
}

// HasOldBarcode returns a boolean if a field has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) HasOldBarcode() bool {
	if o != nil && !IsNil(o.OldBarcode) {
		return true
	}

	return false
}

// SetOldBarcode gets a reference to the given string and assigns it to the OldBarcode field.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) SetOldBarcode(v string) {
	o.OldBarcode = &v
}

// GetOldColor returns the OldColor field value if set, zero value otherwise.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetOldColor() string {
	if o == nil || IsNil(o.OldColor) {
		var ret string
		return ret
	}
	return *o.OldColor
}

// GetOldColorOk returns a tuple with the OldColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetOldColorOk() (*string, bool) {
	if o == nil || IsNil(o.OldColor) {
		return nil, false
	}
	return o.OldColor, true
}

// HasOldColor returns a boolean if a field has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) HasOldColor() bool {
	if o != nil && !IsNil(o.OldColor) {
		return true
	}

	return false
}

// SetOldColor gets a reference to the given string and assigns it to the OldColor field.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) SetOldColor(v string) {
	o.OldColor = &v
}

// GetOldSa returns the OldSa field value if set, zero value otherwise.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetOldSa() string {
	if o == nil || IsNil(o.OldSa) {
		var ret string
		return ret
	}
	return *o.OldSa
}

// GetOldSaOk returns a tuple with the OldSa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetOldSaOk() (*string, bool) {
	if o == nil || IsNil(o.OldSa) {
		return nil, false
	}
	return o.OldSa, true
}

// HasOldSa returns a boolean if a field has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) HasOldSa() bool {
	if o != nil && !IsNil(o.OldSa) {
		return true
	}

	return false
}

// SetOldSa gets a reference to the given string and assigns it to the OldSa field.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) SetOldSa(v string) {
	o.OldSa = &v
}

// GetOldShkID returns the OldShkID field value if set, zero value otherwise.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetOldShkID() int32 {
	if o == nil || IsNil(o.OldShkID) {
		var ret int32
		return ret
	}
	return *o.OldShkID
}

// GetOldShkIDOk returns a tuple with the OldShkID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetOldShkIDOk() (*int32, bool) {
	if o == nil || IsNil(o.OldShkID) {
		return nil, false
	}
	return o.OldShkID, true
}

// HasOldShkID returns a boolean if a field has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) HasOldShkID() bool {
	if o != nil && !IsNil(o.OldShkID) {
		return true
	}

	return false
}

// SetOldShkID gets a reference to the given int32 and assigns it to the OldShkID field.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) SetOldShkID(v int32) {
	o.OldShkID = &v
}

// GetOldSize returns the OldSize field value if set, zero value otherwise.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetOldSize() string {
	if o == nil || IsNil(o.OldSize) {
		var ret string
		return ret
	}
	return *o.OldSize
}

// GetOldSizeOk returns a tuple with the OldSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) GetOldSizeOk() (*string, bool) {
	if o == nil || IsNil(o.OldSize) {
		return nil, false
	}
	return o.OldSize, true
}

// HasOldSize returns a boolean if a field has been set.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) HasOldSize() bool {
	if o != nil && !IsNil(o.OldSize) {
		return true
	}

	return false
}

// SetOldSize gets a reference to the given string and assigns it to the OldSize field.
func (o *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) SetOldSize(v string) {
	o.OldSize = &v
}

func (o ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.NewBarcode) {
		toSerialize["newBarcode"] = o.NewBarcode
	}
	if !IsNil(o.NewColor) {
		toSerialize["newColor"] = o.NewColor
	}
	if !IsNil(o.NewSa) {
		toSerialize["newSa"] = o.NewSa
	}
	if !IsNil(o.NewShkID) {
		toSerialize["newShkID"] = o.NewShkID
	}
	if !IsNil(o.NewSize) {
		toSerialize["newSize"] = o.NewSize
	}
	if !IsNil(o.NmID) {
		toSerialize["nmID"] = o.NmID
	}
	if !IsNil(o.OldBarcode) {
		toSerialize["oldBarcode"] = o.OldBarcode
	}
	if !IsNil(o.OldColor) {
		toSerialize["oldColor"] = o.OldColor
	}
	if !IsNil(o.OldSa) {
		toSerialize["oldSa"] = o.OldSa
	}
	if !IsNil(o.OldShkID) {
		toSerialize["oldShkID"] = o.OldShkID
	}
	if !IsNil(o.OldSize) {
		toSerialize["oldSize"] = o.OldSize
	}
	return toSerialize, nil
}

type NullableApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner struct {
	value *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner
	isSet bool
}

func (v NullableApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) Get() *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner {
	return v.value
}

func (v *NullableApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) Set(val *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner(val *ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) *NullableApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner {
	return &NullableApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner{value: val, isSet: true}
}

func (v NullableApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


