/*
Отчёты

<div class=\"description_important\">   Узнать больше об отчётах можно в <a href=\"https://seller.wildberries.ru/instructions/subcategory/5f2162c5-069b-416d-a4e1-48da2a76e6b0\">справочном центре</a> </div>  С помощью этих методов вы можете получить [основные отчёты](/openapi/reports#tag/Osnovnye-otchyoty) и отчёты о:   1. [Остатках на складах](/openapi/reports#tag/Otchyot-ob-ostatkah-na-skladah)   2. [Товарах с обязательной маркировкой](/openapi/reports#tag/Otchyot-o-tovarah-c-obyazatelnoj-markirovkoj)   3. [Удержаниях](/openapi/reports#tag/Otchyoty-ob-uderzhaniyah)   4. [Платной приёмке](/openapi/reports#tag/Platnaya-priyomka)   5. [Платном хранении](/openapi/reports#tag/Platnoe-hranenie)   6. [Продажах по регионам](/openapi/reports#tag/Prodazhi-po-regionam)   7. [Доле бренда в продажах](/openapi/reports#tag/Dolya-brenda-v-prodazhah)   8. [Скрытых товарах](/openapi/reports#tag/Skrytye-tovary)   9. [Возвратах и перемещении товаров](/openapi/reports#tag/Otchyot-o-vozvratah-i-peremeshenii-tovarov) 

API version: reports
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reports

import (
	"encoding/json"
	"time"
)

// checks if the PenaltyDataReportsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PenaltyDataReportsInner{}

// PenaltyDataReportsInner struct for PenaltyDataReportsInner
type PenaltyDataReportsInner struct {
	// Артикул WB
	NmId *int32 `json:"nmId,omitempty"`
	// ID замера
	DimId *int32 `json:"dimId,omitempty"`
	// Предмет
	Subject *string `json:"subject,omitempty"`
	// Разница в габаритах, %
	PrcOver *float32 `json:"prcOver,omitempty"`
	// Объём, л (фактические габариты)
	Volume *float32 `json:"volume,omitempty"`
	// Ширина, см (фактические габариты)
	Width *int32 `json:"width,omitempty"`
	// Длина, см (фактические габариты)
	Length *int32 `json:"length,omitempty"`
	// Высота, см (фактические габариты)
	Height *int32 `json:"height,omitempty"`
	// Объём, л (габариты карточки товара)
	VolumeSup *float32 `json:"volumeSup,omitempty"`
	// Ширина, см (габариты карточки товара)
	WidthSup *int32 `json:"widthSup,omitempty"`
	// Длина, см (габариты карточки товара)
	LengthSup *int32 `json:"lengthSup,omitempty"`
	// Высота, см (габариты карточки товара)
	HeightSup *int32 `json:"heightSup,omitempty"`
	// Фото замеров
	PhotoUrls []string `json:"photoUrls,omitempty"`
	// Дата штрафа
	DtBonus *time.Time `json:"dtBonus,omitempty"`
	// Статус обмера:   - `false` — отменён   - `true` — подтверждён 
	IsValid *bool `json:"isValid,omitempty"`
	// Дата и время подтверждения или отмены обмера
	IsValidDt *time.Time `json:"isValidDt,omitempty"`
	// Сумма сторно
	ReversalAmount *float32 `json:"reversalAmount,omitempty"`
	// Сумма штрафа
	PenaltyAmount *float32 `json:"penaltyAmount,omitempty"`
}

// NewPenaltyDataReportsInner instantiates a new PenaltyDataReportsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPenaltyDataReportsInner() *PenaltyDataReportsInner {
	this := PenaltyDataReportsInner{}
	return &this
}

// NewPenaltyDataReportsInnerWithDefaults instantiates a new PenaltyDataReportsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPenaltyDataReportsInnerWithDefaults() *PenaltyDataReportsInner {
	this := PenaltyDataReportsInner{}
	return &this
}

// GetNmId returns the NmId field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetNmId() int32 {
	if o == nil || IsNil(o.NmId) {
		var ret int32
		return ret
	}
	return *o.NmId
}

// GetNmIdOk returns a tuple with the NmId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetNmIdOk() (*int32, bool) {
	if o == nil || IsNil(o.NmId) {
		return nil, false
	}
	return o.NmId, true
}

// HasNmId returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasNmId() bool {
	if o != nil && !IsNil(o.NmId) {
		return true
	}

	return false
}

// SetNmId gets a reference to the given int32 and assigns it to the NmId field.
func (o *PenaltyDataReportsInner) SetNmId(v int32) {
	o.NmId = &v
}

// GetDimId returns the DimId field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetDimId() int32 {
	if o == nil || IsNil(o.DimId) {
		var ret int32
		return ret
	}
	return *o.DimId
}

// GetDimIdOk returns a tuple with the DimId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetDimIdOk() (*int32, bool) {
	if o == nil || IsNil(o.DimId) {
		return nil, false
	}
	return o.DimId, true
}

// HasDimId returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasDimId() bool {
	if o != nil && !IsNil(o.DimId) {
		return true
	}

	return false
}

// SetDimId gets a reference to the given int32 and assigns it to the DimId field.
func (o *PenaltyDataReportsInner) SetDimId(v int32) {
	o.DimId = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *PenaltyDataReportsInner) SetSubject(v string) {
	o.Subject = &v
}

// GetPrcOver returns the PrcOver field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetPrcOver() float32 {
	if o == nil || IsNil(o.PrcOver) {
		var ret float32
		return ret
	}
	return *o.PrcOver
}

// GetPrcOverOk returns a tuple with the PrcOver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetPrcOverOk() (*float32, bool) {
	if o == nil || IsNil(o.PrcOver) {
		return nil, false
	}
	return o.PrcOver, true
}

// HasPrcOver returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasPrcOver() bool {
	if o != nil && !IsNil(o.PrcOver) {
		return true
	}

	return false
}

// SetPrcOver gets a reference to the given float32 and assigns it to the PrcOver field.
func (o *PenaltyDataReportsInner) SetPrcOver(v float32) {
	o.PrcOver = &v
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetVolume() float32 {
	if o == nil || IsNil(o.Volume) {
		var ret float32
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetVolumeOk() (*float32, bool) {
	if o == nil || IsNil(o.Volume) {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasVolume() bool {
	if o != nil && !IsNil(o.Volume) {
		return true
	}

	return false
}

// SetVolume gets a reference to the given float32 and assigns it to the Volume field.
func (o *PenaltyDataReportsInner) SetVolume(v float32) {
	o.Volume = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetWidth() int32 {
	if o == nil || IsNil(o.Width) {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetWidthOk() (*int32, bool) {
	if o == nil || IsNil(o.Width) {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasWidth() bool {
	if o != nil && !IsNil(o.Width) {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *PenaltyDataReportsInner) SetWidth(v int32) {
	o.Width = &v
}

// GetLength returns the Length field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetLength() int32 {
	if o == nil || IsNil(o.Length) {
		var ret int32
		return ret
	}
	return *o.Length
}

// GetLengthOk returns a tuple with the Length field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetLengthOk() (*int32, bool) {
	if o == nil || IsNil(o.Length) {
		return nil, false
	}
	return o.Length, true
}

// HasLength returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasLength() bool {
	if o != nil && !IsNil(o.Length) {
		return true
	}

	return false
}

// SetLength gets a reference to the given int32 and assigns it to the Length field.
func (o *PenaltyDataReportsInner) SetLength(v int32) {
	o.Length = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetHeight() int32 {
	if o == nil || IsNil(o.Height) {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetHeightOk() (*int32, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *PenaltyDataReportsInner) SetHeight(v int32) {
	o.Height = &v
}

// GetVolumeSup returns the VolumeSup field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetVolumeSup() float32 {
	if o == nil || IsNil(o.VolumeSup) {
		var ret float32
		return ret
	}
	return *o.VolumeSup
}

// GetVolumeSupOk returns a tuple with the VolumeSup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetVolumeSupOk() (*float32, bool) {
	if o == nil || IsNil(o.VolumeSup) {
		return nil, false
	}
	return o.VolumeSup, true
}

// HasVolumeSup returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasVolumeSup() bool {
	if o != nil && !IsNil(o.VolumeSup) {
		return true
	}

	return false
}

// SetVolumeSup gets a reference to the given float32 and assigns it to the VolumeSup field.
func (o *PenaltyDataReportsInner) SetVolumeSup(v float32) {
	o.VolumeSup = &v
}

// GetWidthSup returns the WidthSup field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetWidthSup() int32 {
	if o == nil || IsNil(o.WidthSup) {
		var ret int32
		return ret
	}
	return *o.WidthSup
}

// GetWidthSupOk returns a tuple with the WidthSup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetWidthSupOk() (*int32, bool) {
	if o == nil || IsNil(o.WidthSup) {
		return nil, false
	}
	return o.WidthSup, true
}

// HasWidthSup returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasWidthSup() bool {
	if o != nil && !IsNil(o.WidthSup) {
		return true
	}

	return false
}

// SetWidthSup gets a reference to the given int32 and assigns it to the WidthSup field.
func (o *PenaltyDataReportsInner) SetWidthSup(v int32) {
	o.WidthSup = &v
}

// GetLengthSup returns the LengthSup field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetLengthSup() int32 {
	if o == nil || IsNil(o.LengthSup) {
		var ret int32
		return ret
	}
	return *o.LengthSup
}

// GetLengthSupOk returns a tuple with the LengthSup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetLengthSupOk() (*int32, bool) {
	if o == nil || IsNil(o.LengthSup) {
		return nil, false
	}
	return o.LengthSup, true
}

// HasLengthSup returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasLengthSup() bool {
	if o != nil && !IsNil(o.LengthSup) {
		return true
	}

	return false
}

// SetLengthSup gets a reference to the given int32 and assigns it to the LengthSup field.
func (o *PenaltyDataReportsInner) SetLengthSup(v int32) {
	o.LengthSup = &v
}

// GetHeightSup returns the HeightSup field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetHeightSup() int32 {
	if o == nil || IsNil(o.HeightSup) {
		var ret int32
		return ret
	}
	return *o.HeightSup
}

// GetHeightSupOk returns a tuple with the HeightSup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetHeightSupOk() (*int32, bool) {
	if o == nil || IsNil(o.HeightSup) {
		return nil, false
	}
	return o.HeightSup, true
}

// HasHeightSup returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasHeightSup() bool {
	if o != nil && !IsNil(o.HeightSup) {
		return true
	}

	return false
}

// SetHeightSup gets a reference to the given int32 and assigns it to the HeightSup field.
func (o *PenaltyDataReportsInner) SetHeightSup(v int32) {
	o.HeightSup = &v
}

// GetPhotoUrls returns the PhotoUrls field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetPhotoUrls() []string {
	if o == nil || IsNil(o.PhotoUrls) {
		var ret []string
		return ret
	}
	return o.PhotoUrls
}

// GetPhotoUrlsOk returns a tuple with the PhotoUrls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetPhotoUrlsOk() ([]string, bool) {
	if o == nil || IsNil(o.PhotoUrls) {
		return nil, false
	}
	return o.PhotoUrls, true
}

// HasPhotoUrls returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasPhotoUrls() bool {
	if o != nil && !IsNil(o.PhotoUrls) {
		return true
	}

	return false
}

// SetPhotoUrls gets a reference to the given []string and assigns it to the PhotoUrls field.
func (o *PenaltyDataReportsInner) SetPhotoUrls(v []string) {
	o.PhotoUrls = v
}

// GetDtBonus returns the DtBonus field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetDtBonus() time.Time {
	if o == nil || IsNil(o.DtBonus) {
		var ret time.Time
		return ret
	}
	return *o.DtBonus
}

// GetDtBonusOk returns a tuple with the DtBonus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetDtBonusOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DtBonus) {
		return nil, false
	}
	return o.DtBonus, true
}

// HasDtBonus returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasDtBonus() bool {
	if o != nil && !IsNil(o.DtBonus) {
		return true
	}

	return false
}

// SetDtBonus gets a reference to the given time.Time and assigns it to the DtBonus field.
func (o *PenaltyDataReportsInner) SetDtBonus(v time.Time) {
	o.DtBonus = &v
}

// GetIsValid returns the IsValid field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetIsValid() bool {
	if o == nil || IsNil(o.IsValid) {
		var ret bool
		return ret
	}
	return *o.IsValid
}

// GetIsValidOk returns a tuple with the IsValid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetIsValidOk() (*bool, bool) {
	if o == nil || IsNil(o.IsValid) {
		return nil, false
	}
	return o.IsValid, true
}

// HasIsValid returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasIsValid() bool {
	if o != nil && !IsNil(o.IsValid) {
		return true
	}

	return false
}

// SetIsValid gets a reference to the given bool and assigns it to the IsValid field.
func (o *PenaltyDataReportsInner) SetIsValid(v bool) {
	o.IsValid = &v
}

// GetIsValidDt returns the IsValidDt field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetIsValidDt() time.Time {
	if o == nil || IsNil(o.IsValidDt) {
		var ret time.Time
		return ret
	}
	return *o.IsValidDt
}

// GetIsValidDtOk returns a tuple with the IsValidDt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetIsValidDtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.IsValidDt) {
		return nil, false
	}
	return o.IsValidDt, true
}

// HasIsValidDt returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasIsValidDt() bool {
	if o != nil && !IsNil(o.IsValidDt) {
		return true
	}

	return false
}

// SetIsValidDt gets a reference to the given time.Time and assigns it to the IsValidDt field.
func (o *PenaltyDataReportsInner) SetIsValidDt(v time.Time) {
	o.IsValidDt = &v
}

// GetReversalAmount returns the ReversalAmount field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetReversalAmount() float32 {
	if o == nil || IsNil(o.ReversalAmount) {
		var ret float32
		return ret
	}
	return *o.ReversalAmount
}

// GetReversalAmountOk returns a tuple with the ReversalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetReversalAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.ReversalAmount) {
		return nil, false
	}
	return o.ReversalAmount, true
}

// HasReversalAmount returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasReversalAmount() bool {
	if o != nil && !IsNil(o.ReversalAmount) {
		return true
	}

	return false
}

// SetReversalAmount gets a reference to the given float32 and assigns it to the ReversalAmount field.
func (o *PenaltyDataReportsInner) SetReversalAmount(v float32) {
	o.ReversalAmount = &v
}

// GetPenaltyAmount returns the PenaltyAmount field value if set, zero value otherwise.
func (o *PenaltyDataReportsInner) GetPenaltyAmount() float32 {
	if o == nil || IsNil(o.PenaltyAmount) {
		var ret float32
		return ret
	}
	return *o.PenaltyAmount
}

// GetPenaltyAmountOk returns a tuple with the PenaltyAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PenaltyDataReportsInner) GetPenaltyAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.PenaltyAmount) {
		return nil, false
	}
	return o.PenaltyAmount, true
}

// HasPenaltyAmount returns a boolean if a field has been set.
func (o *PenaltyDataReportsInner) HasPenaltyAmount() bool {
	if o != nil && !IsNil(o.PenaltyAmount) {
		return true
	}

	return false
}

// SetPenaltyAmount gets a reference to the given float32 and assigns it to the PenaltyAmount field.
func (o *PenaltyDataReportsInner) SetPenaltyAmount(v float32) {
	o.PenaltyAmount = &v
}

func (o PenaltyDataReportsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PenaltyDataReportsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NmId) {
		toSerialize["nmId"] = o.NmId
	}
	if !IsNil(o.DimId) {
		toSerialize["dimId"] = o.DimId
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.PrcOver) {
		toSerialize["prcOver"] = o.PrcOver
	}
	if !IsNil(o.Volume) {
		toSerialize["volume"] = o.Volume
	}
	if !IsNil(o.Width) {
		toSerialize["width"] = o.Width
	}
	if !IsNil(o.Length) {
		toSerialize["length"] = o.Length
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.VolumeSup) {
		toSerialize["volumeSup"] = o.VolumeSup
	}
	if !IsNil(o.WidthSup) {
		toSerialize["widthSup"] = o.WidthSup
	}
	if !IsNil(o.LengthSup) {
		toSerialize["lengthSup"] = o.LengthSup
	}
	if !IsNil(o.HeightSup) {
		toSerialize["heightSup"] = o.HeightSup
	}
	if !IsNil(o.PhotoUrls) {
		toSerialize["photoUrls"] = o.PhotoUrls
	}
	if !IsNil(o.DtBonus) {
		toSerialize["dtBonus"] = o.DtBonus
	}
	if !IsNil(o.IsValid) {
		toSerialize["isValid"] = o.IsValid
	}
	if !IsNil(o.IsValidDt) {
		toSerialize["isValidDt"] = o.IsValidDt
	}
	if !IsNil(o.ReversalAmount) {
		toSerialize["reversalAmount"] = o.ReversalAmount
	}
	if !IsNil(o.PenaltyAmount) {
		toSerialize["penaltyAmount"] = o.PenaltyAmount
	}
	return toSerialize, nil
}

type NullablePenaltyDataReportsInner struct {
	value *PenaltyDataReportsInner
	isSet bool
}

func (v NullablePenaltyDataReportsInner) Get() *PenaltyDataReportsInner {
	return v.value
}

func (v *NullablePenaltyDataReportsInner) Set(val *PenaltyDataReportsInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePenaltyDataReportsInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePenaltyDataReportsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePenaltyDataReportsInner(val *PenaltyDataReportsInner) *NullablePenaltyDataReportsInner {
	return &NullablePenaltyDataReportsInner{value: val, isSet: true}
}

func (v NullablePenaltyDataReportsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePenaltyDataReportsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


