/*
 * Общение с покупателями
 *
 * <div class=\"description_important\">     Узнать больше об общении с покупателями можно в <a href=\"https://seller.wildberries.ru/instructions/category/f7f6c465-dd12-422d-80a0-a6d9562115d5?goBackOption=prevRoute&categoryId=30817062-14cc-4a82-bc78-3600c2b0685b\">справочном центре</a> </div>  С помощью методов общения с покупателями вы можете работать с:   1. [Вопросами](/openapi/user-communication#tag/Voprosy) и [отзывами](/openapi/user-communication#tag/Otzyvy) покупателей   2. [Закреплёнными отзывами](/openapi/user-communication#tag/Zakreplyonnye-otzyvy)   3. [Чатами с покупателями](/openapi/user-communication#tag/Chat-s-pokupatelyami)   4. [Заявками покупателей на возврат](/openapi/user-communication#tag/Vozvraty-pokupatelyami)    <div class=\"description_ref\">     Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/278\">инструкции по работе с разделом Общение с покупателями</a>   </div> 
 *
 * The version of the OpenAPI document: communication
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1FeedbacksAnswerPostRequest {
    /// ID отзыва
    #[serde(rename = "id")]
    pub id: String,
    /// Текст ответа
    #[serde(rename = "text")]
    pub text: String,
}

impl ApiV1FeedbacksAnswerPostRequest {
    pub fn new(id: String, text: String) -> ApiV1FeedbacksAnswerPostRequest {
        ApiV1FeedbacksAnswerPostRequest {
            id,
            text,
        }
    }
}

