/* tslint:disable */
/* eslint-disable */
/**
 * Общее
 * <div class=\"api-block\">  В этом разделе: - [общая информация о WB API](/openapi/api-information#tag/Vvedenie) - как [начать работу с WB API](/openapi/api-information#tag/Vvedenie/Kak-nachat-rabotu-s-API) - как [авторизоваться](/openapi/api-information#tag/Avtorizaciya) и [создавать токены](/openapi/api-information#tag/Avtorizaciya/Kak-sozdat-personalnyj-bazovyj-ili-testovyj-token) - основные [статус-коды ответов](/openapi/api-information#tag/Vvedenie/Status-kody-HTTP) - [лимиты запросов](/openapi/api-information#tag/Vvedenie/Limity-zaprosov) - как обратиться в [поддержку](/openapi/api-information#tag/Vvedenie/Podderzhka)  С помощью методов этого раздела вы можете: - проверить [подключение к WB API](/openapi/api-information#tag/Proverka-podklyucheniya-k-WB-API/paths/~1ping/get) - получить [новости портала продавцов](/openapi/api-information#tag/API-novostej/paths/~1api~1communications~1v2~1news/get) - получить [информацию о продавце](/openapi/api-information#tag/Informaciya-o-prodavce/paths/~1api~1v1~1seller-info/get) - [управлять пользователями продавца](/openapi/api-information#tag/Upravlenie-polzovatelyami-prodavca)  </div> 
 *
 * The version of the OpenAPI document: general
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiCommunicationsV2NewsGet200ResponseDataInner } from './ApiCommunicationsV2NewsGet200ResponseDataInner';
import {
    ApiCommunicationsV2NewsGet200ResponseDataInnerFromJSON,
    ApiCommunicationsV2NewsGet200ResponseDataInnerFromJSONTyped,
    ApiCommunicationsV2NewsGet200ResponseDataInnerToJSON,
    ApiCommunicationsV2NewsGet200ResponseDataInnerToJSONTyped,
} from './ApiCommunicationsV2NewsGet200ResponseDataInner';

/**
 * 
 * @export
 * @interface ApiCommunicationsV2NewsGet200Response
 */
export interface ApiCommunicationsV2NewsGet200Response {
    /**
     * Новости
     * @type {Array<ApiCommunicationsV2NewsGet200ResponseDataInner>}
     * @memberof ApiCommunicationsV2NewsGet200Response
     */
    data?: Array<ApiCommunicationsV2NewsGet200ResponseDataInner>;
}

/**
 * Check if a given object implements the ApiCommunicationsV2NewsGet200Response interface.
 */
export function instanceOfApiCommunicationsV2NewsGet200Response(value: object): value is ApiCommunicationsV2NewsGet200Response {
    return true;
}

export function ApiCommunicationsV2NewsGet200ResponseFromJSON(json: any): ApiCommunicationsV2NewsGet200Response {
    return ApiCommunicationsV2NewsGet200ResponseFromJSONTyped(json, false);
}

export function ApiCommunicationsV2NewsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCommunicationsV2NewsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ApiCommunicationsV2NewsGet200ResponseDataInnerFromJSON)),
    };
}

export function ApiCommunicationsV2NewsGet200ResponseToJSON(json: any): ApiCommunicationsV2NewsGet200Response {
    return ApiCommunicationsV2NewsGet200ResponseToJSONTyped(json, false);
}

export function ApiCommunicationsV2NewsGet200ResponseToJSONTyped(value?: ApiCommunicationsV2NewsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ApiCommunicationsV2NewsGet200ResponseDataInnerToJSON)),
    };
}

