/* tslint:disable */
/* eslint-disable */
/**
 * Общее
 * В этом разделе:   - [общая информация о WB API](/openapi/api-information#tag/Vvedenie)   - как [начать работу с WB API](/openapi/api-information#tag/Vvedenie/Kak-nachat-rabotu-s-API)   - как [авторизоваться](/openapi/api-information#tag/Avtorizaciya) и [создавать токены](/openapi/api-information#tag/Avtorizaciya/Kak-sozdat-personalnyj-bazovyj-ili-testovyj-token)   - основные [статус-коды ответов](/openapi/api-information#tag/Vvedenie/Status-kody-HTTP)   - [лимиты запросов](/openapi/api-information#tag/Vvedenie/Limity-zaprosov)   - как обратиться в [поддержку](/openapi/api-information#tag/Vvedenie/Podderzhka)  С помощью методов этого раздела вы можете:   - проверить [подключение к WB API](/openapi/api-information#tag/Proverka-podklyucheniya-k-WB-API/paths/~1ping/get)   - получить [новости портала продавцов](/openapi/api-information#tag/API-novostej/paths/~1api~1communications~1v2~1news/get)   - получить [информацию о продавце](/openapi/api-information#tag/Informaciya-o-prodavce/paths/~1api~1v1~1seller-info/get)   - [управлять пользователями продавца](/openapi/api-information#tag/Upravlenie-polzovatelyami-prodavca) 
 *
 * The version of the OpenAPI document: general
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInner
 */
export interface ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInner {
    /**
     * ID тега
     * @type {number}
     * @memberof ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInner
     */
    id?: number;
    /**
     * Название тега
     * @type {string}
     * @memberof ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInner
     */
    name?: string;
}

/**
 * Check if a given object implements the ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInner interface.
 */
export function instanceOfApiCommunicationsV2NewsGet200ResponseDataInnerTypesInner(value: object): value is ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInner {
    return true;
}

export function ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInnerFromJSON(json: any): ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInner {
    return ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInnerFromJSONTyped(json, false);
}

export function ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInnerToJSON(json: any): ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInner {
    return ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInnerToJSONTyped(json, false);
}

export function ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInnerToJSONTyped(value?: ApiCommunicationsV2NewsGet200ResponseDataInnerTypesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

