/*
 * Заказы Самовывоз
 *
 * <div class=\"api-block\">  Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [идентификаторами маркировки](/openapi/in-store-pickup#tag/in-store-pickup-label-identifiers) заказов модели Самовывоз.  </div> 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiOrdersMetaResponse {
    /// Идентификаторы маркировки сборочных заданий
    #[serde(rename = "meta")]
    pub meta: Vec<models::ApiOrderMetaV2>,
}

impl ApiOrdersMetaResponse {
    pub fn new(meta: Vec<models::ApiOrderMetaV2>) -> ApiOrdersMetaResponse {
        ApiOrdersMetaResponse {
            meta,
        }
    }
}

