/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBW
 * Управление [сборочными заданиями](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW) и [метаданными](/openapi/orders-dbw#tag/Metadannye-DBW) заказов DBW (Доставка курьером WB).
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV3DbwOrdersOrderIdMetaGtinPutRequest
 */
export interface ApiV3DbwOrdersOrderIdMetaGtinPutRequest {
    /**
     * GTIN
     * @type {string}
     * @memberof ApiV3DbwOrdersOrderIdMetaGtinPutRequest
     */
    gtin: string;
}

/**
 * Check if a given object implements the ApiV3DbwOrdersOrderIdMetaGtinPutRequest interface.
 */
export function instanceOfApiV3DbwOrdersOrderIdMetaGtinPutRequest(value: object): value is ApiV3DbwOrdersOrderIdMetaGtinPutRequest {
    if (!('gtin' in value) || value['gtin'] === undefined) return false;
    return true;
}

export function ApiV3DbwOrdersOrderIdMetaGtinPutRequestFromJSON(json: any): ApiV3DbwOrdersOrderIdMetaGtinPutRequest {
    return ApiV3DbwOrdersOrderIdMetaGtinPutRequestFromJSONTyped(json, false);
}

export function ApiV3DbwOrdersOrderIdMetaGtinPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV3DbwOrdersOrderIdMetaGtinPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'gtin': json['gtin'],
    };
}

export function ApiV3DbwOrdersOrderIdMetaGtinPutRequestToJSON(json: any): ApiV3DbwOrdersOrderIdMetaGtinPutRequest {
    return ApiV3DbwOrdersOrderIdMetaGtinPutRequestToJSONTyped(json, false);
}

export function ApiV3DbwOrdersOrderIdMetaGtinPutRequestToJSONTyped(value?: ApiV3DbwOrdersOrderIdMetaGtinPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gtin': value['gtin'],
    };
}

