/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBW
 * Управление [сборочными заданиями](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW) и [метаданными](/openapi/orders-dbw#tag/Metadannye-DBW) заказов DBW (Доставка курьером WB).
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV3DbwOrdersStatusPost200ResponseOrdersInner } from './ApiV3DbwOrdersStatusPost200ResponseOrdersInner';
import {
    ApiV3DbwOrdersStatusPost200ResponseOrdersInnerFromJSON,
    ApiV3DbwOrdersStatusPost200ResponseOrdersInnerFromJSONTyped,
    ApiV3DbwOrdersStatusPost200ResponseOrdersInnerToJSON,
    ApiV3DbwOrdersStatusPost200ResponseOrdersInnerToJSONTyped,
} from './ApiV3DbwOrdersStatusPost200ResponseOrdersInner';

/**
 * 
 * @export
 * @interface ApiV3DbwOrdersStatusPost200Response
 */
export interface ApiV3DbwOrdersStatusPost200Response {
    /**
     * 
     * @type {Array<ApiV3DbwOrdersStatusPost200ResponseOrdersInner>}
     * @memberof ApiV3DbwOrdersStatusPost200Response
     */
    orders?: Array<ApiV3DbwOrdersStatusPost200ResponseOrdersInner>;
}

/**
 * Check if a given object implements the ApiV3DbwOrdersStatusPost200Response interface.
 */
export function instanceOfApiV3DbwOrdersStatusPost200Response(value: object): value is ApiV3DbwOrdersStatusPost200Response {
    return true;
}

export function ApiV3DbwOrdersStatusPost200ResponseFromJSON(json: any): ApiV3DbwOrdersStatusPost200Response {
    return ApiV3DbwOrdersStatusPost200ResponseFromJSONTyped(json, false);
}

export function ApiV3DbwOrdersStatusPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV3DbwOrdersStatusPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'orders': json['orders'] == null ? undefined : ((json['orders'] as Array<any>).map(ApiV3DbwOrdersStatusPost200ResponseOrdersInnerFromJSON)),
    };
}

export function ApiV3DbwOrdersStatusPost200ResponseToJSON(json: any): ApiV3DbwOrdersStatusPost200Response {
    return ApiV3DbwOrdersStatusPost200ResponseToJSONTyped(json, false);
}

export function ApiV3DbwOrdersStatusPost200ResponseToJSONTyped(value?: ApiV3DbwOrdersStatusPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orders': value['orders'] == null ? undefined : ((value['orders'] as Array<any>).map(ApiV3DbwOrdersStatusPost200ResponseOrdersInnerToJSON)),
    };
}

