/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBW
 * Управление [сборочными заданиями](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW) и [метаданными](/openapi/orders-dbw#tag/Metadannye-DBW) заказов DBW (Доставка курьером WB).
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV3DbwOrdersStickersPostRequest
 */
export interface ApiV3DbwOrdersStickersPostRequest {
    /**
     * Список ID сборочных заданий
     * @type {Array<number>}
     * @memberof ApiV3DbwOrdersStickersPostRequest
     */
    orders?: Array<number>;
}

/**
 * Check if a given object implements the ApiV3DbwOrdersStickersPostRequest interface.
 */
export function instanceOfApiV3DbwOrdersStickersPostRequest(value: object): value is ApiV3DbwOrdersStickersPostRequest {
    return true;
}

export function ApiV3DbwOrdersStickersPostRequestFromJSON(json: any): ApiV3DbwOrdersStickersPostRequest {
    return ApiV3DbwOrdersStickersPostRequestFromJSONTyped(json, false);
}

export function ApiV3DbwOrdersStickersPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV3DbwOrdersStickersPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orders': json['orders'] == null ? undefined : json['orders'],
    };
}

export function ApiV3DbwOrdersStickersPostRequestToJSON(json: any): ApiV3DbwOrdersStickersPostRequest {
    return ApiV3DbwOrdersStickersPostRequestToJSONTyped(json, false);
}

export function ApiV3DbwOrdersStickersPostRequestToJSONTyped(value?: ApiV3DbwOrdersStickersPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orders': value['orders'],
    };
}

