/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBW
 * Управление [сборочными заданиями](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW) и [метаданными](/openapi/orders-dbw#tag/Metadannye-DBW) заказов DBW (Доставка курьером WB).
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV3DbwOrdersStatusPostRequest
 */
export interface ApiV3DbwOrdersStatusPostRequest {
    /**
     * Список ID сборочных заданий
     * @type {Array<number>}
     * @memberof ApiV3DbwOrdersStatusPostRequest
     */
    orders: Array<number>;
}

/**
 * Check if a given object implements the ApiV3DbwOrdersStatusPostRequest interface.
 */
export function instanceOfApiV3DbwOrdersStatusPostRequest(value: object): value is ApiV3DbwOrdersStatusPostRequest {
    if (!('orders' in value) || value['orders'] === undefined) return false;
    return true;
}

export function ApiV3DbwOrdersStatusPostRequestFromJSON(json: any): ApiV3DbwOrdersStatusPostRequest {
    return ApiV3DbwOrdersStatusPostRequestFromJSONTyped(json, false);
}

export function ApiV3DbwOrdersStatusPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV3DbwOrdersStatusPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orders': json['orders'],
    };
}

export function ApiV3DbwOrdersStatusPostRequestToJSON(json: any): ApiV3DbwOrdersStatusPostRequest {
    return ApiV3DbwOrdersStatusPostRequestToJSONTyped(json, false);
}

export function ApiV3DbwOrdersStatusPostRequestToJSONTyped(value?: ApiV3DbwOrdersStatusPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orders': value['orders'],
    };
}

