/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBW
 * С помощью методов Заказы DBW (Доставка курьером WB) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW), управлять статусами и отменять сборочные задания   - получать, добавлять, редактировать и удалять [метаданные](/openapi/orders-dbw#tag/Metadannye-DBW) сборочных заданий  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/241\">инструкции по работе с заказами DBW</a> </div> 
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClientInfo } from './ClientInfo';
import {
    ClientInfoFromJSON,
    ClientInfoFromJSONTyped,
    ClientInfoToJSON,
    ClientInfoToJSONTyped,
} from './ClientInfo';

/**
 * 
 * @export
 * @interface ClientInfoResp
 */
export interface ClientInfoResp {
    /**
     * Информация о покупателях
     * @type {Array<ClientInfo>}
     * @memberof ClientInfoResp
     */
    orders?: Array<ClientInfo>;
}

/**
 * Check if a given object implements the ClientInfoResp interface.
 */
export function instanceOfClientInfoResp(value: object): value is ClientInfoResp {
    return true;
}

export function ClientInfoRespFromJSON(json: any): ClientInfoResp {
    return ClientInfoRespFromJSONTyped(json, false);
}

export function ClientInfoRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientInfoResp {
    if (json == null) {
        return json;
    }
    return {
        
        'orders': json['orders'] == null ? undefined : ((json['orders'] as Array<any>).map(ClientInfoFromJSON)),
    };
}

export function ClientInfoRespToJSON(json: any): ClientInfoResp {
    return ClientInfoRespToJSONTyped(json, false);
}

export function ClientInfoRespToJSONTyped(value?: ClientInfoResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orders': value['orders'] == null ? undefined : ((value['orders'] as Array<any>).map(ClientInfoToJSON)),
    };
}

