/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBW
 * Управление [сборочными заданиями](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW) и [метаданными](/openapi/orders-dbw#tag/Metadannye-DBW) заказов DBW (Доставка курьером WB).
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * IMEI
 * @export
 * @interface MetaImei
 */
export interface MetaImei {
    /**
     * 
     * @type {string}
     * @memberof MetaImei
     */
    value?: string | null;
}

/**
 * Check if a given object implements the MetaImei interface.
 */
export function instanceOfMetaImei(value: object): value is MetaImei {
    return true;
}

export function MetaImeiFromJSON(json: any): MetaImei {
    return MetaImeiFromJSONTyped(json, false);
}

export function MetaImeiFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaImei {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function MetaImeiToJSON(json: any): MetaImei {
    return MetaImeiToJSONTyped(json, false);
}

export function MetaImeiToJSONTyped(value?: MetaImei | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

